<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Ara3D.SDK.Core" Version="$(Ara3DVersion)" />
    <ProjectReference Include="..\..\src\Plato.Compiler\Plato.Compiler.csproj" />
    <ProjectReference Include="..\Plato.CSharpWriter\Plato.CSharpWriter.csproj" />
  </ItemGroup>
</Project>
