// Autogenerated file: DO NOT EDIT
// Created on 2026-07-13 12:58:26 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    // Scalar-erased emission (--scalar=float): Integer => int
    public static class IntegerExtensions
    {
        [MethodImpl(AggressiveInlining)] public static int Add(this int a, int b) => ((Integer)a) + ((Integer)b);
        [MethodImpl(AggressiveInlining)] public static bool LessThan(this int a, int b) => ((Integer)a) < ((Integer)b);
        [MethodImpl(AggressiveInlining)] public static bool NotEquals(this int a, int b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static bool NotEquals(this Integer a, int b) => !((int)a).Equals(b);
        [MethodImpl(AggressiveInlining)] public static Ara3D.Collections.ReadOnlyList2D<T> MakeArray2D<T>(this int columns, int rows, System.Func<Integer, Integer, T> f) => ((Integer)columns).MakeArray2D(rows, f);
        // Wrapper-receiver bridges: call sites the writer could not prove scalar keep
        // Integer-typed intermediates (unerased kept members, handwritten intrinsics).
        [MethodImpl(AggressiveInlining)] public static int Add(this Integer a, int b) => ((int)a).Add(b);
        [MethodImpl(AggressiveInlining)] public static bool LessThan(this Integer a, int b) => ((int)a).LessThan(b);
    }
    // scalar-erasure drop (Integer): operator + (via the Integer wrapper operator); kept as method Add()
    // scalar-erasure drop (Integer): operator < (via the Integer wrapper operator); kept as method LessThan()
}
