// Autogenerated file: DO NOT EDIT
// Created on 2026-07-13 12:58:26 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Line3D
    {
        // Fields
        [DataMember] public readonly Point3D A;
        [DataMember] public readonly Point3D B;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Line3D WithA(Point3D a) => new Line3D(a, B);
        [MethodImpl(AggressiveInlining)] public Line3D WithB(Point3D b) => new Line3D(A, b);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Line3D(Point3D a, Point3D b) { A = a; B = b; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Line3D Create(Point3D a, Point3D b) => new Line3D(a, b);

        // Static default implementation
        public static readonly Line3D Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Point3D, Point3D)(Line3D self) => (self.A, self.B);
        [MethodImpl(AggressiveInlining)] public static implicit operator Line3D((Point3D, Point3D) value) => new Line3D(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Point3D a, out Point3D b) { a = A; b = B;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public bool Equals(Line3D other) => A.Equals(other.A) && B.Equals(other.B);
        [MethodImpl(AggressiveInlining)] public bool NotEquals(Line3D other) => !(A.Equals(other.A) && B.Equals(other.B));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Line3D other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(A, B);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"A\" = {A}, \"B\" = {B} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class Line3DExtensions
    {
    }
}
