// Autogenerated file: DO NOT EDIT
// Created on 2026-07-13 12:58:26 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Point3D: IArrayLike<Point3D, float>
    {
        // Fields
        [DataMember] public readonly float X;
        [DataMember] public readonly float Y;
        [DataMember] public readonly float Z;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Point3D WithX(float x) => new Point3D(x, Y, Z);
        [MethodImpl(AggressiveInlining)] public Point3D WithY(float y) => new Point3D(X, y, Z);
        [MethodImpl(AggressiveInlining)] public Point3D WithZ(float z) => new Point3D(X, Y, z);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Point3D(float x, float y, float z) { X = x; Y = y; Z = z; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Point3D Create(float x, float y, float z) => new Point3D(x, y, z);

        // Static default implementation
        public static readonly Point3D Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (float, float, float)(Point3D self) => (self.X, self.Y, self.Z);
        [MethodImpl(AggressiveInlining)] public static implicit operator Point3D((float, float, float) value) => new Point3D(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out float x, out float y, out float z) { x = X; y = Y; z = Z;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public bool Equals(Point3D other) => X.Equals(other.X) && Y.Equals(other.Y) && Z.Equals(other.Z);
        [MethodImpl(AggressiveInlining)] public bool NotEquals(Point3D other) => !(X.Equals(other.X) && Y.Equals(other.Y) && Z.Equals(other.Z));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Point3D other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(X, Y, Z);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"X\" = {X}, \"Y\" = {Y}, \"Z\" = {Z} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        [MethodImpl(AggressiveInlining)] public int NumComponents() => 3;
        [MethodImpl(AggressiveInlining)] public IReadOnlyList<float> Components() => Intrinsics.MakeArray<float>(X, Y, Z);
        [MethodImpl(AggressiveInlining)] public static Point3D CreateFromComponents(IReadOnlyList<float> numbers) => new Point3D(numbers[0], numbers[1], numbers[2]);

        [MethodImpl(AggressiveInlining)] public static Point3D CreateFromComponent(float x) => new Point3D(x, x, x);

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public float At(int n) => this.Components()[n];

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class Point3DExtensions
    {
    }
}
