// Autogenerated file: DO NOT EDIT
// Created on 2026-07-13 12:58:26 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class ArrayLibrary
    {
        [MethodImpl(AggressiveInlining)] public static Point3D Reverse(this Point3D xs) => Point3D.CreateFromComponents(xs.Components().Reverse());
        [MethodImpl(AggressiveInlining)] public static Point3D MapComponents(this Point3D x, System.Func<float, float> f) => Point3D.CreateFromComponents(x.Components().Map(f));
        [MethodImpl(AggressiveInlining)] public static Point3D ZipComponents(this Point3D a, Point3D b, System.Func<float, float, float> f) => Point3D.CreateFromComponents(a.Components().Zip(b.Components(), f));
        [MethodImpl(AggressiveInlining)] public static Point3D ZipComponents(this Point3D a, Point3D b, Point3D c, System.Func<float, float, float, float> f) => Point3D.CreateFromComponents(a.Components().Zip(b.Components(), c.Components(), f));
        [MethodImpl(AggressiveInlining)] public static bool AllZipComponents(this Point3D a, Point3D b, System.Func<float, float, bool> f) => a.Components().Zip(b.Components(), f).All((x)  => x);
        [MethodImpl(AggressiveInlining)] public static bool AnyZipComponents(this Point3D a, Point3D b, System.Func<float, float, bool> f) => a.Components().Zip(b.Components(), f).Any((x)  => x);
        [MethodImpl(AggressiveInlining)] public static bool AllComponents(this Point3D x, System.Func<float, bool> predicate) => x.Components().All(predicate);
        [MethodImpl(AggressiveInlining)] public static bool AnyComponent(this Point3D x, System.Func<float, bool> predicate) => x.Components().Any(predicate);
        [MethodImpl(AggressiveInlining)] public static Bounds3D Reverse(this Bounds3D xs) => Bounds3D.CreateFromComponents(xs.Components().Reverse());
        [MethodImpl(AggressiveInlining)] public static Bounds3D MapComponents(this Bounds3D x, System.Func<Point3D, Point3D> f) => Bounds3D.CreateFromComponents(x.Components().Map(f));
        [MethodImpl(AggressiveInlining)] public static Bounds3D ZipComponents(this Bounds3D a, Bounds3D b, System.Func<Point3D, Point3D, Point3D> f) => Bounds3D.CreateFromComponents(a.Components().Zip(b.Components(), f));
        [MethodImpl(AggressiveInlining)] public static Bounds3D ZipComponents(this Bounds3D a, Bounds3D b, Bounds3D c, System.Func<Point3D, Point3D, Point3D, Point3D> f) => Bounds3D.CreateFromComponents(a.Components().Zip(b.Components(), c.Components(), f));
        [MethodImpl(AggressiveInlining)] public static bool AllZipComponents(this Bounds3D a, Bounds3D b, System.Func<Point3D, Point3D, bool> f) => a.Components().Zip(b.Components(), f).All((x)  => x);
        [MethodImpl(AggressiveInlining)] public static bool AnyZipComponents(this Bounds3D a, Bounds3D b, System.Func<Point3D, Point3D, bool> f) => a.Components().Zip(b.Components(), f).Any((x)  => x);
        [MethodImpl(AggressiveInlining)] public static bool AllComponents(this Bounds3D x, System.Func<Point3D, bool> predicate) => x.Components().All(predicate);
        [MethodImpl(AggressiveInlining)] public static bool AnyComponent(this Bounds3D x, System.Func<Point3D, bool> predicate) => x.Components().Any(predicate);
    }
}
