// Autogenerated file: DO NOT EDIT
// Created on 2026-07-13 12:58:26 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class Points
    {
        [MethodImpl(AggressiveInlining)] public static Point3D Lerp(this Point3D a, Point3D b, float t){
            var _var0 = t;
            return a.ZipComponents(b, (a1, b1)  => a1.Lerp(b1, ((float)_var0)));
        }

        [MethodImpl(AggressiveInlining)] public static Point3D MinComponents(this Point3D a, Point3D b) => a.ZipComponents(b, (a1, b1)  => a1.Min(b1));
        [MethodImpl(AggressiveInlining)] public static Point3D MaxComponents(this Point3D a, Point3D b) => a.ZipComponents(b, (a1, b1)  => a1.Max(b1));
    }
}
