// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 11:45:44 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Angle: IMeasure<Angle>
    {
        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Angle Create() => new Angle();

        // Static default implementation
        public static readonly Angle Default = default;

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Angle other) => Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Angle other) => !Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Angle other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(Angle a, Angle b) => a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(Angle a, Angle b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Value.GetHashCode();
        [MethodImpl(AggressiveInlining)] public override string ToString() => Value.ToString();

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public Integer NumComponents { [MethodImpl(AggressiveInlining)] get => 1; }
        public IReadOnlyList<Number> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Number>(Value); }
        [MethodImpl(AggressiveInlining)] public static Angle CreateFromComponents(IReadOnlyList<Number> numbers) => new Angle(numbers[0]);

        [MethodImpl(AggressiveInlining)] public static Angle CreateFromComponent(Number x) => new Angle(x);

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public Angle Add(Angle b) => this + b;
        [MethodImpl(AggressiveInlining)] public Angle Divide(Number x) => this / x;
        [MethodImpl(AggressiveInlining)] public Boolean GreaterThan(Angle b) => this > b;
        [MethodImpl(AggressiveInlining)] public Boolean GreaterThanOrEquals(Angle b) => this >= b;
        [MethodImpl(AggressiveInlining)] public Boolean LessThan(Angle b) => this < b;
        [MethodImpl(AggressiveInlining)] public Boolean LessThanOrEquals(Angle b) => this <= b;
        [MethodImpl(AggressiveInlining)] public Angle Multiply(Number x) => this * x;
        public Angle Negative { [MethodImpl(AggressiveInlining)] get => -this; }
        [MethodImpl(AggressiveInlining)] public Angle Subtract(Angle b) => this - b;
        public static Angle Zero { [MethodImpl(AggressiveInlining)] get  => Angle.CreateFromComponent(((Number)0)); } 
        public static Angle One { [MethodImpl(AggressiveInlining)] get  => Angle.CreateFromComponent(((Number)1)); } 
        public static Angle MinValue { [MethodImpl(AggressiveInlining)] get  => Angle.CreateFromComponent(Ara3D.Geometry.Number.MinValue); } 
        public static Angle MaxValue { [MethodImpl(AggressiveInlining)] get  => Angle.CreateFromComponent(Ara3D.Geometry.Number.MaxValue); } 
        public Angle Abs { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Abs); } 
        public Angle BitDecrement { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.BitDecrement); } 
        public Angle BitIncrement { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.BitIncrement); } 
        public Angle Cbrt { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Cbrt); } 
        public Angle Ceiling { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Ceiling); } 
        public Angle Exp { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Exp); } 
        public Angle Floor { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Floor); } 
        public Angle ILogB { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ILogB); } 
        public Angle Log10 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Log10); } 
        public Angle Log2 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Log2); } 
        public Angle NaturalLog { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.NaturalLog); } 
        public Angle Reciprocal { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Reciprocal); } 
        public Angle ReciprocalEstimate { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ReciprocalEstimate); } 
        public Angle ReciprocalSquareRootEstimate { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ReciprocalSquareRootEstimate); } 
        public Boolean AlmostZero { [MethodImpl(AggressiveInlining)] get  => this.AllComponents((x)  => x.AlmostZero); } 
        [MethodImpl(AggressiveInlining)] public Angle Lerp(Angle b, Number t){
            var _var12 = t;
            return this.ZipComponents(b, (a1, b1)  => a1.Lerp(b1, _var12));
        }

        public Angle Pow2 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow2); } 
        public Angle Pow3 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow3); } 
        public Angle Sqr { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Sqr); } 
        public Angle Sqrt { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Sqrt); } 
        [MethodImpl(AggressiveInlining)] public Number At(Integer n) => this.Components[n];
        public Number this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Angle Modulo(Number other) => this % other;
    }
    // Extension methods for the type
    public static class AngleExtensions
    {
        [MethodImpl(AggressiveInlining)] public static Angle Modulo(this Angle self, Number other) => self.Modulo(other);
        [MethodImpl(AggressiveInlining)] public static Angle Add(this Angle a, Angle b) => a.Add(b);
        [MethodImpl(AggressiveInlining)] public static Integer CompareTo(this Angle self, Angle other) => self.CompareTo(other);
        [MethodImpl(AggressiveInlining)] public static Number Cos(this Angle self) => self.Cos;
        [MethodImpl(AggressiveInlining)] public static Number Cosh(this Angle self) => self.Cosh;
        [MethodImpl(AggressiveInlining)] public static Angle Divide(this Angle a, Number x) => a.Divide(x);
        [MethodImpl(AggressiveInlining)] public static Boolean GreaterThan(this Angle a, Angle b) => a.GreaterThan(b);
        [MethodImpl(AggressiveInlining)] public static Boolean GreaterThanOrEquals(this Angle a, Angle b) => a.GreaterThanOrEquals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean LessThan(this Angle a, Angle b) => a.LessThan(b);
        [MethodImpl(AggressiveInlining)] public static Boolean LessThanOrEquals(this Angle a, Angle b) => a.LessThanOrEquals(b);
        [MethodImpl(AggressiveInlining)] public static Angle Multiply(this Angle a, Number x) => a.Multiply(x);
        [MethodImpl(AggressiveInlining)] public static Angle Negative(this Angle n) => n.Negative;
        [MethodImpl(AggressiveInlining)] public static Number Radians(this Angle self) => self.Radians;
        [MethodImpl(AggressiveInlining)] public static Number Sin(this Angle self) => self.Sin;
        [MethodImpl(AggressiveInlining)] public static Tuple2<Number, Number> SinCos(this Angle self) => self.SinCos;
        [MethodImpl(AggressiveInlining)] public static Number Sinh(this Angle self) => self.Sinh;
        [MethodImpl(AggressiveInlining)] public static Angle Subtract(this Angle a, Angle b) => a.Subtract(b);
        [MethodImpl(AggressiveInlining)] public static Number Tan(this Angle self) => self.Tan;
        [MethodImpl(AggressiveInlining)] public static Number Tanh(this Angle self) => self.Tanh;
    }
}
