// Autogenerated file: DO NOT EDIT
// Created on 2026-07-07 10:58:03 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct ByteRGBA: ICoordinate
    {
        // Fields
        [DataMember] public readonly Integer R;
        [DataMember] public readonly Integer G;
        [DataMember] public readonly Integer B;
        [DataMember] public readonly Integer A;

        // With functions 
        [MethodImpl(AggressiveInlining)] public ByteRGBA WithR(Integer r) => new ByteRGBA(r, G, B, A);
        [MethodImpl(AggressiveInlining)] public ByteRGBA WithG(Integer g) => new ByteRGBA(R, g, B, A);
        [MethodImpl(AggressiveInlining)] public ByteRGBA WithB(Integer b) => new ByteRGBA(R, G, b, A);
        [MethodImpl(AggressiveInlining)] public ByteRGBA WithA(Integer a) => new ByteRGBA(R, G, B, a);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public ByteRGBA(Integer r, Integer g, Integer b, Integer a) { R = r; G = g; B = b; A = a; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static ByteRGBA Create(Integer r, Integer g, Integer b, Integer a) => new ByteRGBA(r, g, b, a);

        // Static default implementation
        public static readonly ByteRGBA Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Integer, Integer, Integer, Integer)(ByteRGBA self) => (self.R, self.G, self.B, self.A);
        [MethodImpl(AggressiveInlining)] public static implicit operator ByteRGBA((Integer, Integer, Integer, Integer) value) => new ByteRGBA(value.Item1, value.Item2, value.Item3, value.Item4);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Integer r, out Integer g, out Integer b, out Integer a) { r = R; g = G; b = B; a = A;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(ByteRGBA other) => R.Equals(other.R) && G.Equals(other.G) && B.Equals(other.B) && A.Equals(other.A);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(ByteRGBA other) => !R.Equals(other.R) && G.Equals(other.G) && B.Equals(other.B) && A.Equals(other.A);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is ByteRGBA other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(R, G, B, A);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"R\" = {R}, \"G\" = {G}, \"B\" = {B}, \"A\" = {A} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class ByteRGBAExtensions
    {
    }
}
