// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 11:45:44 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Capsule: ISolid
    {
        // Fields
        [DataMember] public readonly Number Height;
        [DataMember] public readonly Number Radius;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Capsule WithHeight(Number height) => new Capsule(height, Radius);
        [MethodImpl(AggressiveInlining)] public Capsule WithRadius(Number radius) => new Capsule(Height, radius);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Capsule(Number height, Number radius) { Height = height; Radius = radius; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Capsule Create(Number height, Number radius) => new Capsule(height, radius);

        // Static default implementation
        public static readonly Capsule Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number)(Capsule self) => (self.Height, self.Radius);
        [MethodImpl(AggressiveInlining)] public static implicit operator Capsule((Number, Number) value) => new Capsule(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number height, out Number radius) { height = Height; radius = Radius;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Capsule other) => Height.Equals(other.Height) && Radius.Equals(other.Radius);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Capsule other) => !(Height.Equals(other.Height) && Radius.Equals(other.Radius));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Capsule other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Height, Radius);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Height\" = {Height}, \"Radius\" = {Radius} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Point3D Eval(Vector2 t) => throw new NotImplementedException();
        public Boolean ClosedX => throw new NotImplementedException();
        public Boolean ClosedY => throw new NotImplementedException();
    }
    // Extension methods for the type
    public static class CapsuleExtensions
    {
        [MethodImpl(AggressiveInlining)] public static Point3D Eval(this Capsule x, Vector2 t) => x.Eval(t);
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedX(this Capsule x) => x.ClosedX;
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedY(this Capsule x) => x.ClosedY;
    }
}
