// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 10:23:15 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Color: ICoordinate
    {
        // Fields
        [DataMember] public readonly float R;
        [DataMember] public readonly float G;
        [DataMember] public readonly float B;
        [DataMember] public readonly float A;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Color WithR(float r) => new Color(r, G, B, A);
        [MethodImpl(AggressiveInlining)] public Color WithG(float g) => new Color(R, g, B, A);
        [MethodImpl(AggressiveInlining)] public Color WithB(float b) => new Color(R, G, b, A);
        [MethodImpl(AggressiveInlining)] public Color WithA(float a) => new Color(R, G, B, a);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Color(float r, float g, float b, float a) { R = r; G = g; B = b; A = a; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Color Create(float r, float g, float b, float a) => new Color(r, g, b, a);

        // Static default implementation
        public static readonly Color Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (float, float, float, float)(Color self) => (self.R, self.G, self.B, self.A);
        [MethodImpl(AggressiveInlining)] public static implicit operator Color((float, float, float, float) value) => new Color(value.Item1, value.Item2, value.Item3, value.Item4);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out float r, out float g, out float b, out float a) { r = R; g = G; b = B; a = A;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Color other) => R.Equals(other.R) && G.Equals(other.G) && B.Equals(other.B) && A.Equals(other.A);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Color other) => !(R.Equals(other.R) && G.Equals(other.G) && B.Equals(other.B) && A.Equals(other.A));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Color other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(R, G, B, A);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"R\" = {R}, \"G\" = {G}, \"B\" = {B}, \"A\" = {A} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class ColorExtensions
    {
    }
}
