// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 2:43:27 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct ColorHSL: ICoordinate
    {
        // Fields
        [DataMember] public readonly Angle Hue;
        [DataMember] public readonly float Saturation;
        [DataMember] public readonly float Luminance;

        // With functions 
        [MethodImpl(AggressiveInlining)] public ColorHSL WithHue(Angle hue) => new ColorHSL(hue, Saturation, Luminance);
        [MethodImpl(AggressiveInlining)] public ColorHSL WithSaturation(float saturation) => new ColorHSL(Hue, saturation, Luminance);
        [MethodImpl(AggressiveInlining)] public ColorHSL WithLuminance(float luminance) => new ColorHSL(Hue, Saturation, luminance);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public ColorHSL(Angle hue, float saturation, float luminance) { Hue = hue; Saturation = saturation; Luminance = luminance; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static ColorHSL Create(Angle hue, float saturation, float luminance) => new ColorHSL(hue, saturation, luminance);

        // Static default implementation
        public static readonly ColorHSL Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Angle, float, float)(ColorHSL self) => (self.Hue, self.Saturation, self.Luminance);
        [MethodImpl(AggressiveInlining)] public static implicit operator ColorHSL((Angle, float, float) value) => new ColorHSL(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Angle hue, out float saturation, out float luminance) { hue = Hue; saturation = Saturation; luminance = Luminance;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(ColorHSL other) => Hue.Equals(other.Hue) && Saturation.Equals(other.Saturation) && Luminance.Equals(other.Luminance);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(ColorHSL other) => !Hue.Equals(other.Hue) && Saturation.Equals(other.Saturation) && Luminance.Equals(other.Luminance);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is ColorHSL other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Hue, Saturation, Luminance);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Hue\" = {Hue}, \"Saturation\" = {Saturation}, \"Luminance\" = {Luminance} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class ColorHSLExtensions
    {
    }
}
