// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 2:43:27 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct ColorYCbCr: ICoordinate
    {
        // Fields
        [DataMember] public readonly float Y;
        [DataMember] public readonly float Cb;
        [DataMember] public readonly float Cr;

        // With functions 
        [MethodImpl(AggressiveInlining)] public ColorYCbCr WithY(float y) => new ColorYCbCr(y, Cb, Cr);
        [MethodImpl(AggressiveInlining)] public ColorYCbCr WithCb(float cb) => new ColorYCbCr(Y, cb, Cr);
        [MethodImpl(AggressiveInlining)] public ColorYCbCr WithCr(float cr) => new ColorYCbCr(Y, Cb, cr);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public ColorYCbCr(float y, float cb, float cr) { Y = y; Cb = cb; Cr = cr; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static ColorYCbCr Create(float y, float cb, float cr) => new ColorYCbCr(y, cb, cr);

        // Static default implementation
        public static readonly ColorYCbCr Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (float, float, float)(ColorYCbCr self) => (self.Y, self.Cb, self.Cr);
        [MethodImpl(AggressiveInlining)] public static implicit operator ColorYCbCr((float, float, float) value) => new ColorYCbCr(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out float y, out float cb, out float cr) { y = Y; cb = Cb; cr = Cr;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(ColorYCbCr other) => Y.Equals(other.Y) && Cb.Equals(other.Cb) && Cr.Equals(other.Cr);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(ColorYCbCr other) => !Y.Equals(other.Y) && Cb.Equals(other.Cb) && Cr.Equals(other.Cr);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is ColorYCbCr other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Y, Cb, Cr);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Y\" = {Y}, \"Cb\" = {Cb}, \"Cr\" = {Cr} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class ColorYCbCrExtensions
    {
    }
}
