// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 10:23:16 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Cone: ISolid
    {
        // Fields
        [DataMember] public readonly float Height;
        [DataMember] public readonly float Radius;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Cone WithHeight(float height) => new Cone(height, Radius);
        [MethodImpl(AggressiveInlining)] public Cone WithRadius(float radius) => new Cone(Height, radius);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Cone(float height, float radius) { Height = height; Radius = radius; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Cone Create(float height, float radius) => new Cone(height, radius);

        // Static default implementation
        public static readonly Cone Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (float, float)(Cone self) => (self.Height, self.Radius);
        [MethodImpl(AggressiveInlining)] public static implicit operator Cone((float, float) value) => new Cone(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out float height, out float radius) { height = Height; radius = Radius;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Cone other) => Height.Equals(other.Height) && Radius.Equals(other.Radius);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Cone other) => !(Height.Equals(other.Height) && Radius.Equals(other.Radius));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Cone other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Height, Radius);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Height\" = {Height}, \"Radius\" = {Radius} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public Point3D Eval(Vector2 uv){
            var p = ((float)uv.X).Turns().UnitCircle().Multiply(((Number)(((float)this.Radius).Multiply(((float)(1f.Subtract(((float)(((float)uv.Y))))))))));
            return (((float)p.X), ((float)p.Y), ((float)uv.Y).Subtract(((float)(0.5f))).Multiply(((float)(((float)this.Height)))));
        }

        public Boolean ClosedX { [MethodImpl(AggressiveInlining)] get  => true; } 
        public Boolean ClosedY { [MethodImpl(AggressiveInlining)] get  => false; } 

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class ConeExtensions
    {
    }
}
