// Autogenerated file: DO NOT EDIT
// Created on 2026-07-07 10:58:04 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct ConeSegment: ISolid
    {
        // Fields
        [DataMember] public readonly Number Height;
        [DataMember] public readonly Number Radius1;
        [DataMember] public readonly Number Radius2;

        // With functions 
        [MethodImpl(AggressiveInlining)] public ConeSegment WithHeight(Number height) => new ConeSegment(height, Radius1, Radius2);
        [MethodImpl(AggressiveInlining)] public ConeSegment WithRadius1(Number radius1) => new ConeSegment(Height, radius1, Radius2);
        [MethodImpl(AggressiveInlining)] public ConeSegment WithRadius2(Number radius2) => new ConeSegment(Height, Radius1, radius2);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public ConeSegment(Number height, Number radius1, Number radius2) { Height = height; Radius1 = radius1; Radius2 = radius2; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static ConeSegment Create(Number height, Number radius1, Number radius2) => new ConeSegment(height, radius1, radius2);

        // Static default implementation
        public static readonly ConeSegment Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number, Number)(ConeSegment self) => (self.Height, self.Radius1, self.Radius2);
        [MethodImpl(AggressiveInlining)] public static implicit operator ConeSegment((Number, Number, Number) value) => new ConeSegment(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number height, out Number radius1, out Number radius2) { height = Height; radius1 = Radius1; radius2 = Radius2;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(ConeSegment other) => Height.Equals(other.Height) && Radius1.Equals(other.Radius1) && Radius2.Equals(other.Radius2);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(ConeSegment other) => !Height.Equals(other.Height) && Radius1.Equals(other.Radius1) && Radius2.Equals(other.Radius2);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is ConeSegment other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Height, Radius1, Radius2);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Height\" = {Height}, \"Radius1\" = {Radius1}, \"Radius2\" = {Radius2} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Point3D Eval(Vector2 t) => throw new NotImplementedException();
public Boolean ClosedX => throw new NotImplementedException();
public Boolean ClosedY => throw new NotImplementedException();
}
    // Extension methods for the type
    public static class ConeSegmentExtensions
    {
        [MethodImpl(AggressiveInlining)] public static Point3D Eval(this ConeSegment x, Vector2 t) => x.Eval(t);
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedX(this ConeSegment x) => x.ClosedX;
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedY(this ConeSegment x) => x.ClosedY;
    }
}
