// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 10:23:16 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Cylinder: ISurface
    {
        // Fields
        [DataMember] public readonly float Height;
        [DataMember] public readonly float Radius;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Cylinder WithHeight(float height) => new Cylinder(height, Radius);
        [MethodImpl(AggressiveInlining)] public Cylinder WithRadius(float radius) => new Cylinder(Height, radius);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Cylinder(float height, float radius) { Height = height; Radius = radius; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Cylinder Create(float height, float radius) => new Cylinder(height, radius);

        // Static default implementation
        public static readonly Cylinder Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (float, float)(Cylinder self) => (self.Height, self.Radius);
        [MethodImpl(AggressiveInlining)] public static implicit operator Cylinder((float, float) value) => new Cylinder(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out float height, out float radius) { height = Height; radius = Radius;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Cylinder other) => Height.Equals(other.Height) && Radius.Equals(other.Radius);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Cylinder other) => !(Height.Equals(other.Height) && Radius.Equals(other.Radius));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Cylinder other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Height, Radius);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Height\" = {Height}, \"Radius\" = {Radius} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class CylinderExtensions
    {
    }
}
