// Autogenerated file: DO NOT EDIT
// Created on 2026-07-07 10:58:04 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Ellipsoid: ISolid
    {
        // Fields
        [DataMember] public readonly Vector3 Radii;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Ellipsoid WithRadii(Vector3 radii) => new Ellipsoid(radii);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Ellipsoid(Vector3 radii) { Radii = radii; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Ellipsoid Create(Vector3 radii) => new Ellipsoid(radii);

        // Static default implementation
        public static readonly Ellipsoid Default = default;

        // Implicit converters to/from single field
        [MethodImpl(AggressiveInlining)] public static implicit operator Vector3(Ellipsoid self) => self.Radii;
        [MethodImpl(AggressiveInlining)] public static implicit operator Ellipsoid(Vector3 value) => new Ellipsoid(value);

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Ellipsoid other) => Radii.Equals(other.Radii);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Ellipsoid other) => !Radii.Equals(other.Radii);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Ellipsoid other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Radii);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Radii\" = {Radii} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Point3D Eval(Vector2 t) => throw new NotImplementedException();
public Boolean ClosedX => throw new NotImplementedException();
public Boolean ClosedY => throw new NotImplementedException();
}
    // Extension methods for the type
    public static class EllipsoidExtensions
    {
        [MethodImpl(AggressiveInlining)] public static Point3D Eval(this Ellipsoid x, Vector2 t) => x.Eval(t);
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedX(this Ellipsoid x) => x.ClosedX;
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedY(this Ellipsoid x) => x.ClosedY;
    }
}
