// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Epicycloid: IAngularCurve2D, IOpenShape
    {
        // Fields
        [DataMember] public readonly Number Radius1;
        [DataMember] public readonly Number Radius2;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Epicycloid WithRadius1(Number radius1) => new Epicycloid(radius1, Radius2);
        [MethodImpl(AggressiveInlining)] public Epicycloid WithRadius2(Number radius2) => new Epicycloid(Radius1, radius2);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Epicycloid(Number radius1, Number radius2) { Radius1 = radius1; Radius2 = radius2; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Epicycloid Create(Number radius1, Number radius2) => new Epicycloid(radius1, radius2);

        // Static default implementation
        public static readonly Epicycloid Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number)(Epicycloid self) => (self.Radius1, self.Radius2);
        [MethodImpl(AggressiveInlining)] public static implicit operator Epicycloid((Number, Number) value) => new Epicycloid(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number radius1, out Number radius2) { radius1 = Radius1; radius2 = Radius2;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Epicycloid other) => Radius1.Equals(other.Radius1) && Radius2.Equals(other.Radius2);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Epicycloid other) => !Radius1.Equals(other.Radius1) && Radius2.Equals(other.Radius2);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Epicycloid other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Radius1, Radius2);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Radius1\" = {Radius1}, \"Radius2\" = {Radius2} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public Point2D Eval(Angle t) => t.Epicycloid(this.Radius1, this.Radius2);
        [MethodImpl(AggressiveInlining)] public Point2D Eval(Number t) => this.Eval(t.Turns());
        public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class EpicycloidExtensions
    {
    }
}
