// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 2:43:27 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct GeoCoordinateWithAltitude: ICoordinate
    {
        // Fields
        [DataMember] public readonly GeoCoordinate ICoordinate;
        [DataMember] public readonly float Altitude;

        // With functions 
        [MethodImpl(AggressiveInlining)] public GeoCoordinateWithAltitude WithICoordinate(GeoCoordinate iCoordinate) => new GeoCoordinateWithAltitude(iCoordinate, Altitude);
        [MethodImpl(AggressiveInlining)] public GeoCoordinateWithAltitude WithAltitude(float altitude) => new GeoCoordinateWithAltitude(ICoordinate, altitude);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public GeoCoordinateWithAltitude(GeoCoordinate iCoordinate, float altitude) { ICoordinate = iCoordinate; Altitude = altitude; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static GeoCoordinateWithAltitude Create(GeoCoordinate iCoordinate, float altitude) => new GeoCoordinateWithAltitude(iCoordinate, altitude);

        // Static default implementation
        public static readonly GeoCoordinateWithAltitude Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (GeoCoordinate, float)(GeoCoordinateWithAltitude self) => (self.ICoordinate, self.Altitude);
        [MethodImpl(AggressiveInlining)] public static implicit operator GeoCoordinateWithAltitude((GeoCoordinate, float) value) => new GeoCoordinateWithAltitude(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out GeoCoordinate iCoordinate, out float altitude) { iCoordinate = ICoordinate; altitude = Altitude;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(GeoCoordinateWithAltitude other) => ICoordinate.Equals(other.ICoordinate) && Altitude.Equals(other.Altitude);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(GeoCoordinateWithAltitude other) => !ICoordinate.Equals(other.ICoordinate) && Altitude.Equals(other.Altitude);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is GeoCoordinateWithAltitude other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(ICoordinate, Altitude);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"ICoordinate\" = {ICoordinate}, \"Altitude\" = {Altitude} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class GeoCoordinateWithAltitudeExtensions
    {
    }
}
