// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Identity2D: IRigidTransform2D
    {
        // Fields

        // With functions 

        // Regular Constructor

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Identity2D Create() => new Identity2D();

        // Static default implementation
        public static readonly Identity2D Default = default;

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Identity2D;
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Identity2D other) => true;
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Identity2D other) => false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(Identity2D a, Identity2D b) => true;
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(Identity2D a, Identity2D b) => false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes();
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{  }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
        public Matrix3x2 Matrix => throw new NotImplementedException();
    }
    // Extension methods for the type
    public static class Identity2DExtensions
    {
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Matrix(this Identity2D x) => x.Matrix;
    }
}
