// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Integer4: IValue, IArrayLike<Integer4, Integer>
    {
        // Fields
        [DataMember] public readonly Integer A;
        [DataMember] public readonly Integer B;
        [DataMember] public readonly Integer C;
        [DataMember] public readonly Integer D;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Integer4 WithA(Integer a) => new Integer4(a, B, C, D);
        [MethodImpl(AggressiveInlining)] public Integer4 WithB(Integer b) => new Integer4(A, b, C, D);
        [MethodImpl(AggressiveInlining)] public Integer4 WithC(Integer c) => new Integer4(A, B, c, D);
        [MethodImpl(AggressiveInlining)] public Integer4 WithD(Integer d) => new Integer4(A, B, C, d);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Integer4(Integer a, Integer b, Integer c, Integer d) { A = a; B = b; C = c; D = d; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Integer4 Create(Integer a, Integer b, Integer c, Integer d) => new Integer4(a, b, c, d);

        // Static default implementation
        public static readonly Integer4 Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Integer, Integer, Integer, Integer)(Integer4 self) => (self.A, self.B, self.C, self.D);
        [MethodImpl(AggressiveInlining)] public static implicit operator Integer4((Integer, Integer, Integer, Integer) value) => new Integer4(value.Item1, value.Item2, value.Item3, value.Item4);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Integer a, out Integer b, out Integer c, out Integer d) { a = A; b = B; c = C; d = D;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Integer4 other) => A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C) && D.Equals(other.D);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Integer4 other) => !A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C) && D.Equals(other.D);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Integer4 other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(A, B, C, D);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"A\" = {A}, \"B\" = {B}, \"C\" = {C}, \"D\" = {D} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public Integer NumComponents { [MethodImpl(AggressiveInlining)] get => 4; }
        public IReadOnlyList<Integer> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Integer>(A, B, C, D); }
        [MethodImpl(AggressiveInlining)] public static Integer4 CreateFromComponents(IReadOnlyList<Integer> numbers) => new Integer4(numbers[0], numbers[1], numbers[2], numbers[3]);

        [MethodImpl(AggressiveInlining)] public static Integer4 CreateFromComponent(Integer x) => new Integer4(x, x, x, x);

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public Integer At(Integer n) => this.Components[n];
        public Integer this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class Integer4Extensions
    {
    }
}
