// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Limacon: IPolarCurve, IOpenShape
    {
        // Fields
        [DataMember] public readonly Number A;
        [DataMember] public readonly Number B;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Limacon WithA(Number a) => new Limacon(a, B);
        [MethodImpl(AggressiveInlining)] public Limacon WithB(Number b) => new Limacon(A, b);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Limacon(Number a, Number b) { A = a; B = b; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Limacon Create(Number a, Number b) => new Limacon(a, b);

        // Static default implementation
        public static readonly Limacon Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number)(Limacon self) => (self.A, self.B);
        [MethodImpl(AggressiveInlining)] public static implicit operator Limacon((Number, Number) value) => new Limacon(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number a, out Number b) { a = A; b = B;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Limacon other) => A.Equals(other.A) && B.Equals(other.B);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Limacon other) => !A.Equals(other.A) && B.Equals(other.B);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Limacon other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(A, B);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"A\" = {A}, \"B\" = {B} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public Number GetRadius(Angle t) => t.Limacon(this.A, this.B);
        [MethodImpl(AggressiveInlining)] public Point2D Eval(Angle t) => this.EvalPolar(t);
        [MethodImpl(AggressiveInlining)] public Point2D Eval(Number t) => this.Eval(t.Turns());
        public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class LimaconExtensions
    {
    }
}
