// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 11:45:44 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct LogPolarCoordinate: ICoordinate
    {
        // Fields
        [DataMember] public readonly Number Rho;
        [DataMember] public readonly Angle Azimuth;

        // With functions 
        [MethodImpl(AggressiveInlining)] public LogPolarCoordinate WithRho(Number rho) => new LogPolarCoordinate(rho, Azimuth);
        [MethodImpl(AggressiveInlining)] public LogPolarCoordinate WithAzimuth(Angle azimuth) => new LogPolarCoordinate(Rho, azimuth);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public LogPolarCoordinate(Number rho, Angle azimuth) { Rho = rho; Azimuth = azimuth; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static LogPolarCoordinate Create(Number rho, Angle azimuth) => new LogPolarCoordinate(rho, azimuth);

        // Static default implementation
        public static readonly LogPolarCoordinate Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Angle)(LogPolarCoordinate self) => (self.Rho, self.Azimuth);
        [MethodImpl(AggressiveInlining)] public static implicit operator LogPolarCoordinate((Number, Angle) value) => new LogPolarCoordinate(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number rho, out Angle azimuth) { rho = Rho; azimuth = Azimuth;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(LogPolarCoordinate other) => Rho.Equals(other.Rho) && Azimuth.Equals(other.Azimuth);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(LogPolarCoordinate other) => !(Rho.Equals(other.Rho) && Azimuth.Equals(other.Azimuth));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is LogPolarCoordinate other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Rho, Azimuth);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Rho\" = {Rho}, \"Azimuth\" = {Azimuth} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class LogPolarCoordinateExtensions
    {
    }
}
