// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Matrix3x2: IValue, IArrayLike<Matrix3x2, Number>
    {
        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Create(Vector2 row1, Vector2 row2, Vector2 row3) => new Matrix3x2(row1, row2, row3);

        // Static default implementation
        public static readonly Matrix3x2 Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Vector2, Vector2, Vector2)(Matrix3x2 self) => (self.Row1, self.Row2, self.Row3);
        [MethodImpl(AggressiveInlining)] public static implicit operator Matrix3x2((Vector2, Vector2, Vector2) value) => new Matrix3x2(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Vector2 row1, out Vector2 row2, out Vector2 row3) { row1 = Row1; row2 = Row2; row3 = Row3;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Matrix3x2 other) => Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Matrix3x2 other) => !Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Matrix3x2 other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(Matrix3x2 a, Matrix3x2 b) => a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(Matrix3x2 a, Matrix3x2 b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Value.GetHashCode();
        [MethodImpl(AggressiveInlining)] public override string ToString() => Value.ToString();

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public Integer NumComponents { [MethodImpl(AggressiveInlining)] get => 6; }
        public IReadOnlyList<Number> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Number>(M11, M12, M21, M22, M31, M32); }
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 CreateFromComponents(IReadOnlyList<Number> numbers) => new Matrix3x2(numbers[0], numbers[1], numbers[2], numbers[3], numbers[4], numbers[5]);

        [MethodImpl(AggressiveInlining)] public static Matrix3x2 CreateFromComponent(Number x) => new Matrix3x2(x, x, x, x, x, x);

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public Matrix3x2 Add(Matrix3x2 value2) => this + value2;
        [MethodImpl(AggressiveInlining)] public Matrix3x2 Subtract(Matrix3x2 value2) => this - value2;
        [MethodImpl(AggressiveInlining)] public Matrix3x2 Multiply(Matrix3x2 value2) => this * value2;
        [MethodImpl(AggressiveInlining)] public Matrix3x2 Multiply(Number scalar) => this * scalar;
        [MethodImpl(AggressiveInlining)] public Matrix3x2 Divide(Number scalar) => this / scalar;
        [MethodImpl(AggressiveInlining)] public Number At(Integer n) => this.Components[n];
        public Number this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class Matrix3x2Extensions
    {
        [MethodImpl(AggressiveInlining)] public static Vector2 Row1(this Matrix3x2 self) => self.Row1;
        [MethodImpl(AggressiveInlining)] public static Vector2 Row1(this System.Numerics.Matrix3x2 self) => ((Matrix3x2)self).Row1;
        [MethodImpl(AggressiveInlining)] public static Vector2 Row2(this Matrix3x2 self) => self.Row2;
        [MethodImpl(AggressiveInlining)] public static Vector2 Row2(this System.Numerics.Matrix3x2 self) => ((Matrix3x2)self).Row2;
        [MethodImpl(AggressiveInlining)] public static Vector2 Row3(this Matrix3x2 self) => self.Row3;
        [MethodImpl(AggressiveInlining)] public static Vector2 Row3(this System.Numerics.Matrix3x2 self) => ((Matrix3x2)self).Row3;
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 WithRow1(this Matrix3x2 self, Vector2 row) => self.WithRow1(row);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 WithRow1(this System.Numerics.Matrix3x2 self, Vector2 row) => ((Matrix3x2)self).WithRow1(row);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 WithRow2(this Matrix3x2 self, Vector2 row) => self.WithRow2(row);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 WithRow2(this System.Numerics.Matrix3x2 self, Vector2 row) => ((Matrix3x2)self).WithRow2(row);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 WithRow3(this Matrix3x2 self, Vector2 row) => self.WithRow3(row);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 WithRow3(this System.Numerics.Matrix3x2 self, Vector2 row) => ((Matrix3x2)self).WithRow3(row);
        [MethodImpl(AggressiveInlining)] public static Tuple2<Matrix3x2, Boolean> Invert(this Matrix3x2 self) => self.Invert;
        [MethodImpl(AggressiveInlining)] public static Tuple2<Matrix3x2, Boolean> Invert(this System.Numerics.Matrix3x2 self) => ((Matrix3x2)self).Invert;
        [MethodImpl(AggressiveInlining)] public static Number Determinant(this Matrix3x2 self) => self.Determinant;
        [MethodImpl(AggressiveInlining)] public static Number Determinant(this System.Numerics.Matrix3x2 self) => ((Matrix3x2)self).Determinant;
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Add(this Matrix3x2 value1, Matrix3x2 value2) => value1.Add(value2);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Add(this System.Numerics.Matrix3x2 value1, Matrix3x2 value2) => ((Matrix3x2)value1).Add(value2);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Subtract(this Matrix3x2 value1, Matrix3x2 value2) => value1.Subtract(value2);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Subtract(this System.Numerics.Matrix3x2 value1, Matrix3x2 value2) => ((Matrix3x2)value1).Subtract(value2);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Multiply(this Matrix3x2 value1, Matrix3x2 value2) => value1.Multiply(value2);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Multiply(this System.Numerics.Matrix3x2 value1, Matrix3x2 value2) => ((Matrix3x2)value1).Multiply(value2);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Multiply(this Matrix3x2 value1, Number scalar) => value1.Multiply(scalar);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Multiply(this System.Numerics.Matrix3x2 value1, Number scalar) => ((Matrix3x2)value1).Multiply(scalar);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Divide(this Matrix3x2 value1, Number scalar) => value1.Divide(scalar);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Divide(this System.Numerics.Matrix3x2 value1, Number scalar) => ((Matrix3x2)value1).Divide(scalar);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Lerp(this Matrix3x2 self, Matrix3x2 matrix2, Number amount) => self.Lerp(matrix2, amount);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Lerp(this System.Numerics.Matrix3x2 self, Matrix3x2 matrix2, Number amount) => ((Matrix3x2)self).Lerp(matrix2, amount);
        [MethodImpl(AggressiveInlining)] public static Number At(this System.Numerics.Matrix3x2 xs, Integer n) => ((Matrix3x2)xs).At(n);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Reverse(this System.Numerics.Matrix3x2 xs) => ((Matrix3x2)xs).Reverse();
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 MapComponents(this System.Numerics.Matrix3x2 x, System.Func<Number, Number> f) => ((Matrix3x2)x).MapComponents(f);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 ZipComponents(this System.Numerics.Matrix3x2 a, Matrix3x2 b, System.Func<Number, Number, Number> f) => ((Matrix3x2)a).ZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 ZipComponents(this System.Numerics.Matrix3x2 a, Matrix3x2 b, Matrix3x2 c, System.Func<Number, Number, Number, Number> f) => ((Matrix3x2)a).ZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllZipComponents(this System.Numerics.Matrix3x2 a, Matrix3x2 b, System.Func<Number, Number, Boolean> f) => ((Matrix3x2)a).AllZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllZipComponents(this System.Numerics.Matrix3x2 a, Matrix3x2 b, Matrix3x2 c, System.Func<Number, Number, Number, Boolean> f) => ((Matrix3x2)a).AllZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyZipComponents(this System.Numerics.Matrix3x2 a, Matrix3x2 b, System.Func<Number, Number, Boolean> f) => ((Matrix3x2)a).AnyZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyZipComponents(this System.Numerics.Matrix3x2 a, Matrix3x2 b, Matrix3x2 c, System.Func<Number, Number, Number, Boolean> f) => ((Matrix3x2)a).AnyZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllComponents(this System.Numerics.Matrix3x2 x, System.Func<Number, Boolean> predicate) => ((Matrix3x2)x).AllComponents(predicate);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyComponent(this System.Numerics.Matrix3x2 x, System.Func<Number, Boolean> predicate) => ((Matrix3x2)x).AnyComponent(predicate);
    }
}
