// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct NPrism: ISolid
    {
        // Fields
        [DataMember] public readonly Number Height;
        [DataMember] public readonly Number Radius;
        [DataMember] public readonly Integer NumSides;

        // With functions 
        [MethodImpl(AggressiveInlining)] public NPrism WithHeight(Number height) => new NPrism(height, Radius, NumSides);
        [MethodImpl(AggressiveInlining)] public NPrism WithRadius(Number radius) => new NPrism(Height, radius, NumSides);
        [MethodImpl(AggressiveInlining)] public NPrism WithNumSides(Integer numSides) => new NPrism(Height, Radius, numSides);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public NPrism(Number height, Number radius, Integer numSides) { Height = height; Radius = radius; NumSides = numSides; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static NPrism Create(Number height, Number radius, Integer numSides) => new NPrism(height, radius, numSides);

        // Static default implementation
        public static readonly NPrism Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number, Integer)(NPrism self) => (self.Height, self.Radius, self.NumSides);
        [MethodImpl(AggressiveInlining)] public static implicit operator NPrism((Number, Number, Integer) value) => new NPrism(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number height, out Number radius, out Integer numSides) { height = Height; radius = Radius; numSides = NumSides;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(NPrism other) => Height.Equals(other.Height) && Radius.Equals(other.Radius) && NumSides.Equals(other.NumSides);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(NPrism other) => !Height.Equals(other.Height) && Radius.Equals(other.Radius) && NumSides.Equals(other.NumSides);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is NPrism other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Height, Radius, NumSides);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Height\" = {Height}, \"Radius\" = {Radius}, \"NumSides\" = {NumSides} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Point3D Eval(Vector2 t) => throw new NotImplementedException();
        public Boolean ClosedX => throw new NotImplementedException();
        public Boolean ClosedY => throw new NotImplementedException();
    }
    // Extension methods for the type
    public static class NPrismExtensions
    {
        [MethodImpl(AggressiveInlining)] public static Point3D Eval(this NPrism x, Vector2 t) => x.Eval(t);
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedX(this NPrism x) => x.ClosedX;
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedY(this NPrism x) => x.ClosedY;
    }
}
