// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 11:45:44 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct NumberInterval: IInterval<Number>
    {
        // Fields
        [DataMember] public readonly Number Start;
        [DataMember] public readonly Number End;

        // With functions 
        [MethodImpl(AggressiveInlining)] public NumberInterval WithStart(Number start) => new NumberInterval(start, End);
        [MethodImpl(AggressiveInlining)] public NumberInterval WithEnd(Number end) => new NumberInterval(Start, end);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public NumberInterval(Number start, Number end) { Start = start; End = end; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static NumberInterval Create(Number start, Number end) => new NumberInterval(start, end);

        // Static default implementation
        public static readonly NumberInterval Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number)(NumberInterval self) => (self.Start, self.End);
        [MethodImpl(AggressiveInlining)] public static implicit operator NumberInterval((Number, Number) value) => new NumberInterval(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number start, out Number end) { start = Start; end = End;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(NumberInterval other) => Start.Equals(other.Start) && End.Equals(other.End);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(NumberInterval other) => !(Start.Equals(other.Start) && End.Equals(other.End));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is NumberInterval other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Start, End);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Start\" = {Start}, \"End\" = {End} }}";

        // Explicit implementation of interfaces by forwarding properties to fields
        Number IInterval<Number>.Start { [MethodImpl(AggressiveInlining)] get => Start; }
        Number IInterval<Number>.End { [MethodImpl(AggressiveInlining)] get => End; }

        // Implemented interface functions
        public Number Size { [MethodImpl(AggressiveInlining)] get  => this.End.Subtract(this.Start); } 
        public Number Center { [MethodImpl(AggressiveInlining)] get  => this.Lerp(((Number)0.5)); } 

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class NumberIntervalExtensions
    {
    }
}
