// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 11:45:44 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct QuadraticBezier3D: IOpenShape
    {
        // Fields
        [DataMember] public readonly Point3D A;
        [DataMember] public readonly Point3D B;
        [DataMember] public readonly Point3D C;

        // With functions 
        [MethodImpl(AggressiveInlining)] public QuadraticBezier3D WithA(Point3D a) => new QuadraticBezier3D(a, B, C);
        [MethodImpl(AggressiveInlining)] public QuadraticBezier3D WithB(Point3D b) => new QuadraticBezier3D(A, b, C);
        [MethodImpl(AggressiveInlining)] public QuadraticBezier3D WithC(Point3D c) => new QuadraticBezier3D(A, B, c);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public QuadraticBezier3D(Point3D a, Point3D b, Point3D c) { A = a; B = b; C = c; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static QuadraticBezier3D Create(Point3D a, Point3D b, Point3D c) => new QuadraticBezier3D(a, b, c);

        // Static default implementation
        public static readonly QuadraticBezier3D Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Point3D, Point3D, Point3D)(QuadraticBezier3D self) => (self.A, self.B, self.C);
        [MethodImpl(AggressiveInlining)] public static implicit operator QuadraticBezier3D((Point3D, Point3D, Point3D) value) => new QuadraticBezier3D(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Point3D a, out Point3D b, out Point3D c) { a = A; b = B; c = C;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(QuadraticBezier3D other) => A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(QuadraticBezier3D other) => !(A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is QuadraticBezier3D other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(A, B, C);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"A\" = {A}, \"B\" = {B}, \"C\" = {C} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class QuadraticBezier3DExtensions
    {
    }
}
