// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 11:45:44 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Sphere: ISolid
    {
        // Fields
        [DataMember] public readonly Number Radius;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Sphere WithRadius(Number radius) => new Sphere(radius);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Sphere(Number radius) { Radius = radius; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Sphere Create(Number radius) => new Sphere(radius);

        // Static default implementation
        public static readonly Sphere Default = default;

        // Implicit converters to/from single field
        [MethodImpl(AggressiveInlining)] public static implicit operator Number(Sphere self) => self.Radius;
        [MethodImpl(AggressiveInlining)] public static implicit operator Sphere(Number value) => new Sphere(value);
        [MethodImpl(AggressiveInlining)] public static implicit operator Sphere(Integer value) => new Sphere(value);
        [MethodImpl(AggressiveInlining)] public static implicit operator Sphere(int value) => new Integer(value);
        [MethodImpl(AggressiveInlining)] public static implicit operator Sphere(float value) => new Number(value);
        [MethodImpl(AggressiveInlining)] public static implicit operator float(Sphere value) => value.Radius;

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Sphere other) => Radius.Equals(other.Radius);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Sphere other) => !(Radius.Equals(other.Radius));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Sphere other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Radius);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Radius\" = {Radius} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Point3D Eval(Vector2 t) => throw new NotImplementedException();
        public Boolean ClosedX => throw new NotImplementedException();
        public Boolean ClosedY => throw new NotImplementedException();
    }
    // Extension methods for the type
    public static class SphereExtensions
    {
        [MethodImpl(AggressiveInlining)] public static Point3D Eval(this Sphere x, Vector2 t) => x.Eval(t);
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedX(this Sphere x) => x.ClosedX;
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedY(this Sphere x) => x.ClosedY;
    }
}
