// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 2:43:27 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Torus: ISolid
    {
        // Fields
        [DataMember] public readonly float MajorRadius;
        [DataMember] public readonly float MinorRadius;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Torus WithMajorRadius(float majorRadius) => new Torus(majorRadius, MinorRadius);
        [MethodImpl(AggressiveInlining)] public Torus WithMinorRadius(float minorRadius) => new Torus(MajorRadius, minorRadius);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Torus(float majorRadius, float minorRadius) { MajorRadius = majorRadius; MinorRadius = minorRadius; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Torus Create(float majorRadius, float minorRadius) => new Torus(majorRadius, minorRadius);

        // Static default implementation
        public static readonly Torus Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (float, float)(Torus self) => (self.MajorRadius, self.MinorRadius);
        [MethodImpl(AggressiveInlining)] public static implicit operator Torus((float, float) value) => new Torus(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out float majorRadius, out float minorRadius) { majorRadius = MajorRadius; minorRadius = MinorRadius;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Torus other) => MajorRadius.Equals(other.MajorRadius) && MinorRadius.Equals(other.MinorRadius);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Torus other) => !MajorRadius.Equals(other.MajorRadius) && MinorRadius.Equals(other.MinorRadius);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Torus other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(MajorRadius, MinorRadius);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"MajorRadius\" = {MajorRadius}, \"MinorRadius\" = {MinorRadius} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Point3D Eval(Vector2 t) => throw new NotImplementedException();
        public Boolean ClosedX => throw new NotImplementedException();
        public Boolean ClosedY => throw new NotImplementedException();
    }
    // Extension methods for the type
    public static class TorusExtensions
    {
        [MethodImpl(AggressiveInlining)] public static Point3D Eval(this Torus x, Vector2 t) => x.Eval(t);
        [MethodImpl(AggressiveInlining)] public static bool ClosedX(this Torus x) => x.ClosedX;
        [MethodImpl(AggressiveInlining)] public static bool ClosedY(this Torus x) => x.ClosedY;
    }
}
