// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 2:43:27 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Triangle2D: IPolygon2D<Triangle2D>, IGeometricPrimitive2D<Triangle2D>, IArrayLike<Triangle2D, Point2D>
    {
        // Fields
        [DataMember] public readonly Point2D A;
        [DataMember] public readonly Point2D B;
        [DataMember] public readonly Point2D C;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Triangle2D WithA(Point2D a) => new Triangle2D(a, B, C);
        [MethodImpl(AggressiveInlining)] public Triangle2D WithB(Point2D b) => new Triangle2D(A, b, C);
        [MethodImpl(AggressiveInlining)] public Triangle2D WithC(Point2D c) => new Triangle2D(A, B, c);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Triangle2D(Point2D a, Point2D b, Point2D c) { A = a; B = b; C = c; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Triangle2D Create(Point2D a, Point2D b, Point2D c) => new Triangle2D(a, b, c);

        // Static default implementation
        public static readonly Triangle2D Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Point2D, Point2D, Point2D)(Triangle2D self) => (self.A, self.B, self.C);
        [MethodImpl(AggressiveInlining)] public static implicit operator Triangle2D((Point2D, Point2D, Point2D) value) => new Triangle2D(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Point2D a, out Point2D b, out Point2D c) { a = A; b = B; c = C;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Triangle2D other) => A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Triangle2D other) => !A.Equals(other.A) && B.Equals(other.B) && C.Equals(other.C);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Triangle2D other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(A, B, C);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"A\" = {A}, \"B\" = {B}, \"C\" = {C} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public int NumComponents { [MethodImpl(AggressiveInlining)] get => 3; }
        public IReadOnlyList<Point2D> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Point2D>(A, B, C); }
        [MethodImpl(AggressiveInlining)] public static Triangle2D CreateFromComponents(IReadOnlyList<Point2D> numbers) => new Triangle2D(numbers[0], numbers[1], numbers[2]);

        [MethodImpl(AggressiveInlining)] public static Triangle2D CreateFromComponent(Point2D x) => new Triangle2D(x, x, x);

        // Implemented interface functions
        public Point2D Center { [MethodImpl(AggressiveInlining)] get  => this.A.Add(this.B.Add(this.C)).Divide(((Number)(3f))); } 
        // AMBIGUOUS FUNCTIONS 3
        /* Geometry_14.Points(t: Triangle2D): IArray<Point2D> [Library]; */
        /* Geometry_14.Points(t: Triangle2D): IArray<Point2D> [Library]; */
        /* Meshes_18.Points(x: Triangle2D): IArray<Point2D> [Library]; */
        public IReadOnlyList<Point2D> Points { [MethodImpl(AggressiveInlining)] get  => this.Components; } 
        public Triangle3D Triangle3D { [MethodImpl(AggressiveInlining)] get  => this.To3D(); } 
        [MethodImpl(AggressiveInlining)]  public static implicit operator Triangle3D(Triangle2D x) => x.Triangle3D;
        public static Triangle2D Unit { [MethodImpl(AggressiveInlining)] get  => ((0.5f.Negative(), 3f.Sqrt().Half().Negative()), (0.5f.Negative(), 3f.Sqrt().Half()), (0f, 1f)); } 
        [MethodImpl(AggressiveInlining)] public Triangle2D Deform(System.Func<Point2D, Point2D> f) => (f.Invoke(this.A), f.Invoke(this.B), f.Invoke(this.C));
        public Boolean Closed { [MethodImpl(AggressiveInlining)] get  => true; } 
        [MethodImpl(AggressiveInlining)] public Point2D At(Integer n) => this.Components[((int)n)];
        public Point2D this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Point2D Eval(Number t) => throw new NotImplementedException();
        [MethodImpl(AggressiveInlining)] public Triangle2D Transform(Transform2D t) => throw new NotImplementedException();
    }
    // Extension methods for the type
    public static class Triangle2DExtensions
    {
        [MethodImpl(AggressiveInlining)] public static Point2D Eval(this Triangle2D x, float t) => x.Eval(t);
        [MethodImpl(AggressiveInlining)] public static Triangle2D Transform(this Triangle2D x, Transform2D t) => x.Transform(t);
    }
}
