// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Tube: ISolid
    {
        // Fields
        [DataMember] public readonly Number Height;
        [DataMember] public readonly Number InnerRadius;
        [DataMember] public readonly Number OuterRadius;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Tube WithHeight(Number height) => new Tube(height, InnerRadius, OuterRadius);
        [MethodImpl(AggressiveInlining)] public Tube WithInnerRadius(Number innerRadius) => new Tube(Height, innerRadius, OuterRadius);
        [MethodImpl(AggressiveInlining)] public Tube WithOuterRadius(Number outerRadius) => new Tube(Height, InnerRadius, outerRadius);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Tube(Number height, Number innerRadius, Number outerRadius) { Height = height; InnerRadius = innerRadius; OuterRadius = outerRadius; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Tube Create(Number height, Number innerRadius, Number outerRadius) => new Tube(height, innerRadius, outerRadius);

        // Static default implementation
        public static readonly Tube Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number, Number)(Tube self) => (self.Height, self.InnerRadius, self.OuterRadius);
        [MethodImpl(AggressiveInlining)] public static implicit operator Tube((Number, Number, Number) value) => new Tube(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number height, out Number innerRadius, out Number outerRadius) { height = Height; innerRadius = InnerRadius; outerRadius = OuterRadius;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Tube other) => Height.Equals(other.Height) && InnerRadius.Equals(other.InnerRadius) && OuterRadius.Equals(other.OuterRadius);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Tube other) => !Height.Equals(other.Height) && InnerRadius.Equals(other.InnerRadius) && OuterRadius.Equals(other.OuterRadius);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Tube other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Height, InnerRadius, OuterRadius);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Height\" = {Height}, \"InnerRadius\" = {InnerRadius}, \"OuterRadius\" = {OuterRadius} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Point3D Eval(Vector2 t) => throw new NotImplementedException();
        public Boolean ClosedX => throw new NotImplementedException();
        public Boolean ClosedY => throw new NotImplementedException();
    }
    // Extension methods for the type
    public static class TubeExtensions
    {
        [MethodImpl(AggressiveInlining)] public static Point3D Eval(this Tube x, Vector2 t) => x.Eval(t);
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedX(this Tube x) => x.ClosedX;
        [MethodImpl(AggressiveInlining)] public static Boolean ClosedY(this Tube x) => x.ClosedY;
    }
}
