// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 10:23:16 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Tube: ISolid
    {
        // Fields
        [DataMember] public readonly float Height;
        [DataMember] public readonly float InnerRadius;
        [DataMember] public readonly float OuterRadius;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Tube WithHeight(float height) => new Tube(height, InnerRadius, OuterRadius);
        [MethodImpl(AggressiveInlining)] public Tube WithInnerRadius(float innerRadius) => new Tube(Height, innerRadius, OuterRadius);
        [MethodImpl(AggressiveInlining)] public Tube WithOuterRadius(float outerRadius) => new Tube(Height, InnerRadius, outerRadius);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Tube(float height, float innerRadius, float outerRadius) { Height = height; InnerRadius = innerRadius; OuterRadius = outerRadius; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Tube Create(float height, float innerRadius, float outerRadius) => new Tube(height, innerRadius, outerRadius);

        // Static default implementation
        public static readonly Tube Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (float, float, float)(Tube self) => (self.Height, self.InnerRadius, self.OuterRadius);
        [MethodImpl(AggressiveInlining)] public static implicit operator Tube((float, float, float) value) => new Tube(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out float height, out float innerRadius, out float outerRadius) { height = Height; innerRadius = InnerRadius; outerRadius = OuterRadius;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Tube other) => Height.Equals(other.Height) && InnerRadius.Equals(other.InnerRadius) && OuterRadius.Equals(other.OuterRadius);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Tube other) => !(Height.Equals(other.Height) && InnerRadius.Equals(other.InnerRadius) && OuterRadius.Equals(other.OuterRadius));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Tube other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Height, InnerRadius, OuterRadius);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Height\" = {Height}, \"InnerRadius\" = {InnerRadius}, \"OuterRadius\" = {OuterRadius} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public Point3D Eval(Vector2 uv){
            var theta = ((float)uv.X).Turns();
            var r = ((float)uv.Y).LessThan(((float)(0.5f))) ? ((float)this.OuterRadius) : ((float)this.InnerRadius);
            var z = ((float)uv.Y).LessThan(((float)(0.5f))) ? ((float)uv.Y).Multiply(((float)(2f))).Subtract(((float)(0.5f))) : 1.5f.Subtract(((float)(((float)uv.Y).Multiply(((float)(2f)))))).Multiply(((float)(((float)this.Height))));
            return (((float)theta.Cos).Multiply(((float)(r))), ((float)theta.Sin).Multiply(((float)(r))), z);
        }

        public Boolean ClosedX { [MethodImpl(AggressiveInlining)] get  => true; } 
        public Boolean ClosedY { [MethodImpl(AggressiveInlining)] get  => false; } 

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class TubeExtensions
    {
    }
}
