// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 2:43:27 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct UniformScale2D: ITransform2D
    {
        // Fields
        [DataMember] public readonly float Amount;

        // With functions 
        [MethodImpl(AggressiveInlining)] public UniformScale2D WithAmount(float amount) => new UniformScale2D(amount);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public UniformScale2D(float amount) { Amount = amount; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static UniformScale2D Create(float amount) => new UniformScale2D(amount);

        // Static default implementation
        public static readonly UniformScale2D Default = default;

        // Implicit converters to/from single field
        [MethodImpl(AggressiveInlining)] public static implicit operator float(UniformScale2D self) => self.Amount;
        [MethodImpl(AggressiveInlining)] public static implicit operator UniformScale2D(float value) => new UniformScale2D(value);
        [MethodImpl(AggressiveInlining)] public static implicit operator UniformScale2D(Integer value) => new UniformScale2D(value);
        [MethodImpl(AggressiveInlining)] public static implicit operator UniformScale2D(int value) => new UniformScale2D(value);
        [MethodImpl(AggressiveInlining)] public static implicit operator UniformScale2D(Number value) => new UniformScale2D(value);

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(UniformScale2D other) => Amount.Equals(other.Amount);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(UniformScale2D other) => !Amount.Equals(other.Amount);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is UniformScale2D other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Amount);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Amount\" = {Amount} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions

        // Unimplemented interface functions
        public Matrix3x2 Matrix => throw new NotImplementedException();
    }
    // Extension methods for the type
    public static class UniformScale2DExtensions
    {
        [MethodImpl(AggressiveInlining)] public static Matrix3x2 Matrix(this UniformScale2D x) => x.Matrix;
    }
}
