// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Vector3: IVector<Vector3>
    {
        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Vector3 Create(Number x, Number y, Number z) => new Vector3(x, y, z);

        // Static default implementation
        public static readonly Vector3 Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number, Number)(Vector3 self) => (self.X, self.Y, self.Z);
        [MethodImpl(AggressiveInlining)] public static implicit operator Vector3((Number, Number, Number) value) => new Vector3(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number x, out Number y, out Number z) { x = X; y = Y; z = Z;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Vector3 other) => Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Vector3 other) => !Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Vector3 other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(Vector3 a, Vector3 b) => a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(Vector3 a, Vector3 b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Value.GetHashCode();
        [MethodImpl(AggressiveInlining)] public override string ToString() => Value.ToString();

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public Integer NumComponents { [MethodImpl(AggressiveInlining)] get => 3; }
        public IReadOnlyList<Number> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Number>(X, Y, Z); }
        [MethodImpl(AggressiveInlining)] public static Vector3 CreateFromComponents(IReadOnlyList<Number> numbers) => new Vector3(numbers[0], numbers[1], numbers[2]);

        [MethodImpl(AggressiveInlining)] public static Vector3 CreateFromComponent(Number x) => new Vector3(x, x, x);

        // Implemented interface functions
        public Point3D Point3D { [MethodImpl(AggressiveInlining)] get  => (this.X, this.Y, this.Z); } 
        [MethodImpl(AggressiveInlining)]  public static implicit operator Point3D(Vector3 x) => x.Point3D;
        public Ray3D Ray3D { [MethodImpl(AggressiveInlining)] get  => (Constants.Origin3D, this); } 
        [MethodImpl(AggressiveInlining)]  public static implicit operator Ray3D(Vector3 v) => v.Ray3D;
        [MethodImpl(AggressiveInlining)] public Vector3 Add(Vector3 right) => this + right;
        [MethodImpl(AggressiveInlining)] public Vector3 Subtract(Vector3 right) => this - right;
        [MethodImpl(AggressiveInlining)] public Vector3 Multiply(Vector3 right) => this * right;
        [MethodImpl(AggressiveInlining)] public Vector3 Multiply(Number scalar) => this * scalar;
        [MethodImpl(AggressiveInlining)] public Vector3 Divide(Vector3 right) => this / right;
        [MethodImpl(AggressiveInlining)] public Vector3 Divide(Number scalar) => this / scalar;
        public Vector3 Negative { [MethodImpl(AggressiveInlining)] get => -this; }
        public Vector4 Vector4 { [MethodImpl(AggressiveInlining)] get  => this.ToVector4(((Number)0)); } 
        [MethodImpl(AggressiveInlining)]  public static implicit operator Vector4(Vector3 v) => v.Vector4;
        public static Vector3 UnitX { [MethodImpl(AggressiveInlining)] get  => (((Number)1), ((Number)0), ((Number)0)); } 
        public static Vector3 UnitY { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)1), ((Number)0)); } 
        public static Vector3 UnitZ { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)0), ((Number)1)); } 
        public static Vector3 Zero { [MethodImpl(AggressiveInlining)] get  => Vector3.CreateFromComponent(((Number)0)); } 
        public static Vector3 One { [MethodImpl(AggressiveInlining)] get  => Vector3.CreateFromComponent(((Number)1)); } 
        public static Vector3 MinValue { [MethodImpl(AggressiveInlining)] get  => Vector3.CreateFromComponent(Ara3D.Geometry.Number.MinValue); } 
        public static Vector3 MaxValue { [MethodImpl(AggressiveInlining)] get  => Vector3.CreateFromComponent(Ara3D.Geometry.Number.MaxValue); } 
        public Vector3 BitDecrement { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.BitDecrement); } 
        public Vector3 BitIncrement { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.BitIncrement); } 
        public Vector3 Cbrt { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Cbrt); } 
        public Vector3 Ceiling { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Ceiling); } 
        public Vector3 Exp { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Exp); } 
        public Vector3 Floor { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Floor); } 
        public Vector3 ILogB { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ILogB); } 
        public Vector3 Log10 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Log10); } 
        public Vector3 Log2 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Log2); } 
        public Vector3 NaturalLog { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.NaturalLog); } 
        public Vector3 Reciprocal { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Reciprocal); } 
        public Vector3 ReciprocalEstimate { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ReciprocalEstimate); } 
        public Vector3 ReciprocalSquareRootEstimate { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ReciprocalSquareRootEstimate); } 
        public Boolean AlmostZero { [MethodImpl(AggressiveInlining)] get  => this.AllComponents((x)  => x.AlmostZero); } 
        [MethodImpl(AggressiveInlining)] public Vector3 Lerp(Vector3 b, Number t){
            var _var14 = t;
            return this.ZipComponents(b, (a1, b1)  => a1.Lerp(b1, _var14));
        }

        public Vector3 Pow2 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow2); } 
        public Vector3 Pow3 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow3); } 
        public Vector3 Sqr { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Sqr); } 
        [MethodImpl(AggressiveInlining)] public Number At(Integer n) => this.Components[n];
        public Number this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Vector3 Modulo(Vector3 b) => this % b;
        [MethodImpl(AggressiveInlining)] public Vector3 Modulo(Number other) => this % other;
    }
    // Extension methods for the type
    public static class Vector3Extensions
    {
        [MethodImpl(AggressiveInlining)] public static Vector3 Modulo(this Vector3 a, Vector3 b) => a.Modulo(b);
        [MethodImpl(AggressiveInlining)] public static Vector3 Modulo(this System.Numerics.Vector3 a, Vector3 b) => ((Vector3)a).Modulo(b);
        [MethodImpl(AggressiveInlining)] public static Vector3 Modulo(this Vector3 self, Number other) => self.Modulo(other);
        [MethodImpl(AggressiveInlining)] public static Vector3 Modulo(this System.Numerics.Vector3 self, Number other) => ((Vector3)self).Modulo(other);
        [MethodImpl(AggressiveInlining)] public static Point3D Point3D(this System.Numerics.Vector3 x) => ((Vector3)x).Point3D;
        [MethodImpl(AggressiveInlining)] public static Ray3D Ray3D(this System.Numerics.Vector3 v) => ((Vector3)v).Ray3D;
        [MethodImpl(AggressiveInlining)] public static Number X(this Vector3 self) => self.X;
        [MethodImpl(AggressiveInlining)] public static Number X(this System.Numerics.Vector3 self) => ((Vector3)self).X;
        [MethodImpl(AggressiveInlining)] public static Number Y(this Vector3 self) => self.Y;
        [MethodImpl(AggressiveInlining)] public static Number Y(this System.Numerics.Vector3 self) => ((Vector3)self).Y;
        [MethodImpl(AggressiveInlining)] public static Number Z(this Vector3 self) => self.Z;
        [MethodImpl(AggressiveInlining)] public static Number Z(this System.Numerics.Vector3 self) => ((Vector3)self).Z;
        [MethodImpl(AggressiveInlining)] public static Vector3 WithX(this Vector3 self, Number x) => self.WithX(x);
        [MethodImpl(AggressiveInlining)] public static Vector3 WithX(this System.Numerics.Vector3 self, Number x) => ((Vector3)self).WithX(x);
        [MethodImpl(AggressiveInlining)] public static Vector3 WithY(this Vector3 self, Number y) => self.WithY(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 WithY(this System.Numerics.Vector3 self, Number y) => ((Vector3)self).WithY(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 WithZ(this Vector3 self, Number z) => self.WithZ(z);
        [MethodImpl(AggressiveInlining)] public static Vector3 WithZ(this System.Numerics.Vector3 self, Number z) => ((Vector3)self).WithZ(z);
        [MethodImpl(AggressiveInlining)] public static Vector3 Normalize(this Vector3 self) => self.Normalize;
        [MethodImpl(AggressiveInlining)] public static Vector3 Normalize(this System.Numerics.Vector3 self) => ((Vector3)self).Normalize;
        [MethodImpl(AggressiveInlining)] public static Number Length(this Vector3 self) => self.Length;
        [MethodImpl(AggressiveInlining)] public static Number Length(this System.Numerics.Vector3 self) => ((Vector3)self).Length;
        [MethodImpl(AggressiveInlining)] public static Number LengthSquared(this Vector3 self) => self.LengthSquared;
        [MethodImpl(AggressiveInlining)] public static Number LengthSquared(this System.Numerics.Vector3 self) => ((Vector3)self).LengthSquared;
        [MethodImpl(AggressiveInlining)] public static Vector3 Abs(this Vector3 self) => self.Abs;
        [MethodImpl(AggressiveInlining)] public static Vector3 Abs(this System.Numerics.Vector3 self) => ((Vector3)self).Abs;
        [MethodImpl(AggressiveInlining)] public static Vector3 Sqrt(this Vector3 self) => self.Sqrt;
        [MethodImpl(AggressiveInlining)] public static Vector3 Sqrt(this System.Numerics.Vector3 self) => ((Vector3)self).Sqrt;
        [MethodImpl(AggressiveInlining)] public static Vector3 Add(this Vector3 left, Vector3 right) => left.Add(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Add(this System.Numerics.Vector3 left, Vector3 right) => ((Vector3)left).Add(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Subtract(this Vector3 left, Vector3 right) => left.Subtract(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Subtract(this System.Numerics.Vector3 left, Vector3 right) => ((Vector3)left).Subtract(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Multiply(this Vector3 left, Vector3 right) => left.Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Multiply(this System.Numerics.Vector3 left, Vector3 right) => ((Vector3)left).Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Multiply(this Vector3 left, Number scalar) => left.Multiply(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector3 Multiply(this System.Numerics.Vector3 left, Number scalar) => ((Vector3)left).Multiply(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector3 Divide(this Vector3 left, Vector3 right) => left.Divide(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Divide(this System.Numerics.Vector3 left, Vector3 right) => ((Vector3)left).Divide(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Divide(this Vector3 left, Number scalar) => left.Divide(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector3 Divide(this System.Numerics.Vector3 left, Number scalar) => ((Vector3)left).Divide(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector3 Negative(this Vector3 value) => value.Negative;
        [MethodImpl(AggressiveInlining)] public static Vector3 Negative(this System.Numerics.Vector3 value) => ((Vector3)value).Negative;
        [MethodImpl(AggressiveInlining)] public static Number Dot(this Vector3 self, Vector3 right) => self.Dot(right);
        [MethodImpl(AggressiveInlining)] public static Number Dot(this System.Numerics.Vector3 self, Vector3 right) => ((Vector3)self).Dot(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Cross(this Vector3 self, Vector3 right) => self.Cross(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Cross(this System.Numerics.Vector3 self, Vector3 right) => ((Vector3)self).Cross(right);
        [MethodImpl(AggressiveInlining)] public static Number Distance(this Vector3 self, Vector3 value2) => self.Distance(value2);
        [MethodImpl(AggressiveInlining)] public static Number Distance(this System.Numerics.Vector3 self, Vector3 value2) => ((Vector3)self).Distance(value2);
        [MethodImpl(AggressiveInlining)] public static Number DistanceSquared(this Vector3 self, Vector3 value2) => self.DistanceSquared(value2);
        [MethodImpl(AggressiveInlining)] public static Number DistanceSquared(this System.Numerics.Vector3 self, Vector3 value2) => ((Vector3)self).DistanceSquared(value2);
        [MethodImpl(AggressiveInlining)] public static Vector3 Clamp(this Vector3 self, Vector3 min, Vector3 max) => self.Clamp(min, max);
        [MethodImpl(AggressiveInlining)] public static Vector3 Clamp(this System.Numerics.Vector3 self, Vector3 min, Vector3 max) => ((Vector3)self).Clamp(min, max);
        [MethodImpl(AggressiveInlining)] public static Vector3 Reflect(this Vector3 self, Vector3 normal) => self.Reflect(normal);
        [MethodImpl(AggressiveInlining)] public static Vector3 Reflect(this System.Numerics.Vector3 self, Vector3 normal) => ((Vector3)self).Reflect(normal);
        [MethodImpl(AggressiveInlining)] public static Vector3 Transform(this Vector3 self, Matrix4x4 matrix) => self.Transform(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector3 Transform(this System.Numerics.Vector3 self, Matrix4x4 matrix) => ((Vector3)self).Transform(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector3 Transform(this Vector3 self, Quaternion rotation) => self.Transform(rotation);
        [MethodImpl(AggressiveInlining)] public static Vector3 Transform(this System.Numerics.Vector3 self, Quaternion rotation) => ((Vector3)self).Transform(rotation);
        [MethodImpl(AggressiveInlining)] public static Vector3 TransformNormal(this Vector3 self, Matrix4x4 matrix) => self.TransformNormal(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector3 TransformNormal(this System.Numerics.Vector3 self, Matrix4x4 matrix) => ((Vector3)self).TransformNormal(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector3 Max(this Vector3 self, Vector3 value2) => self.Max(value2);
        [MethodImpl(AggressiveInlining)] public static Vector3 Max(this System.Numerics.Vector3 self, Vector3 value2) => ((Vector3)self).Max(value2);
        [MethodImpl(AggressiveInlining)] public static Vector3 Min(this Vector3 self, Vector3 value2) => self.Min(value2);
        [MethodImpl(AggressiveInlining)] public static Vector3 Min(this System.Numerics.Vector3 self, Vector3 value2) => ((Vector3)self).Min(value2);
        [MethodImpl(AggressiveInlining)] public static AxisAngle Rotation(this System.Numerics.Vector3 axis, Angle a) => ((Vector3)axis).Rotation(a);
        [MethodImpl(AggressiveInlining)] public static Vector4 Vector4(this System.Numerics.Vector3 v) => ((Vector3)v).Vector4;
        [MethodImpl(AggressiveInlining)] public static Vector4 ToVector4(this System.Numerics.Vector3 v, Number w) => ((Vector3)v).ToVector4(w);
        [MethodImpl(AggressiveInlining)] public static Vector3 XZY(this System.Numerics.Vector3 v) => ((Vector3)v).XZY();
        [MethodImpl(AggressiveInlining)] public static Vector3 YXZ(this System.Numerics.Vector3 v) => ((Vector3)v).YXZ();
        [MethodImpl(AggressiveInlining)] public static Vector3 YZX(this System.Numerics.Vector3 v) => ((Vector3)v).YZX();
        [MethodImpl(AggressiveInlining)] public static Vector3 ZXY(this System.Numerics.Vector3 v) => ((Vector3)v).ZXY();
        [MethodImpl(AggressiveInlining)] public static Vector3 ZYX(this System.Numerics.Vector3 v) => ((Vector3)v).ZYX();
        [MethodImpl(AggressiveInlining)] public static Vector2 XY(this System.Numerics.Vector3 v) => ((Vector3)v).XY();
        [MethodImpl(AggressiveInlining)] public static Vector2 YX(this System.Numerics.Vector3 v) => ((Vector3)v).YX();
        [MethodImpl(AggressiveInlining)] public static Vector2 XZ(this System.Numerics.Vector3 v) => ((Vector3)v).XZ();
        [MethodImpl(AggressiveInlining)] public static Vector2 ZX(this System.Numerics.Vector3 v) => ((Vector3)v).ZX();
        [MethodImpl(AggressiveInlining)] public static Vector2 YZ(this System.Numerics.Vector3 v) => ((Vector3)v).YZ();
        [MethodImpl(AggressiveInlining)] public static Vector2 ZY(this System.Numerics.Vector3 v) => ((Vector3)v).ZY();
        [MethodImpl(AggressiveInlining)] public static Vector2 XX(this System.Numerics.Vector3 v) => ((Vector3)v).XX();
        [MethodImpl(AggressiveInlining)] public static Vector2 YY(this System.Numerics.Vector3 v) => ((Vector3)v).YY();
        [MethodImpl(AggressiveInlining)] public static Vector2 ZZ(this System.Numerics.Vector3 v) => ((Vector3)v).ZZ();
        [MethodImpl(AggressiveInlining)] public static Vector3 Project(this System.Numerics.Vector3 v, Plane p) => ((Vector3)v).Project(p);
        [MethodImpl(AggressiveInlining)] public static Number MixedProduct(this System.Numerics.Vector3 a, Vector3 b, Vector3 c) => ((Vector3)a).MixedProduct(b, c);
        [MethodImpl(AggressiveInlining)] public static Vector2 To2D(this System.Numerics.Vector3 v) => ((Vector3)v).To2D();
        [MethodImpl(AggressiveInlining)] public static Vector3 Project(this System.Numerics.Vector3 v, Vector3 other) => ((Vector3)v).Project(other);
        [MethodImpl(AggressiveInlining)] public static Angle Angle(this System.Numerics.Vector3 a, Vector3 b) => ((Vector3)a).Angle(b);
        [MethodImpl(AggressiveInlining)] public static Boolean IsParallel(this System.Numerics.Vector3 a, Vector3 b) => ((Vector3)a).IsParallel(b);
        [MethodImpl(AggressiveInlining)] public static Vector3 PlusOne(this System.Numerics.Vector3 x) => ((Vector3)x).PlusOne();
        [MethodImpl(AggressiveInlining)] public static Vector3 MinusOne(this System.Numerics.Vector3 x) => ((Vector3)x).MinusOne();
        [MethodImpl(AggressiveInlining)] public static Vector3 FromOne(this System.Numerics.Vector3 x) => ((Vector3)x).FromOne();
        [MethodImpl(AggressiveInlining)] public static Vector3 Barycentric(this System.Numerics.Vector3 v1, Vector3 v2, Vector3 v3, Vector2 uv) => ((Vector3)v1).Barycentric(v2, v3, uv);
        [MethodImpl(AggressiveInlining)] public static Vector3 Linear(this System.Numerics.Vector3 m, Vector3 b, Number x) => ((Vector3)m).Linear(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 Quadratic(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number x) => ((Vector3)a).Quadratic(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 Cubic(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number x) => ((Vector3)a).Cubic(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 Quartic(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Vector3 e, Number x) => ((Vector3)a).Quartic(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 LinearDerivative(this System.Numerics.Vector3 m, Vector3 b, Number x) => ((Vector3)m).LinearDerivative(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 LinearSecondDerivative(this System.Numerics.Vector3 m, Vector3 b, Number x) => ((Vector3)m).LinearSecondDerivative(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuadraticDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number x) => ((Vector3)a).QuadraticDerivative(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuadraticSecondDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number x) => ((Vector3)a).QuadraticSecondDerivative(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 CubicDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number x) => ((Vector3)a).CubicDerivative(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 CubicSecondDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number x) => ((Vector3)a).CubicSecondDerivative(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuarticDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Vector3 e, Vector3 x) => ((Vector3)a).QuarticDerivative(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuarticSecondDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Vector3 e, Number x) => ((Vector3)a).QuarticSecondDerivative(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 CubicBezier(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number t) => ((Vector3)a).CubicBezier(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 CubicBezierDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number t) => ((Vector3)a).CubicBezierDerivative(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 CubicBezierSecondDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number t) => ((Vector3)a).CubicBezierSecondDerivative(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuadraticBezier(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number t) => ((Vector3)a).QuadraticBezier(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuadraticBezierDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number t) => ((Vector3)a).QuadraticBezierDerivative(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuadraticBezierSecondDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number t) => ((Vector3)a).QuadraticBezierSecondDerivative(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 Hermite(this System.Numerics.Vector3 p0, Vector3 p1, Vector3 m0, Vector3 m1, Number t) => ((Vector3)p0).Hermite(p1, m0, m1, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 HermiteDerivative(this System.Numerics.Vector3 p0, Vector3 p1, Vector3 m0, Vector3 m1, Number t) => ((Vector3)p0).HermiteDerivative(p1, m0, m1, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 CatmullRom(this System.Numerics.Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, Number t) => ((Vector3)p0).CatmullRom(p1, p2, p3, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 CatmullRomDerivative(this System.Numerics.Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, Number t) => ((Vector3)p0).CatmullRomDerivative(p1, p2, p3, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 SmoothStep(this System.Numerics.Vector3 x) => ((Vector3)x).SmoothStep();
        [MethodImpl(AggressiveInlining)] public static Vector3 SmootherStep(this System.Numerics.Vector3 x) => ((Vector3)x).SmootherStep();
        [MethodImpl(AggressiveInlining)] public static Number Reduce(this System.Numerics.Vector3 v, Number initial, System.Func<Number, Number, Number> f) => ((Vector3)v).Reduce(initial, f);
        [MethodImpl(AggressiveInlining)] public static Number MinComponent(this System.Numerics.Vector3 x) => ((Vector3)x).MinComponent();
        [MethodImpl(AggressiveInlining)] public static Number MaxComponent(this System.Numerics.Vector3 x) => ((Vector3)x).MaxComponent();
        [MethodImpl(AggressiveInlining)] public static Number SumComponents(this System.Numerics.Vector3 v) => ((Vector3)v).SumComponents();
        [MethodImpl(AggressiveInlining)] public static Number SumSqrComponents(this System.Numerics.Vector3 v) => ((Vector3)v).SumSqrComponents();
        [MethodImpl(AggressiveInlining)] public static Number AvgComponent(this System.Numerics.Vector3 v) => ((Vector3)v).AvgComponent();
        [MethodImpl(AggressiveInlining)] public static Number Magnitude(this System.Numerics.Vector3 v) => ((Vector3)v).Magnitude();
        [MethodImpl(AggressiveInlining)] public static Number MagnitudeSquared(this System.Numerics.Vector3 v) => ((Vector3)v).MagnitudeSquared();
        [MethodImpl(AggressiveInlining)] public static Vector3 BitDecrement(this System.Numerics.Vector3 self) => ((Vector3)self).BitDecrement;
        [MethodImpl(AggressiveInlining)] public static Vector3 BitIncrement(this System.Numerics.Vector3 self) => ((Vector3)self).BitIncrement;
        [MethodImpl(AggressiveInlining)] public static Vector3 Cbrt(this System.Numerics.Vector3 self) => ((Vector3)self).Cbrt;
        [MethodImpl(AggressiveInlining)] public static Vector3 Ceiling(this System.Numerics.Vector3 self) => ((Vector3)self).Ceiling;
        [MethodImpl(AggressiveInlining)] public static Vector3 CopySign(this System.Numerics.Vector3 self, Vector3 y) => ((Vector3)self).CopySign(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 Exp(this System.Numerics.Vector3 self) => ((Vector3)self).Exp;
        [MethodImpl(AggressiveInlining)] public static Vector3 Floor(this System.Numerics.Vector3 self) => ((Vector3)self).Floor;
        [MethodImpl(AggressiveInlining)] public static Vector3 FusedMultiplyAdd(this System.Numerics.Vector3 self, Vector3 y, Vector3 z) => ((Vector3)self).FusedMultiplyAdd(y, z);
        [MethodImpl(AggressiveInlining)] public static Vector3 ILogB(this System.Numerics.Vector3 self) => ((Vector3)self).ILogB;
        [MethodImpl(AggressiveInlining)] public static Vector3 IEEERemainder(this System.Numerics.Vector3 self, Vector3 y) => ((Vector3)self).IEEERemainder(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 Log10(this System.Numerics.Vector3 self) => ((Vector3)self).Log10;
        [MethodImpl(AggressiveInlining)] public static Vector3 Log2(this System.Numerics.Vector3 self) => ((Vector3)self).Log2;
        [MethodImpl(AggressiveInlining)] public static Vector3 MinMagnitude(this System.Numerics.Vector3 self, Vector3 other) => ((Vector3)self).MinMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Vector3 MaxMagnitude(this System.Numerics.Vector3 self, Vector3 other) => ((Vector3)self).MaxMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Vector3 NaturalLog(this System.Numerics.Vector3 self) => ((Vector3)self).NaturalLog;
        [MethodImpl(AggressiveInlining)] public static Vector3 Pow(this System.Numerics.Vector3 self, Vector3 power) => ((Vector3)self).Pow(power);
        [MethodImpl(AggressiveInlining)] public static Vector3 Reciprocal(this System.Numerics.Vector3 self) => ((Vector3)self).Reciprocal;
        [MethodImpl(AggressiveInlining)] public static Vector3 ReciprocalEstimate(this System.Numerics.Vector3 self) => ((Vector3)self).ReciprocalEstimate;
        [MethodImpl(AggressiveInlining)] public static Vector3 ReciprocalSquareRootEstimate(this System.Numerics.Vector3 self) => ((Vector3)self).ReciprocalSquareRootEstimate;
        [MethodImpl(AggressiveInlining)] public static Vector3 RoundToZero(this System.Numerics.Vector3 self, Integer digits) => ((Vector3)self).RoundToZero(digits);
        [MethodImpl(AggressiveInlining)] public static Vector3 ScaleB(this System.Numerics.Vector3 self, Integer n) => ((Vector3)self).ScaleB(n);
        [MethodImpl(AggressiveInlining)] public static Boolean AlmostEqual(this System.Numerics.Vector3 x, Vector3 y) => ((Vector3)x).AlmostEqual(y);
        [MethodImpl(AggressiveInlining)] public static Boolean AlmostZero(this System.Numerics.Vector3 x) => ((Vector3)x).AlmostZero;
        [MethodImpl(AggressiveInlining)] public static Vector3 Average(this System.Numerics.Vector3 x, Vector3 y) => ((Vector3)x).Average(y);
        [MethodImpl(AggressiveInlining)] public static Boolean Between(this System.Numerics.Vector3 x, Vector3 a, Vector3 b) => ((Vector3)x).Between(a, b);
        [MethodImpl(AggressiveInlining)] public static Boolean Between01(this System.Numerics.Vector3 x) => ((Vector3)x).Between01();
        [MethodImpl(AggressiveInlining)] public static Vector3 ClampZeroOne(this System.Numerics.Vector3 x) => ((Vector3)x).ClampZeroOne();
        [MethodImpl(AggressiveInlining)] public static Vector3 Fract(this System.Numerics.Vector3 x) => ((Vector3)x).Fract();
        [MethodImpl(AggressiveInlining)] public static Vector3 InversePow(this System.Numerics.Vector3 x, Vector3 y) => ((Vector3)x).InversePow(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 Lerp(this System.Numerics.Vector3 a, Vector3 b, Number t) => ((Vector3)a).Lerp(b, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 MultiplyEpsilon(this System.Numerics.Vector3 x, Vector3 y) => ((Vector3)x).MultiplyEpsilon(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 Pow2(this System.Numerics.Vector3 x) => ((Vector3)x).Pow2;
        [MethodImpl(AggressiveInlining)] public static Vector3 Pow3(this System.Numerics.Vector3 x) => ((Vector3)x).Pow3;
        [MethodImpl(AggressiveInlining)] public static Vector3 Pow4(this System.Numerics.Vector3 x) => ((Vector3)x).Pow4();
        [MethodImpl(AggressiveInlining)] public static Vector3 Pow5(this System.Numerics.Vector3 x) => ((Vector3)x).Pow5();
        [MethodImpl(AggressiveInlining)] public static Vector3 Sqr(this System.Numerics.Vector3 x) => ((Vector3)x).Sqr;
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Vector3> Sample(this System.Numerics.Vector3 a, Vector3 b, Integer n) => ((Vector3)a).Sample(b, n);
        [MethodImpl(AggressiveInlining)] public static Vector3 Half(this System.Numerics.Vector3 x) => ((Vector3)x).Half();
        [MethodImpl(AggressiveInlining)] public static Vector3 Quarter(this System.Numerics.Vector3 x) => ((Vector3)x).Quarter();
        [MethodImpl(AggressiveInlining)] public static Vector3 Eight(this System.Numerics.Vector3 x) => ((Vector3)x).Eight();
        [MethodImpl(AggressiveInlining)] public static Vector3 Sixteenth(this System.Numerics.Vector3 x) => ((Vector3)x).Sixteenth();
        [MethodImpl(AggressiveInlining)] public static Vector3 Tenth(this System.Numerics.Vector3 x) => ((Vector3)x).Tenth();
        [MethodImpl(AggressiveInlining)] public static Vector3 Twice(this System.Numerics.Vector3 x) => ((Vector3)x).Twice();
        [MethodImpl(AggressiveInlining)] public static Vector3 Hundred(this System.Numerics.Vector3 x) => ((Vector3)x).Hundred();
        [MethodImpl(AggressiveInlining)] public static Vector3 Thousand(this System.Numerics.Vector3 x) => ((Vector3)x).Thousand();
        [MethodImpl(AggressiveInlining)] public static Vector3 Million(this System.Numerics.Vector3 x) => ((Vector3)x).Million();
        [MethodImpl(AggressiveInlining)] public static Vector3 Billion(this System.Numerics.Vector3 x) => ((Vector3)x).Billion();
        [MethodImpl(AggressiveInlining)] public static Vector3 Hundredth(this System.Numerics.Vector3 x) => ((Vector3)x).Hundredth();
        [MethodImpl(AggressiveInlining)] public static Vector3 Thousandth(this System.Numerics.Vector3 x) => ((Vector3)x).Thousandth();
        [MethodImpl(AggressiveInlining)] public static Vector3 Millionth(this System.Numerics.Vector3 x) => ((Vector3)x).Millionth();
        [MethodImpl(AggressiveInlining)] public static Vector3 Billionth(this System.Numerics.Vector3 x) => ((Vector3)x).Billionth();
        [MethodImpl(AggressiveInlining)] public static Number At(this System.Numerics.Vector3 xs, Integer n) => ((Vector3)xs).At(n);
        [MethodImpl(AggressiveInlining)] public static Vector3 Reverse(this System.Numerics.Vector3 xs) => ((Vector3)xs).Reverse();
        [MethodImpl(AggressiveInlining)] public static Vector3 MapComponents(this System.Numerics.Vector3 x, System.Func<Number, Number> f) => ((Vector3)x).MapComponents(f);
        [MethodImpl(AggressiveInlining)] public static Vector3 ZipComponents(this System.Numerics.Vector3 a, Vector3 b, System.Func<Number, Number, Number> f) => ((Vector3)a).ZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Vector3 ZipComponents(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, System.Func<Number, Number, Number, Number> f) => ((Vector3)a).ZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllZipComponents(this System.Numerics.Vector3 a, Vector3 b, System.Func<Number, Number, Boolean> f) => ((Vector3)a).AllZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllZipComponents(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, System.Func<Number, Number, Number, Boolean> f) => ((Vector3)a).AllZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyZipComponents(this System.Numerics.Vector3 a, Vector3 b, System.Func<Number, Number, Boolean> f) => ((Vector3)a).AnyZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyZipComponents(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, System.Func<Number, Number, Number, Boolean> f) => ((Vector3)a).AnyZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllComponents(this System.Numerics.Vector3 x, System.Func<Number, Boolean> predicate) => ((Vector3)x).AllComponents(predicate);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyComponent(this System.Numerics.Vector3 x, System.Func<Number, Boolean> predicate) => ((Vector3)x).AnyComponent(predicate);
    }
}
