// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 10:23:16 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Vector4: IVector<Vector4>
    {
        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Vector4 Create(float x, float y, float z, float w) => new Vector4(x, y, z, w);

        // Static default implementation
        public static readonly Vector4 Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (float, float, float, float)(Vector4 self) => (self.X, self.Y, self.Z, self.W);
        [MethodImpl(AggressiveInlining)] public static implicit operator Vector4((float, float, float, float) value) => new Vector4(value.Item1, value.Item2, value.Item3, value.Item4);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out float x, out float y, out float z, out float w) { x = X; y = Y; z = Z; w = W;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Vector4 other) => Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Vector4 other) => !Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Vector4 other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(Vector4 a, Vector4 b) => a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(Vector4 a, Vector4 b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Value.GetHashCode();
        [MethodImpl(AggressiveInlining)] public override string ToString() => Value.ToString();

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public int NumComponents { [MethodImpl(AggressiveInlining)] get => 4; }
        public IReadOnlyList<float> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<float>(X, Y, Z, W); }
        IReadOnlyList<Number> IArrayLike<Vector4, Number>.Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Number>(X, Y, Z, W); }
        [MethodImpl(AggressiveInlining)] public static Vector4 CreateFromComponents(IReadOnlyList<float> numbers) => new Vector4(numbers[0], numbers[1], numbers[2], numbers[3]);

        [MethodImpl(AggressiveInlining)] public static Vector4 CreateFromComponent(float x) => new Vector4(x, x, x, x);

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public Vector4 Add(Vector4 right) => this + right;
        [MethodImpl(AggressiveInlining)] public Vector4 Subtract(Vector4 right) => this - right;
        [MethodImpl(AggressiveInlining)] public Vector4 Multiply(Vector4 right) => this * right;
        [MethodImpl(AggressiveInlining)] public Vector4 Multiply(Number scalar) => this * scalar;
        [MethodImpl(AggressiveInlining)] public Vector4 Divide(Vector4 right) => this / right;
        [MethodImpl(AggressiveInlining)] public Vector4 Divide(Number scalar) => this / scalar;
        public Vector4 Negative { [MethodImpl(AggressiveInlining)] get => -this; }
        public static Vector4 UnitX { [MethodImpl(AggressiveInlining)] get  => (1f, 0f, 0f, 0f); } 
        public static Vector4 UnitY { [MethodImpl(AggressiveInlining)] get  => (0f, 1f, 0f, 0f); } 
        public static Vector4 UnitZ { [MethodImpl(AggressiveInlining)] get  => (0f, 0f, 1f, 0f); } 
        public static Vector4 UnitW { [MethodImpl(AggressiveInlining)] get  => (0f, 0f, 0f, 1f); } 
        public static Vector4 Zero { [MethodImpl(AggressiveInlining)] get  => Vector4.CreateFromComponent(((Number)(0f))); } 
        public static Vector4 One { [MethodImpl(AggressiveInlining)] get  => Vector4.CreateFromComponent(((Number)(1f))); } 
        public static Vector4 MinValue { [MethodImpl(AggressiveInlining)] get  => Vector4.CreateFromComponent(Ara3D.Geometry.Number.MinValue); } 
        public static Vector4 MaxValue { [MethodImpl(AggressiveInlining)] get  => Vector4.CreateFromComponent(Ara3D.Geometry.Number.MaxValue); } 
        public Vector4 Reciprocal { [MethodImpl(AggressiveInlining)] get  => new Vector4(((float)this.X).Reciprocal(), ((float)this.Y).Reciprocal(), ((float)this.Z).Reciprocal(), ((float)this.W).Reciprocal()); } 
        public Vector4 ReciprocalSquareRootEstimate { [MethodImpl(AggressiveInlining)] get  => new Vector4(((float)this.X).ReciprocalSquareRootEstimate(), ((float)this.Y).ReciprocalSquareRootEstimate(), ((float)this.Z).ReciprocalSquareRootEstimate(), ((float)this.W).ReciprocalSquareRootEstimate()); } 
        public Boolean AlmostZero { [MethodImpl(AggressiveInlining)] get  => ((bool)((float)this.X).AlmostZero()) && ((bool)((float)this.Y).AlmostZero()) && ((bool)((float)this.Z).AlmostZero()) && ((bool)((float)this.W).AlmostZero()); } 
        [MethodImpl(AggressiveInlining)] public Vector4 Lerp(Vector4 b, Number t) => new Vector4(((float)this.X).Lerp(((float)(((float)b.X))), ((float)(((float)t)))), ((float)this.Y).Lerp(((float)(((float)b.Y))), ((float)(((float)t)))), ((float)this.Z).Lerp(((float)(((float)b.Z))), ((float)(((float)t)))), ((float)this.W).Lerp(((float)(((float)b.W))), ((float)(((float)t)))));
        public Vector4 Pow2 { [MethodImpl(AggressiveInlining)] get  => new Vector4(((float)this.X).Pow2(), ((float)this.Y).Pow2(), ((float)this.Z).Pow2(), ((float)this.W).Pow2()); } 
        public Vector4 Pow3 { [MethodImpl(AggressiveInlining)] get  => new Vector4(((float)this.X).Pow3(), ((float)this.Y).Pow3(), ((float)this.Z).Pow3(), ((float)this.W).Pow3()); } 
        public Vector4 Sqr { [MethodImpl(AggressiveInlining)] get  => new Vector4(((float)this.X).Sqr(), ((float)this.Y).Sqr(), ((float)this.Z).Sqr(), ((float)this.W).Sqr()); } 
        [MethodImpl(AggressiveInlining)] public Number At(Integer n) => this.Components[((int)n)];
        public Number this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Vector4 Modulo(Vector4 b) => this % b;
        [MethodImpl(AggressiveInlining)] public Vector4 Modulo(Number other) => this % other;
    }
    // Extension methods for the type
    public static class Vector4Extensions
    {
        [MethodImpl(AggressiveInlining)] public static Vector4 Modulo(this Vector4 a, Vector4 b) => a.Modulo(b);
        [MethodImpl(AggressiveInlining)] public static Vector4 Modulo(this System.Numerics.Vector4 a, Vector4 b) => ((Vector4)a).Modulo(b);
        [MethodImpl(AggressiveInlining)] public static Vector4 Modulo(this Vector4 self, float other) => self.Modulo(other);
        [MethodImpl(AggressiveInlining)] public static Vector4 Modulo(this System.Numerics.Vector4 self, float other) => ((Vector4)self).Modulo(other);
        [MethodImpl(AggressiveInlining)] public static float X(this Vector4 self) => self.X;
        [MethodImpl(AggressiveInlining)] public static float X(this System.Numerics.Vector4 self) => ((Vector4)self).X;
        [MethodImpl(AggressiveInlining)] public static float Y(this Vector4 self) => self.Y;
        [MethodImpl(AggressiveInlining)] public static float Y(this System.Numerics.Vector4 self) => ((Vector4)self).Y;
        [MethodImpl(AggressiveInlining)] public static float Z(this Vector4 self) => self.Z;
        [MethodImpl(AggressiveInlining)] public static float Z(this System.Numerics.Vector4 self) => ((Vector4)self).Z;
        [MethodImpl(AggressiveInlining)] public static float W(this Vector4 self) => self.W;
        [MethodImpl(AggressiveInlining)] public static float W(this System.Numerics.Vector4 self) => ((Vector4)self).W;
        [MethodImpl(AggressiveInlining)] public static Vector4 WithX(this Vector4 self, float x) => self.WithX(x);
        [MethodImpl(AggressiveInlining)] public static Vector4 WithX(this System.Numerics.Vector4 self, float x) => ((Vector4)self).WithX(x);
        [MethodImpl(AggressiveInlining)] public static Vector4 WithY(this Vector4 self, float y) => self.WithY(y);
        [MethodImpl(AggressiveInlining)] public static Vector4 WithY(this System.Numerics.Vector4 self, float y) => ((Vector4)self).WithY(y);
        [MethodImpl(AggressiveInlining)] public static Vector4 WithZ(this Vector4 self, float z) => self.WithZ(z);
        [MethodImpl(AggressiveInlining)] public static Vector4 WithZ(this System.Numerics.Vector4 self, float z) => ((Vector4)self).WithZ(z);
        [MethodImpl(AggressiveInlining)] public static Vector4 WithW(this Vector4 self, float w) => self.WithW(w);
        [MethodImpl(AggressiveInlining)] public static Vector4 WithW(this System.Numerics.Vector4 self, float w) => ((Vector4)self).WithW(w);
        [MethodImpl(AggressiveInlining)] public static Vector4 Normalize(this Vector4 self) => self.Normalize;
        [MethodImpl(AggressiveInlining)] public static Vector4 Normalize(this System.Numerics.Vector4 self) => ((Vector4)self).Normalize;
        [MethodImpl(AggressiveInlining)] public static float Length(this Vector4 self) => self.Length;
        [MethodImpl(AggressiveInlining)] public static float Length(this System.Numerics.Vector4 self) => ((Vector4)self).Length;
        [MethodImpl(AggressiveInlining)] public static float LengthSquared(this Vector4 self) => self.LengthSquared;
        [MethodImpl(AggressiveInlining)] public static float LengthSquared(this System.Numerics.Vector4 self) => ((Vector4)self).LengthSquared;
        [MethodImpl(AggressiveInlining)] public static Vector4 Abs(this Vector4 self) => self.Abs;
        [MethodImpl(AggressiveInlining)] public static Vector4 Abs(this System.Numerics.Vector4 self) => ((Vector4)self).Abs;
        [MethodImpl(AggressiveInlining)] public static Vector4 Sqrt(this Vector4 self) => self.Sqrt;
        [MethodImpl(AggressiveInlining)] public static Vector4 Sqrt(this System.Numerics.Vector4 self) => ((Vector4)self).Sqrt;
        [MethodImpl(AggressiveInlining)] public static Vector4 Add(this Vector4 left, Vector4 right) => left.Add(right);
        [MethodImpl(AggressiveInlining)] public static Vector4 Add(this System.Numerics.Vector4 left, Vector4 right) => ((Vector4)left).Add(right);
        [MethodImpl(AggressiveInlining)] public static Vector4 Subtract(this Vector4 left, Vector4 right) => left.Subtract(right);
        [MethodImpl(AggressiveInlining)] public static Vector4 Subtract(this System.Numerics.Vector4 left, Vector4 right) => ((Vector4)left).Subtract(right);
        [MethodImpl(AggressiveInlining)] public static Vector4 Multiply(this Vector4 left, Vector4 right) => left.Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector4 Multiply(this System.Numerics.Vector4 left, Vector4 right) => ((Vector4)left).Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector4 Multiply(this Vector4 left, float scalar) => left.Multiply(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector4 Multiply(this System.Numerics.Vector4 left, float scalar) => ((Vector4)left).Multiply(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector4 Divide(this Vector4 left, Vector4 right) => left.Divide(right);
        [MethodImpl(AggressiveInlining)] public static Vector4 Divide(this System.Numerics.Vector4 left, Vector4 right) => ((Vector4)left).Divide(right);
        [MethodImpl(AggressiveInlining)] public static Vector4 Divide(this Vector4 left, float scalar) => left.Divide(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector4 Divide(this System.Numerics.Vector4 left, float scalar) => ((Vector4)left).Divide(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector4 Negative(this Vector4 value) => value.Negative;
        [MethodImpl(AggressiveInlining)] public static Vector4 Negative(this System.Numerics.Vector4 value) => ((Vector4)value).Negative;
        [MethodImpl(AggressiveInlining)] public static float Dot(this Vector4 self, Vector4 right) => self.Dot(right);
        [MethodImpl(AggressiveInlining)] public static float Dot(this System.Numerics.Vector4 self, Vector4 right) => ((Vector4)self).Dot(right);
        [MethodImpl(AggressiveInlining)] public static float Distance(this Vector4 self, Vector4 value2) => self.Distance(value2);
        [MethodImpl(AggressiveInlining)] public static float Distance(this System.Numerics.Vector4 self, Vector4 value2) => ((Vector4)self).Distance(value2);
        [MethodImpl(AggressiveInlining)] public static float DistanceSquared(this Vector4 self, Vector4 value2) => self.DistanceSquared(value2);
        [MethodImpl(AggressiveInlining)] public static float DistanceSquared(this System.Numerics.Vector4 self, Vector4 value2) => ((Vector4)self).DistanceSquared(value2);
        [MethodImpl(AggressiveInlining)] public static Vector4 Clamp(this Vector4 self, Vector4 min, Vector4 max) => self.Clamp(min, max);
        [MethodImpl(AggressiveInlining)] public static Vector4 Clamp(this System.Numerics.Vector4 self, Vector4 min, Vector4 max) => ((Vector4)self).Clamp(min, max);
        [MethodImpl(AggressiveInlining)] public static Vector4 Transform(this Vector4 self, Matrix4x4 matrix) => self.Transform(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector4 Transform(this System.Numerics.Vector4 self, Matrix4x4 matrix) => ((Vector4)self).Transform(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector4 Transform(this Vector4 self, Quaternion rotation) => self.Transform(rotation);
        [MethodImpl(AggressiveInlining)] public static Vector4 Transform(this System.Numerics.Vector4 self, Quaternion rotation) => ((Vector4)self).Transform(rotation);
        [MethodImpl(AggressiveInlining)] public static Vector4 Max(this Vector4 self, Vector4 value2) => self.Max(value2);
        [MethodImpl(AggressiveInlining)] public static Vector4 Max(this System.Numerics.Vector4 self, Vector4 value2) => ((Vector4)self).Max(value2);
        [MethodImpl(AggressiveInlining)] public static Vector4 Min(this Vector4 self, Vector4 value2) => self.Min(value2);
        [MethodImpl(AggressiveInlining)] public static Vector4 Min(this System.Numerics.Vector4 self, Vector4 value2) => ((Vector4)self).Min(value2);
        [MethodImpl(AggressiveInlining)] public static Vector3 XYZ(this System.Numerics.Vector4 v) => ((Vector4)v).XYZ();
        [MethodImpl(AggressiveInlining)] public static Vector8 Vector8(this System.Numerics.Vector4 v1, Vector4 v2) => ((Vector4)v1).Vector8(v2);
        [MethodImpl(AggressiveInlining)] public static Vector4 Reflect(this System.Numerics.Vector4 v, Vector4 normal) => ((Vector4)v).Reflect(normal);
        [MethodImpl(AggressiveInlining)] public static Vector4 Project(this System.Numerics.Vector4 v, Vector4 other) => ((Vector4)v).Project(other);
        [MethodImpl(AggressiveInlining)] public static Angle Angle(this System.Numerics.Vector4 a, Vector4 b) => ((Vector4)a).Angle(b);
        [MethodImpl(AggressiveInlining)] public static bool IsParallel(this System.Numerics.Vector4 a, Vector4 b) => ((Vector4)a).IsParallel(b);
        [MethodImpl(AggressiveInlining)] public static Vector4 PlusOne(this System.Numerics.Vector4 x) => ((Vector4)x).PlusOne();
        [MethodImpl(AggressiveInlining)] public static Vector4 MinusOne(this System.Numerics.Vector4 x) => ((Vector4)x).MinusOne();
        [MethodImpl(AggressiveInlining)] public static Vector4 FromOne(this System.Numerics.Vector4 x) => ((Vector4)x).FromOne();
        [MethodImpl(AggressiveInlining)] public static Vector4 Barycentric(this System.Numerics.Vector4 v1, Vector4 v2, Vector4 v3, Vector2 uv) => ((Vector4)v1).Barycentric(v2, v3, uv);
        [MethodImpl(AggressiveInlining)] public static Vector4 Linear(this System.Numerics.Vector4 m, Vector4 b, float x) => ((Vector4)m).Linear(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 Quadratic(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, float x) => ((Vector4)a).Quadratic(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 Cubic(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, Vector4 d, float x) => ((Vector4)a).Cubic(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 Quartic(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, Vector4 d, Vector4 e, float x) => ((Vector4)a).Quartic(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 LinearDerivative(this System.Numerics.Vector4 m, Vector4 b, float x) => ((Vector4)m).LinearDerivative(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 LinearSecondDerivative(this System.Numerics.Vector4 m, Vector4 b, float x) => ((Vector4)m).LinearSecondDerivative(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 QuadraticDerivative(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, float x) => ((Vector4)a).QuadraticDerivative(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 QuadraticSecondDerivative(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, float x) => ((Vector4)a).QuadraticSecondDerivative(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 CubicDerivative(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, Vector4 d, float x) => ((Vector4)a).CubicDerivative(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 CubicSecondDerivative(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, Vector4 d, float x) => ((Vector4)a).CubicSecondDerivative(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 QuarticDerivative(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, Vector4 d, Vector4 e, Vector4 x) => ((Vector4)a).QuarticDerivative(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 QuarticSecondDerivative(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, Vector4 d, Vector4 e, float x) => ((Vector4)a).QuarticSecondDerivative(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector4 CubicBezier(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, Vector4 d, float t) => ((Vector4)a).CubicBezier(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector4 CubicBezierDerivative(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, Vector4 d, float t) => ((Vector4)a).CubicBezierDerivative(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector4 CubicBezierSecondDerivative(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, Vector4 d, float t) => ((Vector4)a).CubicBezierSecondDerivative(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector4 QuadraticBezier(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, float t) => ((Vector4)a).QuadraticBezier(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector4 QuadraticBezierDerivative(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, float t) => ((Vector4)a).QuadraticBezierDerivative(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector4 QuadraticBezierSecondDerivative(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, float t) => ((Vector4)a).QuadraticBezierSecondDerivative(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector4 Hermite(this System.Numerics.Vector4 p0, Vector4 p1, Vector4 m0, Vector4 m1, float t) => ((Vector4)p0).Hermite(p1, m0, m1, t);
        [MethodImpl(AggressiveInlining)] public static Vector4 HermiteDerivative(this System.Numerics.Vector4 p0, Vector4 p1, Vector4 m0, Vector4 m1, float t) => ((Vector4)p0).HermiteDerivative(p1, m0, m1, t);
        [MethodImpl(AggressiveInlining)] public static Vector4 CatmullRom(this System.Numerics.Vector4 p0, Vector4 p1, Vector4 p2, Vector4 p3, float t) => ((Vector4)p0).CatmullRom(p1, p2, p3, t);
        [MethodImpl(AggressiveInlining)] public static Vector4 CatmullRomDerivative(this System.Numerics.Vector4 p0, Vector4 p1, Vector4 p2, Vector4 p3, float t) => ((Vector4)p0).CatmullRomDerivative(p1, p2, p3, t);
        [MethodImpl(AggressiveInlining)] public static Vector4 SmoothStep(this System.Numerics.Vector4 x) => ((Vector4)x).SmoothStep();
        [MethodImpl(AggressiveInlining)] public static Vector4 SmootherStep(this System.Numerics.Vector4 x) => ((Vector4)x).SmootherStep();
        [MethodImpl(AggressiveInlining)] public static float Reduce(this System.Numerics.Vector4 v, float initial, System.Func<float, float, float> f) => ((Vector4)v).Reduce(initial, f);
        [MethodImpl(AggressiveInlining)] public static float MinComponent(this System.Numerics.Vector4 x) => ((Vector4)x).MinComponent();
        [MethodImpl(AggressiveInlining)] public static float MaxComponent(this System.Numerics.Vector4 x) => ((Vector4)x).MaxComponent();
        [MethodImpl(AggressiveInlining)] public static float SumComponents(this System.Numerics.Vector4 v) => ((Vector4)v).SumComponents();
        [MethodImpl(AggressiveInlining)] public static float SumSqrComponents(this System.Numerics.Vector4 v) => ((Vector4)v).SumSqrComponents();
        [MethodImpl(AggressiveInlining)] public static float AvgComponent(this System.Numerics.Vector4 v) => ((Vector4)v).AvgComponent();
        [MethodImpl(AggressiveInlining)] public static float Magnitude(this System.Numerics.Vector4 v) => ((Vector4)v).Magnitude();
        [MethodImpl(AggressiveInlining)] public static float MagnitudeSquared(this System.Numerics.Vector4 v) => ((Vector4)v).MagnitudeSquared();
        [MethodImpl(AggressiveInlining)] public static Vector4 BitDecrement(this System.Numerics.Vector4 self) => ((Vector4)self).BitDecrement();
        [MethodImpl(AggressiveInlining)] public static Vector4 BitIncrement(this System.Numerics.Vector4 self) => ((Vector4)self).BitIncrement();
        [MethodImpl(AggressiveInlining)] public static Vector4 Cbrt(this System.Numerics.Vector4 self) => ((Vector4)self).Cbrt();
        [MethodImpl(AggressiveInlining)] public static Vector4 Ceiling(this System.Numerics.Vector4 self) => ((Vector4)self).Ceiling();
        [MethodImpl(AggressiveInlining)] public static Vector4 CopySign(this System.Numerics.Vector4 self, Vector4 y) => ((Vector4)self).CopySign(y);
        [MethodImpl(AggressiveInlining)] public static Vector4 Exp(this System.Numerics.Vector4 self) => ((Vector4)self).Exp();
        [MethodImpl(AggressiveInlining)] public static Vector4 Floor(this System.Numerics.Vector4 self) => ((Vector4)self).Floor();
        [MethodImpl(AggressiveInlining)] public static Vector4 FusedMultiplyAdd(this System.Numerics.Vector4 self, Vector4 y, Vector4 z) => ((Vector4)self).FusedMultiplyAdd(y, z);
        [MethodImpl(AggressiveInlining)] public static Vector4 ILogB(this System.Numerics.Vector4 self) => ((Vector4)self).ILogB();
        [MethodImpl(AggressiveInlining)] public static Vector4 IEEERemainder(this System.Numerics.Vector4 self, Vector4 y) => ((Vector4)self).IEEERemainder(y);
        [MethodImpl(AggressiveInlining)] public static Vector4 Log10(this System.Numerics.Vector4 self) => ((Vector4)self).Log10();
        [MethodImpl(AggressiveInlining)] public static Vector4 Log2(this System.Numerics.Vector4 self) => ((Vector4)self).Log2();
        [MethodImpl(AggressiveInlining)] public static Vector4 MinMagnitude(this System.Numerics.Vector4 self, Vector4 other) => ((Vector4)self).MinMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Vector4 MaxMagnitude(this System.Numerics.Vector4 self, Vector4 other) => ((Vector4)self).MaxMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Vector4 NaturalLog(this System.Numerics.Vector4 self) => ((Vector4)self).NaturalLog();
        [MethodImpl(AggressiveInlining)] public static Vector4 Pow(this System.Numerics.Vector4 self, Vector4 power) => ((Vector4)self).Pow(power);
        [MethodImpl(AggressiveInlining)] public static Vector4 Reciprocal(this System.Numerics.Vector4 self) => ((Vector4)self).Reciprocal;
        [MethodImpl(AggressiveInlining)] public static Vector4 ReciprocalEstimate(this System.Numerics.Vector4 self) => ((Vector4)self).ReciprocalEstimate();
        [MethodImpl(AggressiveInlining)] public static Vector4 ReciprocalSquareRootEstimate(this System.Numerics.Vector4 self) => ((Vector4)self).ReciprocalSquareRootEstimate;
        [MethodImpl(AggressiveInlining)] public static Vector4 RoundToZero(this System.Numerics.Vector4 self, int digits) => ((Vector4)self).RoundToZero(digits);
        [MethodImpl(AggressiveInlining)] public static Vector4 ScaleB(this System.Numerics.Vector4 self, int n) => ((Vector4)self).ScaleB(n);
        [MethodImpl(AggressiveInlining)] public static bool AlmostEqual(this System.Numerics.Vector4 x, Vector4 y) => ((Vector4)x).AlmostEqual(y);
        [MethodImpl(AggressiveInlining)] public static bool AlmostZero(this System.Numerics.Vector4 x) => ((Vector4)x).AlmostZero;
        [MethodImpl(AggressiveInlining)] public static Vector4 Average(this System.Numerics.Vector4 x, Vector4 y) => ((Vector4)x).Average(y);
        [MethodImpl(AggressiveInlining)] public static bool Between(this System.Numerics.Vector4 x, Vector4 a, Vector4 b) => ((Vector4)x).Between(a, b);
        [MethodImpl(AggressiveInlining)] public static bool Between01(this System.Numerics.Vector4 x) => ((Vector4)x).Between01();
        [MethodImpl(AggressiveInlining)] public static Vector4 ClampZeroOne(this System.Numerics.Vector4 x) => ((Vector4)x).ClampZeroOne();
        [MethodImpl(AggressiveInlining)] public static Vector4 Fract(this System.Numerics.Vector4 x) => ((Vector4)x).Fract();
        [MethodImpl(AggressiveInlining)] public static Vector4 InversePow(this System.Numerics.Vector4 x, Vector4 y) => ((Vector4)x).InversePow(y);
        [MethodImpl(AggressiveInlining)] public static Vector4 Lerp(this System.Numerics.Vector4 a, Vector4 b, float t) => ((Vector4)a).Lerp(b, t);
        [MethodImpl(AggressiveInlining)] public static Vector4 MultiplyEpsilon(this System.Numerics.Vector4 x, Vector4 y) => ((Vector4)x).MultiplyEpsilon(y);
        [MethodImpl(AggressiveInlining)] public static Vector4 Pow2(this System.Numerics.Vector4 x) => ((Vector4)x).Pow2;
        [MethodImpl(AggressiveInlining)] public static Vector4 Pow3(this System.Numerics.Vector4 x) => ((Vector4)x).Pow3;
        [MethodImpl(AggressiveInlining)] public static Vector4 Pow4(this System.Numerics.Vector4 x) => ((Vector4)x).Pow4();
        [MethodImpl(AggressiveInlining)] public static Vector4 Pow5(this System.Numerics.Vector4 x) => ((Vector4)x).Pow5();
        [MethodImpl(AggressiveInlining)] public static Vector4 Sqr(this System.Numerics.Vector4 x) => ((Vector4)x).Sqr;
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Vector4> Sample(this System.Numerics.Vector4 a, Vector4 b, int n) => ((Vector4)a).Sample(b, n);
        [MethodImpl(AggressiveInlining)] public static Vector4 Half(this System.Numerics.Vector4 x) => ((Vector4)x).Half();
        [MethodImpl(AggressiveInlining)] public static Vector4 Quarter(this System.Numerics.Vector4 x) => ((Vector4)x).Quarter();
        [MethodImpl(AggressiveInlining)] public static Vector4 Eight(this System.Numerics.Vector4 x) => ((Vector4)x).Eight();
        [MethodImpl(AggressiveInlining)] public static Vector4 Sixteenth(this System.Numerics.Vector4 x) => ((Vector4)x).Sixteenth();
        [MethodImpl(AggressiveInlining)] public static Vector4 Tenth(this System.Numerics.Vector4 x) => ((Vector4)x).Tenth();
        [MethodImpl(AggressiveInlining)] public static Vector4 Twice(this System.Numerics.Vector4 x) => ((Vector4)x).Twice();
        [MethodImpl(AggressiveInlining)] public static Vector4 Hundred(this System.Numerics.Vector4 x) => ((Vector4)x).Hundred();
        [MethodImpl(AggressiveInlining)] public static Vector4 Thousand(this System.Numerics.Vector4 x) => ((Vector4)x).Thousand();
        [MethodImpl(AggressiveInlining)] public static Vector4 Million(this System.Numerics.Vector4 x) => ((Vector4)x).Million();
        [MethodImpl(AggressiveInlining)] public static Vector4 Billion(this System.Numerics.Vector4 x) => ((Vector4)x).Billion();
        [MethodImpl(AggressiveInlining)] public static Vector4 Hundredth(this System.Numerics.Vector4 x) => ((Vector4)x).Hundredth();
        [MethodImpl(AggressiveInlining)] public static Vector4 Thousandth(this System.Numerics.Vector4 x) => ((Vector4)x).Thousandth();
        [MethodImpl(AggressiveInlining)] public static Vector4 Millionth(this System.Numerics.Vector4 x) => ((Vector4)x).Millionth();
        [MethodImpl(AggressiveInlining)] public static Vector4 Billionth(this System.Numerics.Vector4 x) => ((Vector4)x).Billionth();
        [MethodImpl(AggressiveInlining)] public static float At(this System.Numerics.Vector4 xs, int n) => ((Vector4)xs).At(n);
        [MethodImpl(AggressiveInlining)] public static Vector4 Reverse(this System.Numerics.Vector4 xs) => ((Vector4)xs).Reverse();
        [MethodImpl(AggressiveInlining)] public static Vector4 MapComponents(this System.Numerics.Vector4 x, System.Func<float, float> f) => ((Vector4)x).MapComponents(f);
        [MethodImpl(AggressiveInlining)] public static Vector4 ZipComponents(this System.Numerics.Vector4 a, Vector4 b, System.Func<float, float, float> f) => ((Vector4)a).ZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Vector4 ZipComponents(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, System.Func<float, float, float, float> f) => ((Vector4)a).ZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static bool AllZipComponents(this System.Numerics.Vector4 a, Vector4 b, System.Func<float, float, bool> f) => ((Vector4)a).AllZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static bool AllZipComponents(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, System.Func<float, float, float, bool> f) => ((Vector4)a).AllZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static bool AnyZipComponents(this System.Numerics.Vector4 a, Vector4 b, System.Func<float, float, bool> f) => ((Vector4)a).AnyZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static bool AnyZipComponents(this System.Numerics.Vector4 a, Vector4 b, Vector4 c, System.Func<float, float, float, bool> f) => ((Vector4)a).AnyZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static bool AllComponents(this System.Numerics.Vector4 x, System.Func<float, bool> predicate) => ((Vector4)x).AllComponents(predicate);
        [MethodImpl(AggressiveInlining)] public static bool AnyComponent(this System.Numerics.Vector4 x, System.Func<float, bool> predicate) => ((Vector4)x).AnyComponent(predicate);
    }
}
