// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class Angles
    {
        [MethodImpl(AggressiveInlining)] public static Angle Turns(this Number x) => x.Multiply(Constants.TwoPi);
        [MethodImpl(AggressiveInlining)] public static Angle Degrees(this Number x) => x.Divide(((Number)360)).Turns();
        [MethodImpl(AggressiveInlining)] public static Angle Gradians(this Number x) => x.Divide(((Number)400)).Turns();
        [MethodImpl(AggressiveInlining)] public static Angle ArcMinutes(this Number x) => x.Multiply(((Number)60)).Degrees();
        [MethodImpl(AggressiveInlining)] public static Angle ArcSeconds(this Number x) => x.Multiply(((Number)60)).ArcMinutes();
        [MethodImpl(AggressiveInlining)] public static Number Turns(this Angle x) => x.Radians.Divide(Constants.TwoPi);
        [MethodImpl(AggressiveInlining)] public static Number Degrees(this Angle x) => x.Turns().Multiply(((Number)360));
        [MethodImpl(AggressiveInlining)] public static Number Gradians(this Angle x) => x.Turns().Multiply(((Number)400));
        [MethodImpl(AggressiveInlining)] public static Number Sec(this Angle x) => x.Cos.Reciprocal;
        [MethodImpl(AggressiveInlining)] public static Number Csc(this Angle x) => x.Sin.Reciprocal;
        [MethodImpl(AggressiveInlining)] public static Number Cot(this Angle x) => x.Tan.Reciprocal;
        [MethodImpl(AggressiveInlining)] public static Angle Turns(this Integer x) => x.Number.Turns();
        [MethodImpl(AggressiveInlining)] public static Angle Degrees(this Integer x) => x.Number.Degrees();
        [MethodImpl(AggressiveInlining)] public static Angle Gradians(this Integer x) => x.Number.Gradians();
        [MethodImpl(AggressiveInlining)] public static Angle ArcMinutes(this Integer x) => x.Number.ArcMinutes();
        [MethodImpl(AggressiveInlining)] public static Angle ArcSeconds(this Integer x) => x.Number.ArcSeconds();
    }
}
