// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 10:23:16 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class AngularCurves2D
    {
        [MethodImpl(AggressiveInlining)] public static Point2D UnitCircle(this Angle t) => (((float)t.Cos), ((float)t.Sin));
        [MethodImpl(AggressiveInlining)] public static Point2D Circle(this Angle t, Point2D center, float radius) => t.UnitCircle().Multiply(((Number)(((float)radius)))).Add(center);
        [MethodImpl(AggressiveInlining)] public static Point2D Ellipse(this Angle t, Point2D center, Vector2 size) => t.UnitCircle().Multiply(size).Add(center);
        [MethodImpl(AggressiveInlining)] public static Point2D Epicycloid(this Angle t, float R, float r) => (((float)R).Add(((float)(((float)r)))).Multiply(((float)(((float)t.Cos)))).Subtract(((float)(((float)r).Multiply(((float)(((float)((float)R).Add(((float)(((float)r)))).Divide(((float)(((float)r)))).Multiply(t).Cos))))))), ((float)R).Add(((float)(((float)r)))).Multiply(((float)(((float)t.Sin)))).Subtract(((float)(((float)r).Multiply(((float)(((float)((float)R).Add(((float)(((float)r)))).Divide(((float)(((float)r)))).Multiply(t).Sin))))))));
        [MethodImpl(AggressiveInlining)] public static Point2D Hypocycloid(this Angle t, float R, float r) => (((float)R).Subtract(((float)(((float)r)))).Multiply(((float)(((float)t.Cos)))).Add(((float)(((float)r).Multiply(((float)(((float)((float)R).Subtract(((float)(((float)r)))).Divide(((float)(((float)r)))).Multiply(t).Cos))))))), ((float)R).Subtract(((float)(((float)r)))).Multiply(((float)(((float)t.Sin)))).Subtract(((float)(((float)r).Multiply(((float)(((float)((float)R).Subtract(((float)(((float)r)))).Divide(((float)(((float)r)))).Multiply(t).Sin))))))));
        [MethodImpl(AggressiveInlining)] public static Point2D Epitrochoid(this Angle t, float R, float r, float d) => (((float)R).Add(((float)(((float)r)))).Multiply(((float)(((float)t.Cos)))).Subtract(((float)(((float)d).Multiply(((float)(((float)((float)R).Add(((float)(((float)r)))).Divide(((float)(((float)r)))).Multiply(t).Cos))))))), ((float)R).Add(((float)(((float)r)))).Multiply(((float)(((float)t.Sin)))).Subtract(((float)(((float)d).Multiply(((float)(((float)((float)R).Add(((float)(((float)r)))).Divide(((float)(((float)r)))).Multiply(t).Sin))))))));
        [MethodImpl(AggressiveInlining)] public static Point2D Hypotrochoid(this Angle t, float R, float r, float d) => (((float)R).Subtract(((float)(((float)r)))).Multiply(((float)(((float)t.Cos)))).Add(((float)(((float)d).Multiply(((float)(((float)((float)R).Subtract(((float)(((float)r)))).Divide(((float)(((float)r)))).Multiply(t).Cos))))))), ((float)R).Subtract(((float)(((float)r)))).Multiply(((float)(((float)t.Sin)))).Subtract(((float)(((float)d).Multiply(((float)(((float)((float)R).Subtract(((float)(((float)r)))).Divide(((float)(((float)r)))).Multiply(t).Sin))))))));
        [MethodImpl(AggressiveInlining)] public static Point2D ButterflyCurve(this Angle t) => t.Divide(((Number)(6f))).ButterflyCurveSection();
        [MethodImpl(AggressiveInlining)] public static Point2D ButterflyCurveSection(this Angle t) => (((float)t.Multiply(((Number)(((float)t.Cos).Exp().Subtract(((float)(2f.Multiply(((float)(((float)t.Multiply(((Number)(4f))).Cos))))))).Subtract(((float)(((float)t.Divide(((Number)(12f))).Sin).Pow(((float)(5f))))))))).Sin), ((float)t.Multiply(((Number)(((float)t.Cos).Exp().Subtract(((float)(2f.Multiply(((float)(((float)t.Multiply(((Number)(4f))).Cos))))))).Subtract(((float)(((float)t.Divide(((Number)(12f))).Sin).Pow(((float)(5f))))))))).Cos));
        [MethodImpl(AggressiveInlining)] public static Point2D Lissajous(this Angle t, float a, float b, Angle d) => (((float)t.Multiply(((Number)(((float)a)))).Add(d).Sin), ((float)t.Multiply(((Number)(((float)b)))).Sin));
    }
}
