// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 2:43:27 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class Curves
    {
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Spiral curve, int numPoints){
            var _var65 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var65.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Spiral curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this QuadraticBezier2D curve, int numPoints){
            var _var66 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var66.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this QuadraticBezier2D curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this CubicBezier2D curve, int numPoints){
            var _var67 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var67.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this CubicBezier2D curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Circle curve, int numPoints){
            var _var68 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var68.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Circle curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Ellipse curve, int numPoints){
            var _var69 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var69.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Ellipse curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Epicycloid curve, int numPoints){
            var _var70 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var70.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Epicycloid curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Hypocycloid curve, int numPoints){
            var _var71 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var71.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Hypocycloid curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Epitrochoid curve, int numPoints){
            var _var72 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var72.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Epitrochoid curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Hypotrochoid curve, int numPoints){
            var _var73 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var73.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Hypotrochoid curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this ButterflyCurve curve, int numPoints){
            var _var74 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var74.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this ButterflyCurve curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Lissajous curve, int numPoints){
            var _var75 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var75.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Lissajous curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this CycloidOfCeva curve, int numPoints){
            var _var76 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var76.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this CycloidOfCeva curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Limacon curve, int numPoints){
            var _var77 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var77.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Limacon curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Cardoid curve, int numPoints){
            var _var78 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var78.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Cardoid curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Rose curve, int numPoints){
            var _var79 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var79.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Rose curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this ArchimedeanSpiral curve, int numPoints){
            var _var80 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var80.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this ArchimedeanSpiral curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this ConicSection curve, int numPoints){
            var _var81 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var81.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this ConicSection curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this LemniscateOfBernoulli curve, int numPoints){
            var _var82 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var82.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this LemniscateOfBernoulli curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this TrisectrixOfMaclaurin curve, int numPoints){
            var _var83 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var83.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this TrisectrixOfMaclaurin curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this ConchoidOfDeSluze curve, int numPoints){
            var _var84 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var84.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this ConchoidOfDeSluze curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this TschirnhausenCubic curve, int numPoints){
            var _var85 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var85.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this TschirnhausenCubic curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this SinusoidalSpiral curve, int numPoints){
            var _var86 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var86.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this SinusoidalSpiral curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this FermatsSpiral curve, int numPoints){
            var _var87 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var87.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this FermatsSpiral curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this LogarithmicSpiral curve, int numPoints){
            var _var88 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var88.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this LogarithmicSpiral curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point3D> Sample(this TorusKnot curve, int numPoints){
            var _var89 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var89.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine3D ToPolyLine3D(this TorusKnot curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point3D> Sample(this TrefoilKnot curve, int numPoints){
            var _var90 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var90.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine3D ToPolyLine3D(this TrefoilKnot curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point3D> Sample(this FigureEightKnot curve, int numPoints){
            var _var91 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var91.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine3D ToPolyLine3D(this FigureEightKnot curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point3D> Sample(this Helix curve, int numPoints){
            var _var92 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var92.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine3D ToPolyLine3D(this Helix curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Triangle2D curve, int numPoints){
            var _var93 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var93.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Triangle2D curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Quad2D curve, int numPoints){
            var _var94 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var94.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Quad2D curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Rect2D curve, int numPoints){
            var _var95 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var95.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Rect2D curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this RegularPolygon curve, int numPoints){
            var _var96 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var96.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this RegularPolygon curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Sample(this Polygon curve, int numPoints){
            var _var97 = curve;
            return ((int)numPoints).LinearSpace().Map((x)  => _var97.Eval(x));
        }

        [MethodImpl(AggressiveInlining)] public static PolyLine2D ToPolyLine2D(this Polygon curve, int numPoints) => (curve.Sample(((Integer)(((int)numPoints)))), ((bool)curve.Closed));
        [MethodImpl(AggressiveInlining)] public static float SineWave(this float x, float amplitude, float frequency, float phase) => ((float)amplitude).Multiply(((float)(((float)frequency).Multiply(((float)(((float)((float)x).Turns().Sin)))).Add(((float)(((float)phase)))))));
        [MethodImpl(AggressiveInlining)] public static float StaircaseFloor(this float x, int steps) => ((float)x).Multiply(((float)(((int)steps)))).Floor().Divide(((float)(((int)steps))));
        [MethodImpl(AggressiveInlining)] public static float StaircaseCeiling(this float x, int steps) => ((float)x).Multiply(((float)(((int)steps)))).Ceiling().Divide(((float)(((int)steps))));
        [MethodImpl(AggressiveInlining)] public static float StaircaseRound(this float x, int steps) => ((float)((float)x).Multiply(((float)(((int)steps)))).Round(((int)(0)))).Divide(((float)(((int)steps))));
    }
}
