// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class Curves2D
    {
        [MethodImpl(AggressiveInlining)] public static Point2D Spiral(this Number t, Number R, Number r, Number numTurns) => new Vector2(t.Turns().Multiply(numTurns).Cos, t.Turns().Multiply(numTurns).Sin).Multiply(r.Lerp(R, t));
    }
}
