// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class Geometry
    {
        [MethodImpl(AggressiveInlining)] public static Line2D LineTo(this Point2D a, Point2D b) => (a, b);
        [MethodImpl(AggressiveInlining)] public static Ray2D RayTo(this Point2D a, Point2D b) => (a, b.Subtract(a));
        [MethodImpl(AggressiveInlining)] public static Ray2D RayFrom(this Point2D a, Vector2 dir) => (a, dir);
        [MethodImpl(AggressiveInlining)] public static Point3D To3D(this Point2D x) => (x.X, x.Y, ((Integer)0));
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> Corners(this Bounds2D x) => Intrinsics.MakeArray(new Point2D(x.Min.X, x.Min.Y), new Point2D(x.Max.X, x.Min.Y), new Point2D(x.Min.X, x.Max.Y), new Point2D(x.Max.X, x.Max.Y), new Point2D(x.Min.X, x.Min.Y), new Point2D(x.Max.X, x.Min.Y), new Point2D(x.Min.X, x.Max.Y), new Point2D(x.Max.X, x.Max.Y));
        [MethodImpl(AggressiveInlining)] public static Bounds3D To3D(this Bounds2D x) => (x.Min.To3D(), x.Max.To3D());
        [MethodImpl(AggressiveInlining)] public static Ray3D To3D(this Ray2D x) => (x.Origin.To3D(), x.Direction.To3D());
        [MethodImpl(AggressiveInlining)] public static Number Area(this Triangle2D t) => t.A.X.Multiply(t.C.Y.Subtract(t.B.Y)).Add(t.B.X.Multiply(t.A.Y.Subtract(t.C.Y)).Add(t.C.X.Multiply(t.B.Y.Subtract(t.A.Y)))).Half();
        [MethodImpl(AggressiveInlining)] public static Triangle2D Flip(this Triangle2D t) => (t.C, t.B, t.A);
        [MethodImpl(AggressiveInlining)] public static Point2D Barycentric(this Triangle2D t, Vector2 uv) => t.A.Vector2.Barycentric(t.B, t.C, uv);
        [MethodImpl(AggressiveInlining)] public static Line2D LineA(this Triangle2D t) => (t.A, t.B);
        [MethodImpl(AggressiveInlining)] public static Line2D LineB(this Triangle2D t) => (t.B, t.C);
        [MethodImpl(AggressiveInlining)] public static Line2D LineC(this Triangle2D t) => (t.C, t.A);
        [MethodImpl(AggressiveInlining)] public static Triangle3D To3D(this Triangle2D x) => (x.A.To3D(), x.B.To3D(), x.C.To3D());
        [MethodImpl(AggressiveInlining)] public static Quad2D Flip(this Quad2D q) => (q.D, q.C, q.B, q.A);
        [MethodImpl(AggressiveInlining)] public static Line2D LineA(this Quad2D q) => (q.A, q.B);
        [MethodImpl(AggressiveInlining)] public static Line2D LineB(this Quad2D q) => (q.B, q.C);
        [MethodImpl(AggressiveInlining)] public static Line2D LineC(this Quad2D q) => (q.C, q.D);
        [MethodImpl(AggressiveInlining)] public static Line2D LineD(this Quad2D q) => (q.D, q.A);
        [MethodImpl(AggressiveInlining)] public static Triangle2D TriangleA(this Quad2D q) => (q.A, q.B, q.C);
        [MethodImpl(AggressiveInlining)] public static Triangle2D TriangleB(this Quad2D q) => (q.C, q.D, q.A);
        [MethodImpl(AggressiveInlining)] public static Number Area(this Quad2D q) => q.TriangleA().Area().Add(q.TriangleB().Area());
        [MethodImpl(AggressiveInlining)] public static Quad3D To3D(this Quad2D x) => (x.A.To3D(), x.B.To3D(), x.C.To3D(), x.D.To3D());
        [MethodImpl(AggressiveInlining)] public static Line2D Reverse(this Line2D x) => (x.B, x.A);
        [MethodImpl(AggressiveInlining)] public static Point2D Eval(this Line2D x, Number t) => x.A.Lerp(x.B, t);
        [MethodImpl(AggressiveInlining)] public static Line3D To3D(this Line2D x) => (x.A.To3D(), x.B.To3D());
        [MethodImpl(AggressiveInlining)] public static Number Left(this Rect2D x) => x.Center.X.Subtract(x.Width.Half());
        [MethodImpl(AggressiveInlining)] public static Number Right(this Rect2D x) => x.Left().Add(x.Width);
        [MethodImpl(AggressiveInlining)] public static Number Bottom(this Rect2D x) => x.Center.Y.Subtract(x.Height.Half());
        [MethodImpl(AggressiveInlining)] public static Number Top(this Rect2D x) => x.Bottom().Add(x.Height);
        [MethodImpl(AggressiveInlining)] public static Point2D BottomLeft(this Rect2D x) => (x.Left(), x.Bottom());
        [MethodImpl(AggressiveInlining)] public static Point2D BottomRight(this Rect2D x) => (x.Right(), x.Bottom());
        [MethodImpl(AggressiveInlining)] public static Point2D TopRight(this Rect2D x) => (x.Right(), x.Top());
        [MethodImpl(AggressiveInlining)] public static Point2D TopLeft(this Rect2D x) => (x.Left(), x.Top());
        [MethodImpl(AggressiveInlining)] public static Line3D LineTo(this Point3D a, Point3D b) => (a, b);
        [MethodImpl(AggressiveInlining)] public static Ray3D RayTo(this Point3D a, Point3D b) => (a, b.Subtract(a));
        [MethodImpl(AggressiveInlining)] public static Ray3D RayFrom(this Point3D a, Vector3 dir) => (a, dir);
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point3D> Corners(this Bounds3D x) => Intrinsics.MakeArray(new Point3D(x.Min.X, x.Min.Y, x.Min.Z), new Point3D(x.Max.X, x.Min.Y, x.Min.Z), new Point3D(x.Min.X, x.Max.Y, x.Min.Z), new Point3D(x.Max.X, x.Max.Y, x.Min.Z), new Point3D(x.Min.X, x.Min.Y, x.Max.Z), new Point3D(x.Max.X, x.Min.Y, x.Max.Z), new Point3D(x.Min.X, x.Max.Y, x.Max.Z), new Point3D(x.Max.X, x.Max.Y, x.Max.Z));
        [MethodImpl(AggressiveInlining)] public static Line3D Reverse(this Line3D x) => (x.B, x.A);
        [MethodImpl(AggressiveInlining)] public static Point3D Eval(this Line3D x, Number t) => x.A.Lerp(x.B, t);
        [MethodImpl(AggressiveInlining)] public static Angle Angle(this Ray3D a, Ray3D b) => a.Direction.Angle(b.Direction);
        [MethodImpl(AggressiveInlining)] public static Ray3D Reverse(this Ray3D r) => (r.Origin, r.Direction.Negative);
        [MethodImpl(AggressiveInlining)] public static Number Area(this Triangle3D t) => t.CrossProductA().Magnitude().Half();
        [MethodImpl(AggressiveInlining)] public static Vector3 CrossProductA(this Triangle3D t) => t.B.Subtract(t.A).Cross(t.C.Subtract(t.A));
        [MethodImpl(AggressiveInlining)] public static Triangle3D Flip(this Triangle3D t) => (t.C, t.B, t.A);
        [MethodImpl(AggressiveInlining)] public static Line3D LineA(this Triangle3D t) => (t.A, t.B);
        [MethodImpl(AggressiveInlining)] public static Line3D LineB(this Triangle3D t) => (t.B, t.C);
        [MethodImpl(AggressiveInlining)] public static Line3D LineC(this Triangle3D t) => (t.C, t.A);
        [MethodImpl(AggressiveInlining)] public static Point3D Barycentric(this Triangle3D t, Vector2 uv) => t.A.Vector3.Barycentric(t.B, t.C, uv);
        [MethodImpl(AggressiveInlining)] public static Quad3D Flip(this Quad3D q) => (q.D, q.C, q.B, q.A);
        [MethodImpl(AggressiveInlining)] public static Line3D LineA(this Quad3D q) => (q.A, q.B);
        [MethodImpl(AggressiveInlining)] public static Line3D LineB(this Quad3D q) => (q.B, q.C);
        [MethodImpl(AggressiveInlining)] public static Line3D LineC(this Quad3D q) => (q.C, q.D);
        [MethodImpl(AggressiveInlining)] public static Line3D LineD(this Quad3D q) => (q.D, q.A);
        [MethodImpl(AggressiveInlining)] public static Triangle3D TriangleA(this Quad3D q) => (q.A, q.B, q.C);
        [MethodImpl(AggressiveInlining)] public static Triangle3D TriangleB(this Quad3D q) => (q.C, q.D, q.A);
        [MethodImpl(AggressiveInlining)] public static Number Area(this Quad3D q) => q.TriangleA().Area().Add(q.TriangleB().Area());
        [MethodImpl(AggressiveInlining)] public static PolyLine3D To3D(this PolyLine2D x) => (x.Points.Map((p)  => p.To3D()), x.Closed);
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point2D> CirclePoints(this Integer n) => n.Fractions().Map((x)  => x.Turns().UnitCircle());
        [MethodImpl(AggressiveInlining)] public static Vector3 To3D(this Vector2 x) => (x.X, x.Y, ((Integer)0));
    }
}
