// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class IBoundsLibrary
    {
        [MethodImpl(AggressiveInlining)] public static Point2D Lerp(this Bounds2D x, Number amount) => x.Min.Lerp(x.Max, amount);
        [MethodImpl(AggressiveInlining)] public static Boolean Contains(this Bounds2D x, Point2D value) => value.Between(x.Min, x.Max);
        [MethodImpl(AggressiveInlining)] public static Boolean Contains(this Bounds2D x, Bounds2D y) => x.Contains(y.Min).And(x.Contains(y.Max));
        [MethodImpl(AggressiveInlining)] public static Boolean Overlaps(this Bounds2D x, Bounds2D y) => x.Contains(y.Min).Or(x.Contains(y.Max).Or(y.Contains(x.Min).Or(y.Contains(x.Max))));
        [MethodImpl(AggressiveInlining)] public static Bounds2D Recenter(this Bounds2D x, Point2D c) => (c.Subtract(x.Size.Half()), c.Add(x.Size.Half()));
        [MethodImpl(AggressiveInlining)] public static Bounds2D Clamp(this Bounds2D x, Bounds2D y) => (x.Clamp(y.Min), x.Clamp(y.Max));
        [MethodImpl(AggressiveInlining)] public static Point2D Clamp(this Bounds2D x, Point2D value) => value.Clamp(x.Min, x.Max);
        [MethodImpl(AggressiveInlining)] public static Bounds2D Include(this Bounds2D x, Point2D value) => (x.Min.Min(value), x.Max.Max(value));
        [MethodImpl(AggressiveInlining)] public static Bounds2D Include(this Bounds2D x, Bounds2D y) => x.Include(y.Min).Include(y.Max);
        [MethodImpl(AggressiveInlining)] public static Point3D Lerp(this Bounds3D x, Number amount) => x.Min.Lerp(x.Max, amount);
        [MethodImpl(AggressiveInlining)] public static Boolean Contains(this Bounds3D x, Point3D value) => value.Between(x.Min, x.Max);
        [MethodImpl(AggressiveInlining)] public static Boolean Contains(this Bounds3D x, Bounds3D y) => x.Contains(y.Min).And(x.Contains(y.Max));
        [MethodImpl(AggressiveInlining)] public static Boolean Overlaps(this Bounds3D x, Bounds3D y) => x.Contains(y.Min).Or(x.Contains(y.Max).Or(y.Contains(x.Min).Or(y.Contains(x.Max))));
        [MethodImpl(AggressiveInlining)] public static Bounds3D Recenter(this Bounds3D x, Point3D c) => (c.Subtract(x.Size.Half()), c.Add(x.Size.Half()));
        [MethodImpl(AggressiveInlining)] public static Bounds3D Clamp(this Bounds3D x, Bounds3D y) => (x.Clamp(y.Min), x.Clamp(y.Max));
        [MethodImpl(AggressiveInlining)] public static Point3D Clamp(this Bounds3D x, Point3D value) => value.Clamp(x.Min, x.Max);
        [MethodImpl(AggressiveInlining)] public static Bounds3D Include(this Bounds3D x, Point3D value) => (x.Min.Min(value), x.Max.Max(value));
        [MethodImpl(AggressiveInlining)] public static Bounds3D Include(this Bounds3D x, Bounds3D y) => x.Include(y.Min).Include(y.Max);
    }
}
