// Autogenerated file: DO NOT EDIT
// Created on 2026-07-07 10:58:04 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class IIntervalLibrary
    {
        extension(AnglePair x)
        {
            public Angle Size { [MethodImpl(AggressiveInlining)] get  => x.End.Subtract(x.Start); } 
[MethodImpl(AggressiveInlining)] public Angle Lerp(Number amount) => x.Start.Lerp(x.End, amount);
public AnglePair Reverse { [MethodImpl(AggressiveInlining)] get  => (x.End, x.Start); } 
public Angle Center { [MethodImpl(AggressiveInlining)] get  => x.Lerp(((Number)0.5)); } 
[MethodImpl(AggressiveInlining)] public Boolean Contains(Angle value) => value.Between(x.Start, x.End);
[MethodImpl(AggressiveInlining)] public Boolean Contains(AnglePair y) => x.Contains(y.Start).And(x.Contains(y.End));
[MethodImpl(AggressiveInlining)] public Boolean Overlaps(AnglePair y) => x.Contains(y.Start).Or(x.Contains(y.End).Or(y.Contains(x.Start).Or(y.Contains(x.End))));
[MethodImpl(AggressiveInlining)] public Tuple2<AnglePair, AnglePair> SplitAt(Number t) => (x.Left(t), x.Right(t));
public Tuple2<AnglePair, AnglePair> Split { [MethodImpl(AggressiveInlining)] get  => x.SplitAt(((Number)0.5)); } 
[MethodImpl(AggressiveInlining)] public AnglePair Left(Number t) => (x.Start, x.Lerp(t));
[MethodImpl(AggressiveInlining)] public AnglePair Right(Number t) => (x.Lerp(t), x.End);
[MethodImpl(AggressiveInlining)] public AnglePair MoveTo(Angle v) => (v, v.Add(x.Size));
public AnglePair LeftHalf { [MethodImpl(AggressiveInlining)] get  => x.Left(((Number)0.5)); } 
public AnglePair RightHalf { [MethodImpl(AggressiveInlining)] get  => x.Right(((Number)0.5)); } 
[MethodImpl(AggressiveInlining)] public AnglePair Recenter(Angle c) => (c.Subtract(x.Size.Half), c.Add(x.Size.Half));
[MethodImpl(AggressiveInlining)] public AnglePair Clamp(AnglePair y) => (x.Clamp(y.Start), x.Clamp(y.End));
[MethodImpl(AggressiveInlining)] public Angle Clamp(Angle value) => value.Clamp(x.Start, x.End);
}
        extension(AnglePair interval)
        {
            [MethodImpl(AggressiveInlining)] public IReadOnlyList<Angle> LinearSpace(Integer count){
                var _var53 = interval;
                return count.LinearSpace.Map((x)  => _var53.Lerp(x));
            }

[MethodImpl(AggressiveInlining)] public IReadOnlyList<Angle> LinearSpaceExclusive(Integer count){
                var _var54 = interval;
                return count.LinearSpaceExclusive.Map((x)  => _var54.Lerp(x));
            }

[MethodImpl(AggressiveInlining)] public AnglePair Subdivide(Number start, Number end) => (interval.Lerp(start), interval.Lerp(end));
[MethodImpl(AggressiveInlining)] public AnglePair Subdivide(NumberInterval subInterval) => interval.Subdivide(subInterval.Start, subInterval.End);
[MethodImpl(AggressiveInlining)] public IReadOnlyList<AnglePair> Subdivide(Integer count){
                var _var55 = interval;
                return count.Intervals.Map((i)  => _var55.Subdivide(i));
            }

}
        extension(NumberInterval x)
        {
            public Number Size { [MethodImpl(AggressiveInlining)] get  => x.End.Subtract(x.Start); } 
[MethodImpl(AggressiveInlining)] public Number Lerp(Number amount) => x.Start.Lerp(x.End, amount);
public NumberInterval Reverse { [MethodImpl(AggressiveInlining)] get  => (x.End, x.Start); } 
public Number Center { [MethodImpl(AggressiveInlining)] get  => x.Lerp(((Number)0.5)); } 
[MethodImpl(AggressiveInlining)] public Boolean Contains(Number value) => value.Between(x.Start, x.End);
[MethodImpl(AggressiveInlining)] public Boolean Contains(NumberInterval y) => x.Contains(y.Start).And(x.Contains(y.End));
[MethodImpl(AggressiveInlining)] public Boolean Overlaps(NumberInterval y) => x.Contains(y.Start).Or(x.Contains(y.End).Or(y.Contains(x.Start).Or(y.Contains(x.End))));
[MethodImpl(AggressiveInlining)] public Tuple2<NumberInterval, NumberInterval> SplitAt(Number t) => (x.Left(t), x.Right(t));
public Tuple2<NumberInterval, NumberInterval> Split { [MethodImpl(AggressiveInlining)] get  => x.SplitAt(((Number)0.5)); } 
[MethodImpl(AggressiveInlining)] public NumberInterval Left(Number t) => (x.Start, x.Lerp(t));
[MethodImpl(AggressiveInlining)] public NumberInterval Right(Number t) => (x.Lerp(t), x.End);
[MethodImpl(AggressiveInlining)] public NumberInterval MoveTo(Number v) => (v, v.Add(x.Size));
public NumberInterval LeftHalf { [MethodImpl(AggressiveInlining)] get  => x.Left(((Number)0.5)); } 
public NumberInterval RightHalf { [MethodImpl(AggressiveInlining)] get  => x.Right(((Number)0.5)); } 
[MethodImpl(AggressiveInlining)] public NumberInterval Recenter(Number c) => (c.Subtract(x.Size.Half), c.Add(x.Size.Half));
[MethodImpl(AggressiveInlining)] public NumberInterval Clamp(NumberInterval y) => (x.Clamp(y.Start), x.Clamp(y.End));
[MethodImpl(AggressiveInlining)] public Number Clamp(Number value) => value.Clamp(x.Start, x.End);
}
        extension(NumberInterval interval)
        {
            [MethodImpl(AggressiveInlining)] public IReadOnlyList<Number> LinearSpace(Integer count){
                var _var56 = interval;
                return count.LinearSpace.Map((x)  => _var56.Lerp(x));
            }

[MethodImpl(AggressiveInlining)] public IReadOnlyList<Number> LinearSpaceExclusive(Integer count){
                var _var57 = interval;
                return count.LinearSpaceExclusive.Map((x)  => _var57.Lerp(x));
            }

[MethodImpl(AggressiveInlining)] public NumberInterval Subdivide(Number start, Number end) => (interval.Lerp(start), interval.Lerp(end));
[MethodImpl(AggressiveInlining)] public NumberInterval Subdivide(NumberInterval subInterval) => interval.Subdivide(subInterval.Start, subInterval.End);
[MethodImpl(AggressiveInlining)] public IReadOnlyList<NumberInterval> Subdivide(Integer count){
                var _var58 = interval;
                return count.Intervals.Map((i)  => _var58.Subdivide(i));
            }

}
        extension(Line2D x)
        {
            public Point2D Size { [MethodImpl(AggressiveInlining)] get  => x.End.Subtract(x.Start); } 
[MethodImpl(AggressiveInlining)] public Point2D Lerp(Number amount) => x.Start.Lerp(x.End, amount);
[MethodImpl(AggressiveInlining)] public Boolean Contains(Point2D value) => value.Between(x.Start, x.End);
[MethodImpl(AggressiveInlining)] public Boolean Contains(Line2D y) => x.Contains(y.Start).And(x.Contains(y.End));
[MethodImpl(AggressiveInlining)] public Boolean Overlaps(Line2D y) => x.Contains(y.Start).Or(x.Contains(y.End).Or(y.Contains(x.Start).Or(y.Contains(x.End))));
[MethodImpl(AggressiveInlining)] public Tuple2<Line2D, Line2D> SplitAt(Number t) => (x.Left(t), x.Right(t));
public Tuple2<Line2D, Line2D> Split { [MethodImpl(AggressiveInlining)] get  => x.SplitAt(((Number)0.5)); } 
[MethodImpl(AggressiveInlining)] public Line2D Left(Number t) => (x.Start, x.Lerp(t));
[MethodImpl(AggressiveInlining)] public Line2D Right(Number t) => (x.Lerp(t), x.End);
[MethodImpl(AggressiveInlining)] public Line2D MoveTo(Point2D v) => (v, v.Add(x.Size));
public Line2D LeftHalf { [MethodImpl(AggressiveInlining)] get  => x.Left(((Number)0.5)); } 
public Line2D RightHalf { [MethodImpl(AggressiveInlining)] get  => x.Right(((Number)0.5)); } 
[MethodImpl(AggressiveInlining)] public Line2D Recenter(Point2D c) => (c.Subtract(x.Size.Half), c.Add(x.Size.Half));
[MethodImpl(AggressiveInlining)] public Line2D Clamp(Line2D y) => (x.Clamp(y.Start), x.Clamp(y.End));
[MethodImpl(AggressiveInlining)] public Point2D Clamp(Point2D value) => value.Clamp(x.Start, x.End);
}
        extension(Line2D interval)
        {
            [MethodImpl(AggressiveInlining)] public IReadOnlyList<Point2D> LinearSpace(Integer count){
                var _var59 = interval;
                return count.LinearSpace.Map((x)  => _var59.Lerp(x));
            }

[MethodImpl(AggressiveInlining)] public IReadOnlyList<Point2D> LinearSpaceExclusive(Integer count){
                var _var60 = interval;
                return count.LinearSpaceExclusive.Map((x)  => _var60.Lerp(x));
            }

[MethodImpl(AggressiveInlining)] public Line2D Subdivide(Number start, Number end) => (interval.Lerp(start), interval.Lerp(end));
[MethodImpl(AggressiveInlining)] public Line2D Subdivide(NumberInterval subInterval) => interval.Subdivide(subInterval.Start, subInterval.End);
[MethodImpl(AggressiveInlining)] public IReadOnlyList<Line2D> Subdivide(Integer count){
                var _var61 = interval;
                return count.Intervals.Map((i)  => _var61.Subdivide(i));
            }

}
        extension(Line3D x)
        {
            public Point3D Size { [MethodImpl(AggressiveInlining)] get  => x.End.Subtract(x.Start); } 
[MethodImpl(AggressiveInlining)] public Point3D Lerp(Number amount) => x.Start.Lerp(x.End, amount);
[MethodImpl(AggressiveInlining)] public Boolean Contains(Point3D value) => value.Between(x.Start, x.End);
[MethodImpl(AggressiveInlining)] public Boolean Contains(Line3D y) => x.Contains(y.Start).And(x.Contains(y.End));
[MethodImpl(AggressiveInlining)] public Boolean Overlaps(Line3D y) => x.Contains(y.Start).Or(x.Contains(y.End).Or(y.Contains(x.Start).Or(y.Contains(x.End))));
[MethodImpl(AggressiveInlining)] public Tuple2<Line3D, Line3D> SplitAt(Number t) => (x.Left(t), x.Right(t));
public Tuple2<Line3D, Line3D> Split { [MethodImpl(AggressiveInlining)] get  => x.SplitAt(((Number)0.5)); } 
[MethodImpl(AggressiveInlining)] public Line3D Left(Number t) => (x.Start, x.Lerp(t));
[MethodImpl(AggressiveInlining)] public Line3D Right(Number t) => (x.Lerp(t), x.End);
[MethodImpl(AggressiveInlining)] public Line3D MoveTo(Point3D v) => (v, v.Add(x.Size));
public Line3D LeftHalf { [MethodImpl(AggressiveInlining)] get  => x.Left(((Number)0.5)); } 
public Line3D RightHalf { [MethodImpl(AggressiveInlining)] get  => x.Right(((Number)0.5)); } 
[MethodImpl(AggressiveInlining)] public Line3D Recenter(Point3D c) => (c.Subtract(x.Size.Half), c.Add(x.Size.Half));
[MethodImpl(AggressiveInlining)] public Line3D Clamp(Line3D y) => (x.Clamp(y.Start), x.Clamp(y.End));
[MethodImpl(AggressiveInlining)] public Point3D Clamp(Point3D value) => value.Clamp(x.Start, x.End);
}
        extension(Line3D interval)
        {
            [MethodImpl(AggressiveInlining)] public IReadOnlyList<Point3D> LinearSpace(Integer count){
                var _var62 = interval;
                return count.LinearSpace.Map((x)  => _var62.Lerp(x));
            }

[MethodImpl(AggressiveInlining)] public IReadOnlyList<Point3D> LinearSpaceExclusive(Integer count){
                var _var63 = interval;
                return count.LinearSpaceExclusive.Map((x)  => _var63.Lerp(x));
            }

[MethodImpl(AggressiveInlining)] public Line3D Subdivide(Number start, Number end) => (interval.Lerp(start), interval.Lerp(end));
[MethodImpl(AggressiveInlining)] public Line3D Subdivide(NumberInterval subInterval) => interval.Subdivide(subInterval.Start, subInterval.End);
[MethodImpl(AggressiveInlining)] public IReadOnlyList<Line3D> Subdivide(Integer count){
                var _var64 = interval;
                return count.Intervals.Map((i)  => _var64.Subdivide(i));
            }

}
        extension(Integer count)
        {
            public IReadOnlyList<Number> LinearSpace { [MethodImpl(AggressiveInlining)] get  => count.Fractions; } 
public IReadOnlyList<Number> LinearSpaceExclusive { [MethodImpl(AggressiveInlining)] get  => count.FractionsExclusive; } 
public IReadOnlyList<NumberInterval> Intervals { [MethodImpl(AggressiveInlining)] get  => count.Add(((Integer)1)).LinearSpace.WithNext((a, b)  => new NumberInterval(a, b), ((Boolean)false)); } 
}
    }
}
