// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 11:45:44 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class Integers
    {
        [MethodImpl(AggressiveInlining)] public static Integer PlusOne(this Integer x) => x.Add(((Integer)1));
        [MethodImpl(AggressiveInlining)] public static Integer MinusOne(this Integer x) => x.Subtract(((Integer)1));
        [MethodImpl(AggressiveInlining)] public static Integer FromOne(this Integer x) => ((Integer)1).Subtract(x);
        [MethodImpl(AggressiveInlining)] public static Number FloatDivision(this Integer x, Integer y) => x.Number.Divide(y.Number);
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Number> Fractions(this Integer x){
            var _var112 = x;
            return x.Range.Map((i)  => i.FloatDivision(_var112.Subtract(((Integer)1))));
        }

        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Number> FractionsExclusive(this Integer x){
            var _var113 = x;
            return x.Range.Map((i)  => i.FloatDivision(_var113));
        }

    }
}
