// Autogenerated file: DO NOT EDIT
// Created on 2026-07-08 10:16:45 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class Vectors
    {
        [MethodImpl(AggressiveInlining)] public static Vector2 XVector2(this Number n) => (n, ((Number)0));
        [MethodImpl(AggressiveInlining)] public static Vector2 YVector2(this Number n) => (((Number)0), n);
        [MethodImpl(AggressiveInlining)] public static Vector3 XVector3(this Number n) => (n, ((Number)0), ((Number)0));
        [MethodImpl(AggressiveInlining)] public static Vector3 YVector3(this Number n) => (((Number)0), n, ((Number)0));
        [MethodImpl(AggressiveInlining)] public static Vector3 ZVector3(this Number n) => (((Number)0), ((Number)0), n);
        [MethodImpl(AggressiveInlining)] public static Vector4 XVector4(this Number n) => (n, ((Number)0), ((Number)0), ((Number)0));
        [MethodImpl(AggressiveInlining)] public static Vector4 YVector4(this Number n) => (((Number)0), n, ((Number)0), ((Number)0));
        [MethodImpl(AggressiveInlining)] public static Vector4 ZVector4(this Number n) => (((Number)0), ((Number)0), n, ((Number)0));
        [MethodImpl(AggressiveInlining)] public static Vector4 WVector4(this Number n) => (((Number)0), ((Number)0), ((Number)0), n);
        [MethodImpl(AggressiveInlining)] public static Vector3 ToVector3(this Vector2 v, Number z) => (v.X, v.Y, z);
        [MethodImpl(AggressiveInlining)] public static Vector4 ToVector4(this Vector2 v, Number z, Number w) => (v.X, v.Y, z, w);
        [MethodImpl(AggressiveInlining)] public static Vector2 Project(this Vector2 v, Vector2 other) => other.Multiply(v.Dot(other));
        [MethodImpl(AggressiveInlining)] public static Angle Angle(this Vector2 a, Vector2 b) => a.Dot(b).Divide(a.Magnitude().Multiply(b.Magnitude())).Acos;
        [MethodImpl(AggressiveInlining)] public static Boolean IsParallel(this Vector2 a, Vector2 b) => a.Dot(b).Abs.GreaterThanOrEquals(((Number)1).Subtract(Constants.Epsilon));
        [MethodImpl(AggressiveInlining)] public static Vector2 PlusOne(this Vector2 x) => x.Add(Ara3D.Geometry.Vector2.One);
        [MethodImpl(AggressiveInlining)] public static Vector2 MinusOne(this Vector2 x) => x.Subtract(Ara3D.Geometry.Vector2.One);
        [MethodImpl(AggressiveInlining)] public static Vector2 FromOne(this Vector2 x) => x.Add(Ara3D.Geometry.Vector2.One).Negative;
        [MethodImpl(AggressiveInlining)] public static Vector4 ToVector4(this Vector3 v, Number w) => (v.X, v.Y, v.Z, w);
        [MethodImpl(AggressiveInlining)] public static Vector3 XZY(this Vector3 v) => (v.X, v.Z, v.Y);
        [MethodImpl(AggressiveInlining)] public static Vector3 YXZ(this Vector3 v) => (v.Y, v.X, v.Z);
        [MethodImpl(AggressiveInlining)] public static Vector3 YZX(this Vector3 v) => (v.Y, v.Z, v.X);
        [MethodImpl(AggressiveInlining)] public static Vector3 ZXY(this Vector3 v) => (v.Z, v.X, v.Y);
        [MethodImpl(AggressiveInlining)] public static Vector3 ZYX(this Vector3 v) => (v.Z, v.Y, v.X);
        [MethodImpl(AggressiveInlining)] public static Vector2 XY(this Vector3 v) => (v.X, v.Y);
        [MethodImpl(AggressiveInlining)] public static Vector2 YX(this Vector3 v) => (v.Y, v.X);
        [MethodImpl(AggressiveInlining)] public static Vector2 XZ(this Vector3 v) => (v.X, v.Z);
        [MethodImpl(AggressiveInlining)] public static Vector2 ZX(this Vector3 v) => (v.Z, v.X);
        [MethodImpl(AggressiveInlining)] public static Vector2 YZ(this Vector3 v) => (v.Y, v.Z);
        [MethodImpl(AggressiveInlining)] public static Vector2 ZY(this Vector3 v) => (v.Z, v.Y);
        [MethodImpl(AggressiveInlining)] public static Vector2 XX(this Vector3 v) => (v.X, v.X);
        [MethodImpl(AggressiveInlining)] public static Vector2 YY(this Vector3 v) => (v.Y, v.Y);
        [MethodImpl(AggressiveInlining)] public static Vector2 ZZ(this Vector3 v) => (v.Z, v.Z);
        [MethodImpl(AggressiveInlining)] public static Vector3 Project(this Vector3 v, Plane p) => v.Subtract(p.Normal.Multiply(p.Normal.Dot(v)));
        [MethodImpl(AggressiveInlining)] public static Number MixedProduct(this Vector3 a, Vector3 b, Vector3 c) => a.Cross(b).Dot(c);
        [MethodImpl(AggressiveInlining)] public static Vector2 To2D(this Vector3 v) => (v.X, v.Y);
        [MethodImpl(AggressiveInlining)] public static Vector3 Project(this Vector3 v, Vector3 other) => other.Multiply(v.Dot(other));
        [MethodImpl(AggressiveInlining)] public static Angle Angle(this Vector3 a, Vector3 b) => a.Dot(b).Divide(a.Magnitude().Multiply(b.Magnitude())).Acos;
        [MethodImpl(AggressiveInlining)] public static Boolean IsParallel(this Vector3 a, Vector3 b) => a.Dot(b).Abs.GreaterThanOrEquals(((Number)1).Subtract(Constants.Epsilon));
        [MethodImpl(AggressiveInlining)] public static Vector3 PlusOne(this Vector3 x) => x.Add(Ara3D.Geometry.Vector3.One);
        [MethodImpl(AggressiveInlining)] public static Vector3 MinusOne(this Vector3 x) => x.Subtract(Ara3D.Geometry.Vector3.One);
        [MethodImpl(AggressiveInlining)] public static Vector3 FromOne(this Vector3 x) => x.Add(Ara3D.Geometry.Vector3.One).Negative;
        [MethodImpl(AggressiveInlining)] public static Vector3 XYZ(this Vector4 v) => (v.X, v.Y, v.Z);
        [MethodImpl(AggressiveInlining)] public static Vector8 Vector8(this Vector4 v1, Vector4 v2) => (v1.X, v1.Y, v1.Z, v1.W, v2.X, v2.Y, v2.Z, v2.W);
        [MethodImpl(AggressiveInlining)] public static Vector4 Reflect(this Vector4 v, Vector4 normal) => v.Subtract(normal.Multiply(v.Dot(normal).Multiply(((Number)2))));
        [MethodImpl(AggressiveInlining)] public static Vector4 Project(this Vector4 v, Vector4 other) => other.Multiply(v.Dot(other));
        [MethodImpl(AggressiveInlining)] public static Angle Angle(this Vector4 a, Vector4 b) => a.Dot(b).Divide(a.Magnitude().Multiply(b.Magnitude())).Acos;
        [MethodImpl(AggressiveInlining)] public static Boolean IsParallel(this Vector4 a, Vector4 b) => a.Dot(b).Abs.GreaterThanOrEquals(((Number)1).Subtract(Constants.Epsilon));
        [MethodImpl(AggressiveInlining)] public static Vector4 PlusOne(this Vector4 x) => x.Add(Ara3D.Geometry.Vector4.One);
        [MethodImpl(AggressiveInlining)] public static Vector4 MinusOne(this Vector4 x) => x.Subtract(Ara3D.Geometry.Vector4.One);
        [MethodImpl(AggressiveInlining)] public static Vector4 FromOne(this Vector4 x) => x.Add(Ara3D.Geometry.Vector4.One).Negative;
        [MethodImpl(AggressiveInlining)] public static Vector8 Reflect(this Vector8 v, Vector8 normal) => v.Subtract(normal.Multiply(v.Dot(normal).Multiply(((Number)2))));
        [MethodImpl(AggressiveInlining)] public static Vector8 Project(this Vector8 v, Vector8 other) => other.Multiply(v.Dot(other));
        [MethodImpl(AggressiveInlining)] public static Number Distance(this Vector8 a, Vector8 b) => b.Subtract(a).Magnitude();
        [MethodImpl(AggressiveInlining)] public static Number DistanceSquared(this Vector8 a, Vector8 b) => b.Subtract(a).MagnitudeSquared();
        [MethodImpl(AggressiveInlining)] public static Angle Angle(this Vector8 a, Vector8 b) => a.Dot(b).Divide(a.Magnitude().Multiply(b.Magnitude())).Acos;
        [MethodImpl(AggressiveInlining)] public static Boolean IsParallel(this Vector8 a, Vector8 b) => a.Dot(b).Abs.GreaterThanOrEquals(((Number)1).Subtract(Constants.Epsilon));
        [MethodImpl(AggressiveInlining)] public static Vector8 PlusOne(this Vector8 x) => x.Add(Ara3D.Geometry.Vector8.One);
        [MethodImpl(AggressiveInlining)] public static Vector8 MinusOne(this Vector8 x) => x.Subtract(Ara3D.Geometry.Vector8.One);
        [MethodImpl(AggressiveInlining)] public static Vector8 FromOne(this Vector8 x) => x.Add(Ara3D.Geometry.Vector8.One).Negative;
        [MethodImpl(AggressiveInlining)] public static Vector4 Column1(this Matrix4x4 m) => (m.M11, m.M21, m.M31, m.M41);
        [MethodImpl(AggressiveInlining)] public static Vector4 Column2(this Matrix4x4 m) => (m.M12, m.M22, m.M32, m.M42);
        [MethodImpl(AggressiveInlining)] public static Vector4 Column3(this Matrix4x4 m) => (m.M13, m.M23, m.M33, m.M43);
        [MethodImpl(AggressiveInlining)] public static Vector4 Column4(this Matrix4x4 m) => (m.M14, m.M24, m.M34, m.M44);
        [MethodImpl(AggressiveInlining)] public static Vector3 Transform(this Matrix4x4 m, Vector3 v) => v.Transform(m);
        [MethodImpl(AggressiveInlining)] public static Vector3 TransformNormal(this Matrix4x4 m, Vector3 v) => v.TransformNormal(m);
        [MethodImpl(AggressiveInlining)] public static Vector3 Transform(this Quaternion q, Vector3 v) => v.Transform(q);
    }
}
