// Autogenerated file: DO NOT EDIT
// Created on 2026-07-13 12:58:29 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    public static class Geometry
    {
        [MethodImpl(AggressiveInlining)] public static Point3D Deform(this Point3D v, System.Func<Point3D, Point3D> f) => f.Invoke(v);
        [MethodImpl(AggressiveInlining)] public static Bounds3D Include(this Bounds3D x, Point3D p){
            var _s3a = x.Min.Components();
            var _s3b = p.Components();
            var _n3 = System.Math.Min(_s3a.Count, _s3b.Count);
            var _lp3 = new float[_n3];
            for (var _i3 = 0; _i3 < _n3; _i3++)
            {
                var a1_6 = _s3a[_i3];
                var b1_7 = _s3b[_i3];
                _lp3[_i3] = a1_6.LessThan(b1_7) ? a1_6 : b1_7;
            }
            var _s4a = x.Max.Components();
            var _s4b = p.Components();
            var _n4 = System.Math.Min(_s4a.Count, _s4b.Count);
            var _lp4 = new float[_n4];
            for (var _i4 = 0; _i4 < _n4; _i4++)
            {
                var a1_8 = _s4a[_i4];
                var b1_9 = _s4b[_i4];
                _lp4[_i4] = a1_8.GreaterThan(b1_9) ? a1_8 : b1_9;
            }
            return (Point3D.CreateFromComponents(_lp3), Point3D.CreateFromComponents(_lp4));
        }

        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Point3D> Corners(this Bounds3D x) => Intrinsics.MakeArray<Point3D>(new Point3D(x.Min.X, x.Min.Y, x.Min.Z), new Point3D(x.Max.X, x.Min.Y, x.Min.Z), new Point3D(x.Min.X, x.Max.Y, x.Min.Z), new Point3D(x.Max.X, x.Max.Y, x.Min.Z), new Point3D(x.Min.X, x.Min.Y, x.Max.Z), new Point3D(x.Max.X, x.Min.Y, x.Max.Z), new Point3D(x.Min.X, x.Max.Y, x.Max.Z), new Point3D(x.Max.X, x.Max.Y, x.Max.Z));
        [MethodImpl(AggressiveInlining)] public static Bounds3D Deform(this Bounds3D x, System.Func<Point3D, Point3D> f) => Intrinsics.MakeArray<Point3D>(f.Invoke(new Point3D(x.Min.X, x.Min.Y, x.Min.Z)), f.Invoke(new Point3D(x.Max.X, x.Min.Y, x.Min.Z)), f.Invoke(new Point3D(x.Min.X, x.Max.Y, x.Min.Z)), f.Invoke(new Point3D(x.Max.X, x.Max.Y, x.Min.Z)), f.Invoke(new Point3D(x.Min.X, x.Min.Y, x.Max.Z)), f.Invoke(new Point3D(x.Max.X, x.Min.Y, x.Max.Z)), f.Invoke(new Point3D(x.Min.X, x.Max.Y, x.Max.Z)), f.Invoke(new Point3D(x.Max.X, x.Max.Y, x.Max.Z))).Bounds();
        [MethodImpl(AggressiveInlining)] public static Point3D Eval(this Line3D x, float t) => new Ara3D.Geometry.Point3D(x.A.X.Multiply(1f.Subtract(t)).Add(x.B.X.Multiply(t)), x.A.Y.Multiply(1f.Subtract(t)).Add(x.B.Y.Multiply(t)), x.A.Z.Multiply(1f.Subtract(t)).Add(x.B.Z.Multiply(t)));
        [MethodImpl(AggressiveInlining)] public static Line3D Deform(this Line3D x, System.Func<Point3D, Point3D> f) => (f.Invoke(x.A), f.Invoke(x.B));
    }
}
