<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Ara3D.Geometry</RootNamespace>
    <NoWarn>$(NoWarn);CS0108;CS0114;CS0660;CS0661;CS1591;CS1701</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Plato.Intrinsics.V3\**\*.cs" Link="Intrinsics\%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\ara3d-sdk\src\Ara3D.Collections\Ara3D.Collections.csproj" />
    <ProjectReference Include="..\..\..\ara3d-sdk\src\Ara3D.Memory\Ara3D.Memory.csproj" />
    <ProjectReference Include="..\..\..\ara3d-sdk\src\Ara3D.Utils\Ara3D.Utils.csproj" />
  </ItemGroup>
</Project>
