// DO NOT EDIT: Autogenerated file created on 2024-01-11 7:34:18 PM. 

using System;
using System.Collections.Generic;
using System.Linq;
using Parakeet;
using Parakeet.CST;
using Parakeet.Grammars;

namespace Plato.Parser
{
    public class CstNodeFactory
    {
        public static PlatoGrammar Grammar = new PlatoGrammar();
        public Dictionary<CstNode, ParserTreeNode> Lookup { get;} = new Dictionary<CstNode, ParserTreeNode>();
        public CstNode Create(ParserTreeNode node)
        {
            var r = InternalCreate(node);
            Lookup.Add(r, node);
            return r;
        }
        public CstNode InternalCreate(ParserTreeNode node)
        {
            switch (node.Type)
            {
                case "CastExpression": return new CstCastExpression(Enumerable.ToArray(node.Children.Select(Create)));
                case "PrefixOperator": return new CstPrefixOperator(node.Contents);
                case "Indexer": return new CstIndexer(Enumerable.ToArray(node.Children.Select(Create)));
                case "PostfixOperator": return new CstPostfixOperator(Enumerable.ToArray(node.Children.Select(Create)));
                case "Identifier": return new CstIdentifier(node.Contents);
                case "BinaryOperation": return new CstBinaryOperation(Enumerable.ToArray(node.Children.Select(Create)));
                case "TernaryOperation": return new CstTernaryOperation(Enumerable.ToArray(node.Children.Select(Create)));
                case "ParenthesizedExpression": return new CstParenthesizedExpression(Enumerable.ToArray(node.Children.Select(Create)));
                case "ThrowExpression": return new CstThrowExpression(Enumerable.ToArray(node.Children.Select(Create)));
                case "LambdaParameter": return new CstLambdaParameter(Enumerable.ToArray(node.Children.Select(Create)));
                case "LambdaParameters": return new CstLambdaParameters(Enumerable.ToArray(node.Children.Select(Create)));
                case "LambdaBody": return new CstLambdaBody(Enumerable.ToArray(node.Children.Select(Create)));
                case "LambdaExpr": return new CstLambdaExpr(Enumerable.ToArray(node.Children.Select(Create)));
                case "MemberAccess": return new CstMemberAccess(Enumerable.ToArray(node.Children.Select(Create)));
                case "ConditionalMemberAccess": return new CstConditionalMemberAccess(Enumerable.ToArray(node.Children.Select(Create)));
                case "TypeOf": return new CstTypeOf(Enumerable.ToArray(node.Children.Select(Create)));
                case "NameOf": return new CstNameOf(Enumerable.ToArray(node.Children.Select(Create)));
                case "Default": return new CstDefault(Enumerable.ToArray(node.Children.Select(Create)));
                case "InitializerClause": return new CstInitializerClause(Enumerable.ToArray(node.Children.Select(Create)));
                case "Initializer": return new CstInitializer(Enumerable.ToArray(node.Children.Select(Create)));
                case "ArraySizeSpecifier": return new CstArraySizeSpecifier(Enumerable.ToArray(node.Children.Select(Create)));
                case "NewOperation": return new CstNewOperation(Enumerable.ToArray(node.Children.Select(Create)));
                case "IsOperation": return new CstIsOperation(Enumerable.ToArray(node.Children.Select(Create)));
                case "AsOperation": return new CstAsOperation(Enumerable.ToArray(node.Children.Select(Create)));
                case "StringInterpolationContent": return new CstStringInterpolationContent(Enumerable.ToArray(node.Children.Select(Create)));
                case "StringInterpolation": return new CstStringInterpolation(Enumerable.ToArray(node.Children.Select(Create)));
                case "FunctionArgKeyword": return new CstFunctionArgKeyword(node.Contents);
                case "FunctionArg": return new CstFunctionArg(Enumerable.ToArray(node.Children.Select(Create)));
                case "FunctionArgs": return new CstFunctionArgs(Enumerable.ToArray(node.Children.Select(Create)));
                case "LeafExpression": return new CstLeafExpression(Enumerable.ToArray(node.Children.Select(Create)));
                case "Expression": return new CstExpression(Enumerable.ToArray(node.Children.Select(Create)));
                case "ExpressionStatement": return new CstExpressionStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "ElseClause": return new CstElseClause(Enumerable.ToArray(node.Children.Select(Create)));
                case "IfStatement": return new CstIfStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "WhileStatement": return new CstWhileStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "DoWhileStatement": return new CstDoWhileStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "ReturnStatement": return new CstReturnStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "BreakStatement": return new CstBreakStatement(node.Contents);
                case "YieldStatement": return new CstYieldStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "YieldReturn": return new CstYieldReturn(Enumerable.ToArray(node.Children.Select(Create)));
                case "YieldBreak": return new CstYieldBreak(node.Contents);
                case "ContinueStatement": return new CstContinueStatement(node.Contents);
                case "CompoundStatement": return new CstCompoundStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "CatchClause": return new CstCatchClause(Enumerable.ToArray(node.Children.Select(Create)));
                case "FinallyClause": return new CstFinallyClause(Enumerable.ToArray(node.Children.Select(Create)));
                case "CaseClause": return new CstCaseClause(Enumerable.ToArray(node.Children.Select(Create)));
                case "SwitchStatement": return new CstSwitchStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "TryStatement": return new CstTryStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "ForEachStatement": return new CstForEachStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "FunctionDeclStatement": return new CstFunctionDeclStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "ForLoopInit": return new CstForLoopInit(Enumerable.ToArray(node.Children.Select(Create)));
                case "ForLoopInvariant": return new CstForLoopInvariant(Enumerable.ToArray(node.Children.Select(Create)));
                case "ForLoopVariant": return new CstForLoopVariant(Enumerable.ToArray(node.Children.Select(Create)));
                case "ForStatement": return new CstForStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "ArrayInitializationValue": return new CstArrayInitializationValue(Enumerable.ToArray(node.Children.Select(Create)));
                case "InitializationValue": return new CstInitializationValue(Enumerable.ToArray(node.Children.Select(Create)));
                case "Initialization": return new CstInitialization(Enumerable.ToArray(node.Children.Select(Create)));
                case "VarWithInitialization": return new CstVarWithInitialization(Enumerable.ToArray(node.Children.Select(Create)));
                case "VarDecl": return new CstVarDecl(Enumerable.ToArray(node.Children.Select(Create)));
                case "VarDeclStatement": return new CstVarDeclStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "Statement": return new CstStatement(Enumerable.ToArray(node.Children.Select(Create)));
                case "QualifiedIdentifier": return new CstQualifiedIdentifier(Enumerable.ToArray(node.Children.Select(Create)));
                case "TypeParameter": return new CstTypeParameter(Enumerable.ToArray(node.Children.Select(Create)));
                case "TypeParameterList": return new CstTypeParameterList(Enumerable.ToArray(node.Children.Select(Create)));
                case "ImplementsList": return new CstImplementsList(Enumerable.ToArray(node.Children.Select(Create)));
                case "InheritsList": return new CstInheritsList(Enumerable.ToArray(node.Children.Select(Create)));
                case "Constraint": return new CstConstraint(Enumerable.ToArray(node.Children.Select(Create)));
                case "ConstraintList": return new CstConstraintList(Enumerable.ToArray(node.Children.Select(Create)));
                case "Type": return new CstType(Enumerable.ToArray(node.Children.Select(Create)));
                case "Concept": return new CstConcept(Enumerable.ToArray(node.Children.Select(Create)));
                case "Library": return new CstLibrary(Enumerable.ToArray(node.Children.Select(Create)));
                case "TopLevelDeclaration": return new CstTopLevelDeclaration(Enumerable.ToArray(node.Children.Select(Create)));
                case "FunctionParameter": return new CstFunctionParameter(Enumerable.ToArray(node.Children.Select(Create)));
                case "FunctionParameterList": return new CstFunctionParameterList(Enumerable.ToArray(node.Children.Select(Create)));
                case "ExpressionBody": return new CstExpressionBody(Enumerable.ToArray(node.Children.Select(Create)));
                case "FunctionBody": return new CstFunctionBody(Enumerable.ToArray(node.Children.Select(Create)));
                case "TypeAnnotation": return new CstTypeAnnotation(Enumerable.ToArray(node.Children.Select(Create)));
                case "MethodDeclaration": return new CstMethodDeclaration(Enumerable.ToArray(node.Children.Select(Create)));
                case "FieldDeclaration": return new CstFieldDeclaration(Enumerable.ToArray(node.Children.Select(Create)));
                case "MemberDeclaration": return new CstMemberDeclaration(Enumerable.ToArray(node.Children.Select(Create)));
                case "ArrayRankSpecifier": return new CstArrayRankSpecifier(node.Contents);
                case "ArrayRankSpecifiers": return new CstArrayRankSpecifiers(Enumerable.ToArray(node.Children.Select(Create)));
                case "TypeArgList": return new CstTypeArgList(Enumerable.ToArray(node.Children.Select(Create)));
                case "TypeVar": return new CstTypeVar(Enumerable.ToArray(node.Children.Select(Create)));
                case "SimpleTypeExpr": return new CstSimpleTypeExpr(Enumerable.ToArray(node.Children.Select(Create)));
                case "CompoundTypeExpr": return new CstCompoundTypeExpr(Enumerable.ToArray(node.Children.Select(Create)));
                case "CompoundOrSimpleTypeExpr": return new CstCompoundOrSimpleTypeExpr(Enumerable.ToArray(node.Children.Select(Create)));
                case "InnerTypeExpr": return new CstInnerTypeExpr(Enumerable.ToArray(node.Children.Select(Create)));
                case "TypeExpr": return new CstTypeExpr(Enumerable.ToArray(node.Children.Select(Create)));
                case "File": return new CstFile(Enumerable.ToArray(node.Children.Select(Create)));
                case "FloatLiteral": return new CstFloatLiteral(node.Contents);
                case "HexLiteral": return new CstHexLiteral(node.Contents);
                case "BinaryLiteral": return new CstBinaryLiteral(node.Contents);
                case "IntegerLiteral": return new CstIntegerLiteral(node.Contents);
                case "StringLiteral": return new CstStringLiteral(node.Contents);
                case "CharLiteral": return new CstCharLiteral(node.Contents);
                case "BooleanLiteral": return new CstBooleanLiteral(node.Contents);
                case "NullLiteral": return new CstNullLiteral(node.Contents);
                case "Literal": return new CstLiteral(Enumerable.ToArray(node.Children.Select(Create)));
                case "BinaryOperator": return new CstBinaryOperator(node.Contents);
                case "Operator": return new CstOperator(node.Contents);
                case "Separator": return new CstSeparator(Enumerable.ToArray(node.Children.Select(Create)));
                case "Delimiter": return new CstDelimiter(node.Contents);
                case "TypeKeyword": return new CstTypeKeyword(node.Contents);
                case "StatementKeyword": return new CstStatementKeyword(node.Contents);
                case "Unknown": return new CstUnknown(node.Contents);
                case "ParameterName": return new CstParameterName(Enumerable.ToArray(node.Children.Select(Create)));
                case "FunctionName": return new CstFunctionName(Enumerable.ToArray(node.Children.Select(Create)));
                case "FieldName": return new CstFieldName(Enumerable.ToArray(node.Children.Select(Create)));
                case "TypeName": return new CstTypeName(Enumerable.ToArray(node.Children.Select(Create)));
                case "TypeParameterToken": return new CstTypeParameterToken(Enumerable.ToArray(node.Children.Select(Create)));
                case "TypeParametersToken": return new CstTypeParametersToken(Enumerable.ToArray(node.Children.Select(Create)));
                case "Comment": return new CstComment(node.Contents);
                default: throw new Exception($"Unrecognized parse node {node.Type}");
            }
        }
    }
}
