<#
.SYNOPSIS
    Regenerates Ara3D.Csg.Tests\Generated by compiling the production Plato
    standard library (plato-src) merged with csg.plato.

.DESCRIPTION
    Same mechanism and emitter recipe as regen-earcut.ps1: scalar wrappers erased
    to native floats, libraries become classic extension methods, both optimizer
    passes on, no-arg functions emitted as methods. See FINDINGS.md.

.EXAMPLE
    .\regen-csg.ps1          # regenerate only
    .\regen-csg.ps1 -Test    # regenerate + run the test suite
#>
[CmdletBinding()]
param(
    [switch]$Test,
    [string]$Configuration = 'Release'
)

$ErrorActionPreference = 'Stop'

$platoRoot   = Split-Path -Parent $PSScriptRoot
$cliProj     = Join-Path $platoRoot 'Plato.CLI\Plato.CLI.csproj'
$platoSrc    = Join-Path $platoRoot 'plato-src'
$testProj    = Join-Path $PSScriptRoot 'Ara3D.Csg.Tests'
$generated   = Join-Path $testProj 'Generated'
$mergedInput = Join-Path $env:TEMP 'plato-csg\merged-src'

foreach ($p in @($cliProj, $platoSrc, $testProj)) {
    if (-not (Test-Path $p)) { throw "Expected path not found: $p" }
}

Write-Host "== Merging plato-src + csg.plato =="
if (Test-Path $mergedInput) { Remove-Item -Recurse -Force $mergedInput }
New-Item -ItemType Directory -Force $mergedInput | Out-Null
Get-ChildItem $platoSrc -File -Filter '*.plato' | Copy-Item -Destination $mergedInput
Copy-Item (Join-Path $PSScriptRoot 'csg.plato') $mergedInput

Write-Host "== Building Plato.CLI ($Configuration) =="
dotnet build $cliProj -c $Configuration -v minimal --nologo
if ($LASTEXITCODE -ne 0) { throw "dotnet build failed (exit $LASTEXITCODE)" }

$flags = @('--csharp-style=extensions', '--scalar=float', '--optimize', '--optimize-arrays', '--methods')
Write-Host "== Running Plato.CLI ($($flags -join ' ')) =="
if (Test-Path $generated) { Remove-Item -Recurse -Force $generated }
New-Item -ItemType Directory -Force $generated | Out-Null

dotnet run --project $cliProj -c $Configuration --no-build -- $mergedInput $generated @flags
if ($LASTEXITCODE -ne 0) { throw "Plato.CLI failed (exit $LASTEXITCODE)" }

$genCs = Get-ChildItem $generated -File -Filter '*.g.cs'
if ($genCs.Count -lt 100) {
    throw "Generation produced only $($genCs.Count) .g.cs files - compilation likely failed."
}
if (-not (Test-Path (Join-Path $generated 'Csg.g.cs'))) {
    throw "Csg.g.cs was not generated - csg.plato did not compile."
}
Write-Host ("   generated {0} .g.cs files" -f $genCs.Count)

if ($Test) {
    Write-Host "== Running csg tests =="
    dotnet test (Join-Path $testProj 'Ara3D.Csg.Tests.csproj') -c $Configuration -v minimal --nologo
    if ($LASTEXITCODE -ne 0) { throw "Csg tests FAILED (exit $LASTEXITCODE)" }
    Write-Host "Csg tests passed." -ForegroundColor Green
}
exit 0
