#!/usr/bin/env python3
"""Build a design-sketch types/concepts index with heavier generics and merges.

Reads the live stdlib/types-and-concepts.txt and writes a proposed alternate that
collapses 2D/3D twins and repeated families. This does NOT change the stdlib;
it is a vocabulary sketch for review.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "stdlib" / "types-and-concepts.txt"
OUT = ROOT / "docs" / "types-and-concepts-merged.txt"

# Names dropped entirely (replaced by a generic / merged declaration below).
DROP_EXACT = {
    # Dimension twins → parameterized concepts
    "AngularCurve2D",
    "AngularCurve3D",
    "Bounded2D",
    "Bounded3D",
    "BoundedSignedDistanceField2D",
    "BoundedSignedDistanceField3D",
    "Centroid2D",
    "Centroid3D",
    "ClosedCurve2D",
    "ClosedCurve3D",
    "ClosestPointQueryable2D",
    "ClosestPointQueryable3D",
    "ColorField2D",
    "ColorField3D",
    "ComplexField2D",
    "ContainsPoint2D",
    "ContainsPoint3D",
    "Curve2D",
    "Curve3D",
    "Deformable2D",
    "Deformable3D",
    "Deformation2D",
    "Deformation3D",
    "DifferentiableCurve2D",
    "DifferentiableCurve3D",
    "DifferentiableScalarField2D",
    "DifferentiableScalarField3D",
    "DifferentiableVectorField2D",
    "DifferentiableVectorField3D",
    "DirectionField2D",
    "DirectionField3D",
    "ImplicitRegion2D",
    "ImplicitVolume3D",
    "Meshable2D",
    "Meshable3D",
    "NearestNeighborQueryable2D",
    "NearestNeighborQueryable3D",
    "NearestPoint2D",
    "NearestPoint3D",
    "PointSet2D",
    "PointSet3D",
    "RayIntersectable2D",
    "RayIntersectable3D",
    "ScalarField2D",
    "ScalarField3D",
    "SignedDistanceField2D",
    "SignedDistanceField3D",
    "SpatialIndex2D",
    "SpatialIndex3D",
    "SupportMappable2D",
    "SupportMappable3D",
    "TensorField2D",
    "TensorField3D",
    "TimeVaryingScalarField2D",
    "TimeVaryingScalarField3D",
    "TimeVaryingVectorField2D",
    "TimeVaryingVectorField3D",
    "VectorField2D",
    "VectorField3D",
    "PrimitiveCollection3D",
    # Curve / spline / segment / ray / line twins → TPoint families
    "BezierCurve2D",
    "BezierCurve3D",
    "BSplineCurve2D",
    "BSplineCurve3D",
    "CatmullRomCurve2D",
    "CatmullRomCurve3D",
    "CompositeBezier2D",
    "CompositeBezier3D",
    "CubicBezier2D",
    "CubicBezier3D",
    "HermiteCurve2D",
    "HermiteCurve3D",
    "HermiteSpline2D",
    "HermiteSpline3D",
    "LinearSpline2D",
    "LinearSpline3D",
    "NurbsCurve2D",
    "NurbsCurve3D",
    "QuadraticBezier2D",
    "QuadraticBezier3D",
    "RationalBezierCurve2D",
    "RationalBezierCurve3D",
    "TcbSpline2D",
    "TcbSpline3D",
    "LineSegment2D",
    "LineSegment3D",
    "Line2D",
    "Line3D",
    "Ray2D",
    "Ray3D",
    "Polyline2D",
    "Polyline3D",
    "PointCloud2D",
    "PointCloud3D",
    "LineSet2D",
    "LineSet3D",
    "Triangle2D",
    "Triangle3D",
    "Quad2D",
    "Quad3D",
    "Bounds2D",
    "Bounds3D",
    "IntegerBounds2D",
    "IntegerBounds3D",
    "Size2D",
    "Size3D",
    "IntegerSize2D",
    "IntegerSize3D",
    "Direction2D",
    "Direction3D",
    "Frame2D",
    "Frame3D",
    "Pose2D",
    "Pose3D",
    "Transform2D",
    "Transform3D",
    "AffineTransform2D",
    "AffineTransform3D",
    "ProjectiveTransform2D",
    "ProjectiveTransform3D",
    "RayHit2D",
    "RayHit3D",
    "RayQuery2D",
    "RayQuery3D",
    "ClosestPointResult2D",
    "ClosestPointResult3D",
    "IntersectionResult2D",
    "IntersectionResult3D",
    "KNearestQuery2D",
    "KNearestQuery3D",
    "RadiusQuery2D",
    "RadiusQuery3D",
    "OverlapQuery2D",
    "OverlapQuery3D",
    "Capsule2D",
    "Capsule3D",
    # Image family → Image<TPixel> + thin aliases kept as comments in header only
    "Bitmap",
    "FloatImage",
    "GrayscaleImage",
    "BinaryImage",
    "NormalImage",
    # DepthImage / IndexedImage keep extra fields (Near/Far, Palette) — rewritten in place.
    # Noise / sampled-field twins
    "PerlinNoise2D",
    "PerlinNoise3D",
    "SimplexNoise2D",
    "SimplexNoise3D",
    "ValueNoise2D",
    "ValueNoise3D",
    "WhiteNoise2D",
    "WhiteNoise3D",
    "FbmNoise2D",
    "FbmNoise3D",
    "RidgedNoise2D",
    "RidgedNoise3D",
    "TurbulenceNoise2D",
    "TurbulenceNoise3D",
    "DomainWarpNoise2D",
    "DomainWarpNoise3D",
    "GaborNoise2D",
    "GaborNoise3D",
    "CurlNoise2D",
    "CurlNoise3D",
    "WorleyNoise2D",
    "WorleyNoise3D",
    "ConstantScalarField2D",
    "ConstantScalarField3D",
    "ConstantVectorField2D",
    "ConstantVectorField3D",
    "SampledScalarGrid2D",
    "SampledScalarGrid3D",
    "SampledVectorGrid2D",
    "SampledVectorGrid3D",
    "SampledSdf2D",
    "SampledSdf3D",
    "BoundedSdf2D",
    "BoundedSdf3D",
    "FunctionSdf2D",
    "FunctionSdf3D",
    "FunctionRegion2D",
    "FunctionVolume3D",
    "ScalarFunctionField2D",
    "ScalarFunctionField3D",
    "VectorFunctionField2D",
    "VectorFunctionField3D",
    "DensityGrid2D",
    "DensityGrid3D",
    "OccupancyGrid2D",
    "OccupancyGrid3D",
    "BinningGrid2D",
    "BinningGrid3D",
    "Bvh2D",
    "Bvh3D",
    "BvhNode2D",
    "BvhNode3D",
    "KdTree2D",
    "KdTree3D",
    "KdTreeNode2D",
    "KdTreeNode3D",
    "SpatialHashGrid2D",
    "SpatialHashGrid3D",
    "RegularGrid2D",
    "RegularGrid3D",
    "GridCell2D",
    "GridCell3D",
    "GridResampling2D",
    "GridResampling3D",
    "MetaBall2D",
    "MetaBall3D",
    "MetaBallSystem2D",
    "MetaBallSystem3D",
    "MappingDeformation2D",
    "MappingDeformation3D",
    "Shear2D",
    "Shear3D",
    "Taper2D",
    "Taper3D",
    "Twist2D",
    "Twist3D",
    "SampledCurve2D",
    "SampledCurve3D",
    "CurveJet2D",
    "CurveJet3D",
    "FrenetFrame2D",
    "FrenetFrame3D",
    "HomogeneousPoint2D",
    "HomogeneousPoint3D",
    "NormalDistribution2D",
    "NormalDistribution3D",
    "Covariance2D",
    "Covariance3D",
    # Shell / annulus shared shape
    "Annulus",
    "SphericalShell",
    "CylindricalShell",
}

# Concept/type lines to inject (merged vocabulary). Kept in declaration style.
INJECT_CONCEPTS = [
    "concept AngularCurve<TPoint>inherits Curve<TPoint>{Eval(x:Self,angle:Angle):TPoint;}",
    "concept Bounded<TBounds>{Bounds(x:Self):TBounds;}",
    "concept BoundedSignedDistanceField<TPoint,TBounds>inherits SignedDistanceField<TPoint>,Bounded<TBounds>{}",
    "concept Centroid<TPoint>{Centroid(x:Self):TPoint;}",
    "concept ClosedCurve<TPoint>inherits Curve<TPoint>{}",
    "concept ClosestPointQueryable<TPoint,TResult>{ClosestPoint(x:Self,point:TPoint):TResult;}",
    "concept ContainsPoint<TPoint>{Contains(x:Self,point:TPoint):Boolean;}",
    "concept ControlPointCurve<TPoint>inherits Curve<TPoint>{ControlPoints(x:Self):Array<TPoint>;}",
    "concept Deformable<TPoint>{Deform(x:Self,mapping:Function1<TPoint,TPoint>):Self;}",
    "concept Deformation<TPoint>inherits Procedural<TPoint,TPoint>{}",
    "concept DifferentiableCurve<TPoint,TVector>inherits Curve<TPoint>{TangentAt(x:Self,t:Number):TVector;CurvatureAt(x:Self,t:Number):Number;}",
    "concept DifferentiableScalarField<TPoint,TVector>inherits ScalarField<TPoint>{GradientAt(x:Self,point:TPoint):TVector;}",
    "concept DifferentiableVectorField<TPoint,TVector,TMatrix>inherits VectorField<TPoint,TVector>{JacobianAt(x:Self,point:TPoint):TMatrix;DivergenceAt(x:Self,point:TPoint):Number;}",
    "concept Framed<TFrame>{Frame(x:Self):TFrame;}",
    "concept GridField<TPoint,TValue>{Origin(x:Self):TPoint;CellSize(x:Self):Number;}",
    "concept HitResult{Hit(x:Self):Boolean;}",
    "concept ImplicitRegion<TPoint>inherits Procedural<TPoint,Boolean>{}",
    "concept IndexedMesh<TPoint,TFace>inherits Meshable<TriangleMesh3D>{Positions(x:Self):Array<TPoint>;Faces(x:Self):Array<TFace>;}",
    "concept InnerOuterRadii{InnerRadius(x:Self):Number;OuterRadius(x:Self):Number;}",
    "concept Meshable<TMesh>{ToMesh(x:Self):TMesh;}",
    "concept NearestNeighborQueryable<TQuery>{FindNearest(x:Self,query:TQuery):NearestNeighbors;}",
    "concept NearestPoint<TPoint>{ClosestPoint(x:Self,point:TPoint):TPoint;}",
    "concept PointSet<TPoint>inherits Geometry{Points(x:Self):Array<TPoint>;}",
    "concept PrimitiveCollection<TPrimitive>inherits Geometry{Primitives(x:Self):Array<TPrimitive>;}",
    "concept RadialShell inherits InnerOuterRadii,Geometry{}",
    "concept RayIntersectable<TQuery,THit>{Raycast(x:Self,query:TQuery):THit;}",
    "concept SamplePattern2D{Region(x:Self):Bounds<Point2D,Vector2D>;Count(x:Self):Integer;}",
    "concept ScalarField<TPoint>inherits Field<TPoint,Number>{}",
    "concept SegmentRadius<TPoint>{A(x:Self):TPoint;B(x:Self):TPoint;Radius(x:Self):Number;}",
    "concept SignedDistanceField<TPoint>inherits ScalarField<TPoint>{}",
    "concept SpatialIndex<TBounds>{ItemCount(x:Self):Integer;CandidatesInBounds(x:Self,bounds:TBounds):Array<ItemIndex>;}",
    "concept SupportMappable<TPoint,TDirection>{Support(x:Self,direction:TDirection):TPoint;}",
    "concept TimeVaryingField<TPoint,TValue>{EvalAtTime(x:Self,point:TPoint,time:Instant):TValue;}",
    "concept VectorField<TPoint,TVector>inherits Field<TPoint,TVector>{}",
]

INJECT_TYPES = [
    # Core dimension-generic geometry
    "type AffineTransform<TMatrix>implements Value{Matrix:TMatrix;}",
    "type BezierCurve<TPoint>implements ControlPointCurve<TPoint>{ControlPoints:Array<TPoint>;}",
    "type BinningGrid<TBounds,TCounts>implements Value,SpatialIndex<TBounds>{Bounds:TBounds;CellCounts:TCounts;BucketOffsets:Array<Integer>;ItemIndices:Array<ItemIndex>;}",
    "type Bounds<TPoint,TDelta>where TPoint:Difference<TDelta>implements BoundsLike<TPoint,TDelta>{Min:TPoint;Max:TPoint;}",
    "type BoundedSdf<TPoint,TBounds>implements Value,BoundedSignedDistanceField<TPoint,TBounds>{Sdf:FunctionSdf<TPoint>;Bounds:TBounds;}",
    "type BSplineCurve<TPoint>implements ControlPointCurve<TPoint>{ControlPoints:Array<TPoint>;Degree:Integer;Knots:KnotVector;}",
    "type Bvh<TBounds>implements Value,SpatialIndex<TBounds>{Nodes:Array<BvhNode<TBounds>>;PrimitiveIndices:Array<ItemIndex>;}",
    "type BvhNode<TBounds>implements Value{Bounds:TBounds;LeftChild:SpatialNodeIndex;RightChild:SpatialNodeIndex;Primitives:IntegerInterval;}",
    "type Capsule<TPoint>implements Geometry,SegmentRadius<TPoint>,ClosedShape,ConvexShape,Connected{A:TPoint;B:TPoint;Radius:Number;}",
    "type CatmullRomCurve<TPoint>implements Curve<TPoint>{Points:Array<TPoint>;Alpha:Number;Closed:Boolean;}",
    "type ClosestPointResult<TPoint,TId>implements Value,HitResult{Position:TPoint;Distance:Number;Id:TId;Parameter:Number;}",
    "type CompositeBezier<TPoint>implements Curve<TPoint>{Segments:Array<CubicBezier<TPoint>>;}",
    "type ConstantScalarField<TPoint>implements Value,ScalarField<TPoint>{Value:Number;}",
    "type ConstantVectorField<TPoint,TVector>implements Value,VectorField<TPoint,TVector>{Value:TVector;}",
    "type Covariance<T>implements Value{Components:T;}",
    "type CubicBezier<TPoint>implements Curve<TPoint>{P0:TPoint;P1:TPoint;P2:TPoint;P3:TPoint;}",
    "type CurlNoise<TPoint,TVector>implements Value,VectorField<TPoint,TVector>{Seed:Integer;Frequency:Number;}",
    "type CurveJet<TPoint,TVector>implements Value{Parameter:Number;Position:TPoint;FirstDerivative:TVector;SecondDerivative:TVector;}",
    "type DensityGrid<TPoint,TArray>implements Value,GridField<TPoint,Number>{Origin:TPoint;CellSize:Number;Values:TArray;}",
    "type Direction<TVector>implements Value{Vector:TVector;}",
    "type DomainWarpNoise<TPoint>implements Value,ScalarField<TPoint>{Basis:NoiseBasis;Seed:Integer;Frequency:Number;WarpStrength:Number;WarpFrequency:Number;Iterations:Integer;}",
    "type FbmNoise<TPoint>implements Value,ScalarField<TPoint>{Basis:NoiseBasis;Seed:Integer;Frequency:Number;Octaves:Integer;Lacunarity:Number;Gain:Number;}",
    "type Frame<TPoint,TDirection>implements Value{Origin:TPoint;Axes:Array<TDirection>;}",
    "type FrenetFrame<TPoint,TDirection>implements Value{Position:TPoint;Tangent:TDirection;Normal:TDirection;}",
    "type FunctionRegion<TPoint>implements ImplicitRegion<TPoint>{Function:Function1<TPoint,Boolean>;}",
    "type FunctionSdf<TPoint>implements SignedDistanceField<TPoint>{Function:Function1<TPoint,Number>;}",
    "type GaborNoise<TPoint>implements Value,ScalarField<TPoint>{Seed:Integer;Frequency:Number;Bandwidth:Number;Anisotropy:Number;}",
    "type GridCell<TIndex,TBounds>implements Value{CellIndex:TIndex;Bounds:TBounds;}",
    "type GridResampling<TGrid>implements Value{Source:TGrid;Target:TGrid;Scheme:GridSamplingScheme;}",
    "type HermiteCurve<TPoint,TVector>implements Curve<TPoint>{Start:TPoint;StartTangent:TVector;End:TPoint;EndTangent:TVector;}",
    "type HermiteSpline<TPoint,TVector>implements Curve<TPoint>{Points:Array<TPoint>;Tangents:Array<TVector>;Closed:Boolean;}",
    "type HomogeneousPoint<TComponents>implements Value{Components:TComponents;}",
    "type ImageBuffer<TPixel>implements Image{Size:IntegerSize<IntegerVector2>;Pixels:Array<TPixel>;}",
    "type IntegerBounds<TPoint>implements Value{Min:TPoint;Max:TPoint;}",
    "type IntegerSize<TVector>implements Value,Hashable{Extents:TVector;}",
    "type IntersectionResult<TPoint>implements Value,HitResult{Hit:Boolean;Points:Array<TPoint>;}",
    "type Interval<T>implements IntervalLike<T>{Start:T;End:T;}",
    "type KdTree<TPoint,TBounds>implements Value,SpatialIndex<TBounds>,NearestNeighborQueryable<KNearestQuery<TPoint>>{Points:Array<TPoint>;Nodes:Array<KdTreeNode>;PointIndices:Array<ItemIndex>;}",
    "type KdTreeNode implements Value{SplitAxis:Integer;SplitValue:Number;LeftChild:SpatialNodeIndex;RightChild:SpatialNodeIndex;Items:IntegerInterval;}",
    "type KNearestQuery<TPoint>implements Value{Center:TPoint;NeighborCount:Integer;MaxDistance:Number;}",
    "type Line<TPoint,TDirection>implements Geometry,Connected,NearestPoint<TPoint>{Origin:TPoint;Direction:TDirection;}",
    "type LinearSpline<TPoint>implements Curve<TPoint>{Points:Array<TPoint>;Closed:Boolean;}",
    "type LineSegment<TPoint,TDelta>where TPoint:Difference<TDelta>implements Geometry,OpenShape,Connected,Bounded<Bounds<TPoint,TDelta>>,LengthMeasurable,PointSet<TPoint>,Centroid<TPoint>,NearestPoint<TPoint>,Deformable<TPoint>{A:TPoint;B:TPoint;}",
    "type LineSet<TPoint>implements Value,Deformable<TPoint>{Positions:Array<TPoint>;Lines:Array<VertexPair>;}",
    "type MappingDeformation<TPoint>implements Value,Deformation<TPoint>{Mapping:Function1<TPoint,TPoint>;}",
    "type MetaBall<TPoint>implements Value{Center:TPoint;Radius:Number;Strength:Number;}",
    "type MetaBallSystem<TPoint>implements Value,ScalarField<TPoint>{Balls:Array<MetaBall<TPoint>>;Threshold:Number;}",
    "type NormalDistributionND<TMean,TCov>implements Value{Mean:TMean;Covariance:TCov;}",
    "type NurbsCurve<TPoint>implements ControlPointCurve<TPoint>{ControlPoints:Array<TPoint>;Weights:Array<Number>;Degree:Integer;Knots:KnotVector;}",
    "type OccupancyGrid<TPoint,TArray>implements Value,GridField<TPoint,Boolean>{Origin:TPoint;CellSize:Number;Occupied:TArray;}",
    "type OverlapQuery<TBounds>implements Value{Bounds:TBounds;FilterMask:Integer;}",
    "type PerlinNoise<TPoint>implements Value,ScalarField<TPoint>{Seed:Integer;Frequency:Number;}",
    "type PointCloud<TPoint>implements Value,Deformable<TPoint>{Positions:Array<TPoint>;}",
    "type Polyline<TPoint>implements Geometry,Connected,LengthMeasurable,PointSet<TPoint>,Deformable<TPoint>{Points:Array<TPoint>;Closed:Boolean;}",
    "type Pose<TPoint,TOrientation>implements Value,Interpolatable{Position:TPoint;Orientation:TOrientation;}",
    "type ProjectiveTransform<TMatrix>implements Value{Matrix:TMatrix;}",
    "type Quad<TPoint>implements Geometry,Connected,PlanarMeasurable,PointSet<TPoint>,Centroid<TPoint>,Deformable<TPoint>{A:TPoint;B:TPoint;C:TPoint;D:TPoint;}",
    "type QuadraticBezier<TPoint>implements Curve<TPoint>{P0:TPoint;P1:TPoint;P2:TPoint;}",
    "type RadialShellSolid implements RadialShell,ClosedShape,Connected,SpatialMeasurable,Bounded<Bounds<Point3D,Vector3D>>,Centroid<Point3D>,ContainsPoint<Point3D>{Center:Point3D;InnerRadius:Number;OuterRadius:Number;}",
    "type RadialShellPlanar implements RadialShell,ClosedShape,Connected,PlanarMeasurable,Bounded<Bounds<Point2D,Vector2D>>,Centroid<Point2D>,ContainsPoint<Point2D>{Center:Point2D;InnerRadius:Number;OuterRadius:Number;}",
    "type RadiusQuery<TPoint>implements Value{Center:TPoint;Radius:Number;MaxCount:Integer;}",
    "type RationalBezierCurve<TPoint>implements ControlPointCurve<TPoint>{ControlPoints:Array<TPoint>;Weights:Array<Number>;}",
    "type Ray<TPoint,TDirection>implements Geometry,Connected,NearestPoint<TPoint>{Origin:TPoint;Direction:TDirection;}",
    "type RayHit<TPoint,TDirection,TId>implements Value,HitResult{Hit:Boolean;Distance:Number;Position:TPoint;Normal:TDirection;Id:TId;}",
    "type RayQuery<TPoint,TDirection>implements Value{Ray:Ray<TPoint,TDirection>;MaxDistance:Number;FilterMask:Integer;}",
    "type RegularGrid<TBounds,TCounts>implements Value{Bounds:TBounds;CellCounts:TCounts;}",
    "type RidgedNoise<TPoint>implements Value,ScalarField<TPoint>{Basis:NoiseBasis;Seed:Integer;Frequency:Number;Octaves:Integer;Lacunarity:Number;Gain:Number;Offset:Number;}",
    "type SampledCurve<TPoint>implements Value,Deformable<TPoint>{Parameters:Array<Number>;Points:Array<TPoint>;}",
    "type SampledFieldGrid<TPoint,TValue,TArray,TGrid>implements Value,Field<TPoint,TValue>{Grid:TGrid;Values:TArray;}",
    "type SampledSdf<TPoint,TBounds,TArray>implements Value,BoundedSignedDistanceField<TPoint,TBounds>{Values:TArray;Bounds:TBounds;}",
    "type ScalarFunctionField<TPoint>implements ScalarField<TPoint>{Function:Function1<TPoint,Number>;}",
    "type Shear<TPoint,TDirection,TRate>implements Value,Deformation<TPoint>{Origin:TPoint;Axis:TDirection;Rate:TRate;}",
    "type SimplexNoise<TPoint>implements Value,ScalarField<TPoint>{Seed:Integer;Frequency:Number;}",
    "type Size<T>implements Value{Extents:T;}",
    "type SpatialHashGrid<TCoord,TBounds>implements Value,SpatialIndex<TBounds>{CellSize:Number;CellCoordinates:Array<TCoord>;BucketOffsets:Array<Integer>;ItemIndices:Array<ItemIndex>;}",
    "type Taper<TPoint,TDirection>implements Value,Deformation<TPoint>{Origin:TPoint;Axis:TDirection;Rate:Number;}",
    "type TcbSpline<TPoint>implements Curve<TPoint>{Points:Array<TPoint>;Tensions:Array<Number>;Continuities:Array<Number>;Biases:Array<Number>;Closed:Boolean;}",
    "type Transform<TTranslation,TRotation,TScale>implements Value{Translation:TTranslation;Rotation:TRotation;Scale:TScale;}",
    "type Triangle<TPoint>implements Geometry,ClosedShape,ConvexShape,Connected,PlanarMeasurable,PointSet<TPoint>,Centroid<TPoint>,NearestPoint<TPoint>,Deformable<TPoint>{A:TPoint;B:TPoint;C:TPoint;}",
    "type TurbulenceNoise<TPoint>implements Value,ScalarField<TPoint>{Basis:NoiseBasis;Seed:Integer;Frequency:Number;Octaves:Integer;Lacunarity:Number;Gain:Number;}",
    "type Twist<TPoint,TAxis>implements Value,Deformation<TPoint>{Origin:TPoint;Axis:TAxis;AnglePerUnit:Angle;}",
    "type ValueNoise<TPoint>implements Value,ScalarField<TPoint>{Seed:Integer;Frequency:Number;}",
    "type VectorFunctionField<TPoint,TVector>implements VectorField<TPoint,TVector>{Function:Function1<TPoint,TVector>;}",
    "type WhiteNoise<TPoint>implements Value,ScalarField<TPoint>{Seed:Integer;}",
    "type WorleyNoise<TPoint>implements Value,ScalarField<TPoint>{Seed:Integer;Frequency:Number;Jitter:Number;Distance:WorleyDistance;Feature:WorleyFeature;}",
    # Convenience aliases kept as named types (same fields, fixed arguments)
    "type AngleInterval implements IntervalLike<Angle>{Start:Angle;End:Angle;}",
    "type LengthInterval implements IntervalLike<Length>{Start:Length;End:Length;}",
    "type NumberInterval implements IntervalLike<Number>{Start:Number;End:Number;}",
    "type IntegerInterval implements IntervalLike<Integer>{Start:Integer;End:Integer;}",
]


def decl_name(line: str) -> str | None:
    m = re.match(r"^(?:concept|type)\s+([A-Za-z_][A-Za-z0-9_]*)", line)
    return m.group(1) if m else None


def kind(line: str) -> str:
    return line.split()[0]


def rewrite_implements(line: str) -> str:
    """Rewrite leftover 2D/3D concept references on surviving declarations."""
    replacements = [
        (r"\bContainsPoint2D\b", "ContainsPoint<Point2D>"),
        (r"\bContainsPoint3D\b", "ContainsPoint<Point3D>"),
        (r"\bNearestPoint2D\b", "NearestPoint<Point2D>"),
        (r"\bNearestPoint3D\b", "NearestPoint<Point3D>"),
        (r"\bCentroid2D\b", "Centroid<Point2D>"),
        (r"\bCentroid3D\b", "Centroid<Point3D>"),
        (r"\bBounded2D\b", "Bounded<Bounds<Point2D,Vector2D>>"),
        (r"\bBounded3D\b", "Bounded<Bounds<Point3D,Vector3D>>"),
        (r"\bDeformable2D\b", "Deformable<Point2D>"),
        (r"\bDeformable3D\b", "Deformable<Point3D>"),
        (r"\bDeformation2D\b", "Deformation<Point2D>"),
        (r"\bDeformation3D\b", "Deformation<Point3D>"),
        (r"\bPointSet2D\b", "PointSet<Point2D>"),
        (r"\bPointSet3D\b", "PointSet<Point3D>"),
        (r"\bSupportMappable2D\b", "SupportMappable<Point2D,Direction<Vector2D>>"),
        (r"\bSupportMappable3D\b", "SupportMappable<Point3D,Direction<Vector3D>>"),
        (r"\bMeshable2D\b", "Meshable<TriangleMesh2D>"),
        (r"\bMeshable3D\b", "Meshable<TriangleMesh3D>"),
        (r"\bScalarField2D\b", "ScalarField<Point2D>"),
        (r"\bScalarField3D\b", "ScalarField<Point3D>"),
        (r"\bVectorField2D\b", "VectorField<Point2D,Vector2D>"),
        (r"\bVectorField3D\b", "VectorField<Point3D,Vector3D>"),
        (r"\bSignedDistanceField2D\b", "SignedDistanceField<Point2D>"),
        (r"\bSignedDistanceField3D\b", "SignedDistanceField<Point3D>"),
        (r"\bBoundedSignedDistanceField2D\b", "BoundedSignedDistanceField<Point2D,Bounds<Point2D,Vector2D>>"),
        (r"\bBoundedSignedDistanceField3D\b", "BoundedSignedDistanceField<Point3D,Bounds<Point3D,Vector3D>>"),
        (r"\bSpatialIndex2D\b", "SpatialIndex<Bounds<Point2D,Vector2D>>"),
        (r"\bSpatialIndex3D\b", "SpatialIndex<Bounds<Point3D,Vector3D>>"),
        (r"\bRayIntersectable2D\b", "RayIntersectable<RayQuery<Point2D,Direction<Vector2D>>,RayHit<Point2D,Direction<Vector2D>,ItemIndex>>"),
        (r"\bRayIntersectable3D\b", "RayIntersectable<RayQuery<Point3D,Direction<Vector3D>>,RayHit<Point3D,Direction<Vector3D>,FaceIndex>>"),
        (r"\bNearestNeighborQueryable2D\b", "NearestNeighborQueryable<KNearestQuery<Point2D>>"),
        (r"\bNearestNeighborQueryable3D\b", "NearestNeighborQueryable<KNearestQuery<Point3D>>"),
        (r"\bClosestPointQueryable2D\b", "ClosestPointQueryable<Point2D,ClosestPointResult<Point2D,ItemIndex>>"),
        (r"\bClosestPointQueryable3D\b", "ClosestPointQueryable<Point3D,ClosestPointResult<Point3D,FaceIndex>>"),
        (r"\bCurve2D\b", "Curve<Point2D>"),
        (r"\bCurve3D\b", "Curve<Point3D>"),
        (r"\bClosedCurve2D\b", "ClosedCurve<Point2D>"),
        (r"\bClosedCurve3D\b", "ClosedCurve<Point3D>"),
        (r"\bPolarCurve2D\b", "PolarCurve2D"),  # keep named polar specialisation
        (r"\bPlanarCurve3D\b", "PlanarCurve3D"),
        (r"\bImplicitRegion2D\b", "ImplicitRegion<Point2D>"),
        (r"\bImplicitVolume3D\b", "ImplicitRegion<Point3D>"),
        (r"\bColorField2D\b", "Field<Point2D,Color>"),
        (r"\bColorField3D\b", "Field<Point3D,Color>"),
        (r"\bDirectionField2D\b", "Field<Point2D,Direction<Vector2D>>"),
        (r"\bDirectionField3D\b", "Field<Point3D,Direction<Vector3D>>"),
        (r"\bTensorField2D\b", "Field<Point2D,Matrix2x2>"),
        (r"\bTensorField3D\b", "Field<Point3D,Matrix3x3>"),
        (r"\bComplexField2D\b", "Field<Point2D,Complex>"),
        (r"\bPrimitiveCollection3D<", "PrimitiveCollection<"),
        (r"\bBounds2D\b", "Bounds<Point2D,Vector2D>"),
        (r"\bBounds3D\b", "Bounds<Point3D,Vector3D>"),
        (r"\bSize2D\b", "Size<Number2>"),
        (r"\bSize3D\b", "Size<Number3>"),
        (r"\bIntegerBounds2D\b", "IntegerBounds<IntegerVector2>"),
        (r"\bIntegerBounds3D\b", "IntegerBounds<IntegerVector3>"),
        (r"\bIntegerSize2D\b", "IntegerSize<IntegerVector2>"),
        (r"\bIntegerSize3D\b", "IntegerSize<IntegerVector3>"),
        (r"\bDirection2D\b", "Direction<Vector2D>"),
        (r"\bDirection3D\b", "Direction<Vector3D>"),
        (r"\bFrame2D\b", "Frame<Point2D,Direction<Vector2D>>"),
        (r"\bFrame3D\b", "Frame<Point3D,Direction<Vector3D>>"),
        (r"\bPose2D\b", "Pose<Point2D,Rotation2D>"),
        (r"\bPose3D\b", "Pose<Point3D,Quaternion>"),
        (r"\bTransform2D\b", "Transform<Vector2D,Rotation2D,Number2>"),
        (r"\bTransform3D\b", "Transform<Vector3D,Quaternion,Number3>"),
        (r"\bAffineTransform2D\b", "AffineTransform<Matrix3x2>"),
        (r"\bAffineTransform3D\b", "AffineTransform<Matrix4x3>"),
        (r"\bProjectiveTransform2D\b", "ProjectiveTransform<Matrix3x3>"),
        (r"\bProjectiveTransform3D\b", "ProjectiveTransform<Matrix4x4>"),
        (r"\bLineSegment2D\b", "LineSegment<Point2D,Vector2D>"),
        (r"\bLineSegment3D\b", "LineSegment<Point3D,Vector3D>"),
        (r"\bRay2D\b", "Ray<Point2D,Direction<Vector2D>>"),
        (r"\bRay3D\b", "Ray<Point3D,Direction<Vector3D>>"),
        (r"\bLine2D\b", "Line<Point2D,Direction<Vector2D>>"),
        (r"\bLine3D\b", "Line<Point3D,Direction<Vector3D>>"),
        (r"\bPolyline2D\b", "Polyline<Point2D>"),
        (r"\bPolyline3D\b", "Polyline<Point3D>"),
        (r"\bTriangle2D\b", "Triangle<Point2D>"),
        (r"\bTriangle3D\b", "Triangle<Point3D>"),
        (r"\bQuad2D\b", "Quad<Point2D>"),
        (r"\bQuad3D\b", "Quad<Point3D>"),
        (r"\bPointCloud2D\b", "PointCloud<Point2D>"),
        (r"\bPointCloud3D\b", "PointCloud<Point3D>"),
        (r"\bCapsule2D\b", "Capsule<Point2D>"),
        (r"\bCapsule3D\b", "Capsule<Point3D>"),
        (r"\bBezierCurve2D\b", "BezierCurve<Point2D>"),
        (r"\bBezierCurve3D\b", "BezierCurve<Point3D>"),
        (r"\bCubicBezier2D\b", "CubicBezier<Point2D>"),
        (r"\bCubicBezier3D\b", "CubicBezier<Point3D>"),
        (r"\bQuadraticBezier2D\b", "QuadraticBezier<Point2D>"),
        (r"\bQuadraticBezier3D\b", "QuadraticBezier<Point3D>"),
        (r"\bBSplineCurve2D\b", "BSplineCurve<Point2D>"),
        (r"\bBSplineCurve3D\b", "BSplineCurve<Point3D>"),
        (r"\bNurbsCurve2D\b", "NurbsCurve<Point2D>"),
        (r"\bNurbsCurve3D\b", "NurbsCurve<Point3D>"),
        (r"\bBitmap\b", "ImageBuffer<Color8>"),
        (r"\bFloatImage\b", "ImageBuffer<Color>"),
        (r"\bGrayscaleImage\b", "ImageBuffer<Number>"),
        (r"\bBinaryImage\b", "ImageBuffer<Boolean>"),
        (r"\bNormalImage\b", "ImageBuffer<Vector3D>"),
        (r":Bounds2D\b", ":Bounds<Point2D,Vector2D>"),
        (r":Bounds3D\b", ":Bounds<Point3D,Vector3D>"),
        (r":Size2D\b", ":Size<Number2>"),
        (r":Size3D\b", ":Size<Number3>"),
        (r":IntegerBounds2D\b", ":IntegerBounds<IntegerVector2>"),
        (r":IntegerBounds3D\b", ":IntegerBounds<IntegerVector3>"),
        (r":IntegerSize2D\b", ":IntegerSize<IntegerVector2>"),
        (r":IntegerSize3D\b", ":IntegerSize<IntegerVector3>"),
        (r":Direction2D\b", ":Direction<Vector2D>"),
        (r":Direction3D\b", ":Direction<Vector3D>"),
        (r":Frame2D\b", ":Frame<Point2D,Direction<Vector2D>>"),
        (r":Frame3D\b", ":Frame<Point3D,Direction<Vector3D>>"),
        (r":Pose2D\b", ":Pose<Point2D,Rotation2D>"),
        (r":Pose3D\b", ":Pose<Point3D,Quaternion>"),
        (r":Transform2D\b", ":Transform<Vector2D,Rotation2D,Number2>"),
        (r":Transform3D\b", ":Transform<Vector3D,Quaternion,Number3>"),
        (r":Ray2D\b", ":Ray<Point2D,Direction<Vector2D>>"),
        (r":Ray3D\b", ":Ray<Point3D,Direction<Vector3D>>"),
        (r":Line2D\b", ":Line<Point2D,Direction<Vector2D>>"),
        (r":Line3D\b", ":Line<Point3D,Direction<Vector3D>>"),
        (r":Polyline2D\b", ":Polyline<Point2D>"),
        (r":Polyline3D\b", ":Polyline<Point3D>"),
        (r":Triangle2D\b", ":Triangle<Point2D>"),
        (r":Triangle3D\b", ":Triangle<Point3D>"),
        (r":PointCloud2D\b", ":PointCloud<Point2D>"),
        (r":PointCloud3D\b", ":PointCloud<Point3D>"),
        (r":Capsule2D\b", ":Capsule<Point2D>"),
        (r":Capsule3D\b", ":Capsule<Point3D>"),
        (r"Array<Bounds2D>", "Array<Bounds<Point2D,Vector2D>>"),
        (r"Array<Bounds3D>", "Array<Bounds<Point3D,Vector3D>>"),
        (r"Array<Direction2D>", "Array<Direction<Vector2D>>"),
        (r"Array<Direction3D>", "Array<Direction<Vector3D>>"),
        (r"Array<Pose3D>", "Array<Pose<Point3D,Quaternion>>"),
        (r"Array<Transform3D>", "Array<Transform<Vector3D,Quaternion,Number3>>"),
        (r"Array<FloatImage>", "Array<ImageBuffer<Color>>"),
        (r"Array<Bitmap>", "Array<ImageBuffer<Color8>>"),
        (r"RegularGrid2D", "RegularGrid<Bounds<Point2D,Vector2D>,IntegerVector2>"),
        (r"RegularGrid3D", "RegularGrid<Bounds<Point3D,Vector3D>,IntegerVector3>"),
    ]
    for pattern, repl in replacements:
        line = re.sub(pattern, repl, line)
    return line


def main() -> int:
    if not SRC.is_file():
        print(f"Missing source index: {SRC}", file=sys.stderr)
        return 1

    kept: list[str] = []
    for raw in SRC.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line:
            continue
        name = decl_name(line)
        if name in DROP_EXACT:
            continue
        # Interval concretes are re-injected in generic-friendly form; drop originals to avoid dupes
        if name in {"AngleInterval", "LengthInterval", "NumberInterval", "IntegerInterval"}:
            continue
        kept.append(rewrite_implements(line))

    concepts = [ln for ln in kept if kind(ln) == "concept"] + INJECT_CONCEPTS
    types = [ln for ln in kept if kind(ln) == "type"] + INJECT_TYPES

    def sort_key(line: str) -> str:
        return decl_name(line) or line

    concepts = sorted(set(concepts), key=sort_key)
    types = sorted(set(types), key=sort_key)

    header = [
        "# DESIGN SKETCH - not the live index.",
        "# Generated by tools/propose-merged-types-index.py from stdlib/types-and-concepts.txt.",
        "# Intent: collapse 2D/3D twins and repeated families behind type parameters.",
        "# Geometry2D/Geometry3D markers, polar/planar specialisations, and domain-specific",
        "# sums are kept where a parameter would erase a real distinction.",
        "# Convenience spellings people still want in APIs:",
        "#   Bounds2D = Bounds<Point2D,Vector2D>, Direction3D = Direction<Vector3D>,",
        "#   Pose3D = Pose<Point3D,Quaternion>, Bitmap = ImageBuffer<Color8>, etc.",
        "#   Annulus = RadialShellPlanar; SphericalShell ~ RadialShellSolid;",
        "#   CylindricalShell still wants Axis+Height (not fully collapsed here).",
        "#",
    ]

    body = header + concepts + types
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(body) + "\n", encoding="utf-8", newline="\n")

    src_concepts = sum(1 for ln in SRC.read_text(encoding="utf-8").splitlines() if ln.startswith("concept "))
    src_types = sum(1 for ln in SRC.read_text(encoding="utf-8").splitlines() if ln.startswith("type "))
    print(f"Wrote {OUT}")
    print(f"  live:     {src_concepts} concepts, {src_types} types")
    print(f"  proposed: {len(concepts)} concepts, {len(types)} types")
    print(f"  delta:    {len(concepts) - src_concepts:+d} concepts, {len(types) - src_types:+d} types")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
