<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\parakeet\Parakeet.Parsers\Ara3D.Parakeet.Parsers.csproj" />
    <ProjectReference Include="..\..\parakeet\Parakeet\Ara3D.Parakeet.csproj" />
    <PackageReference Include="Ara3D.SDK.Core" Version="$(Ara3DVersion)" />
    <ProjectReference Include="..\Plato.AST\Plato.AST.csproj" />
    <ProjectReference Include="..\..\writers\Plato.CSharpWriter\Plato.CSharpWriter.csproj" />
    <ProjectReference Include="..\..\writers\Plato.TypeScriptWriter\Plato.TypeScriptWriter.csproj" />
    <ProjectReference Include="..\..\writers\Plato.RustWriter\Plato.RustWriter.csproj" />
    <ProjectReference Include="..\..\writers\Plato.GlslWriter\Plato.GlslWriter.csproj" />
    <ProjectReference Include="..\Plato.Compiler\Plato.Compiler.csproj" />
    <ProjectReference Include="..\..\writers\Plato.CppWriter\Plato.CppWriter.csproj" />
  </ItemGroup>

</Project>
